### ISSUE TITLE
Colorcodes not working correctly with Questnames & Questrequirements

### ISSUE THREAD

**Issue by EazyAce** [PikaMug/Quests#1198]
**What is your Quests version / build number (do _not_ say "latest")?**
quests 3.9.1-b86 for MC 1.14.4

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When giving Quests Names with Colorcodes for example "&btestquest" and make a second quest with questrequieremnt for the first quests, it will not work. It doesn't matter if you use the ingame editor (After reloading the quest, the quest will not be loaded / working anymore) or editing it in the config ( wont load eitherway).

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Few more Information.
Yes, all quests were working fine before adding the colored names.
Even coloring the name is working fine, ONLY the quests with the questrequirements wont work anymore. Here is a list of everything we tried so far.
```
  custom1:
    name: '&3testquest1'
```
v1
```
  custom2:
    name: '&btestquest2'
    requirements:
      quests:
      - '&3testquest1'
```
v2
```
  custom2:
    name: '&btestquest2'
    requirements:
      quests:
      - &3testquest1
```
v3
```
  custom2:
    name: '&btestquest2'
    requirements:
      quests:
      - testquest1
```
v4
```
  custom2:
    name: '&btestquest2'
    requirements:
      quests:
      - custom1
```

As said, we even tryed the ingame Editor. If using the ingame editor the requirement is looking like this in the config, dont know why & doenst work.

```
  custom1:
    name: '&btestquest2'
    requirements:
      - §3testquest1!
```
