### ISSUE TITLE
attempted to take quest "null" but something went wrong

### ISSUE THREAD

**Issue by chivivor** [PikaMug/Quests#1252]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.2-b94
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When new player joins server after restart or /questadmin reload they get an error when trying to accept a quest.

<player name here> attempted to take quest "null" but something went wrong

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

All quests do this but here is one I created below:
```
  custom6:
    name: Witch Hunt
    ask-message: Find the terrible witch tower to the south and destroy 20 witches!
    finish-message: You have completed the witch hunt!
    npc-giver-id: 35
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Witch
          mob-amounts:
          - 20
          locations-to-kill:
          - world 95.0 68.0 257.0
          kill-location-radii:
          - 30
          kill-location-names:
          - Witch Tower
    rewards:
      money: 300
      quest-points: 30
      exp: 400
    options:
      allow-commands: true
      allow-quitting: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
      require-same-quest: true
```
