### ISSUE TITLE
Citizens do nothing when I click them

### ISSUE THREAD

**Issue by M4RC0Sx** [PikaMug/Quests#1345]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests3.9.5, Citizens Citizens-2.0.27-b2044

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
No errors in console. I create my NPC and I create a quest with this NPC start. Firstly, clicking the NPC doesn´t give its ID, which is strange. I create a stage, the messages, the GUI and all necessary things I think. Save all, reload the plugin but NPC does nothing. I also tried reinstalling the plugin and restarting the server.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
```
custom1:
    name: Ukeke1
    ask-message: Bueno, parece que hubo un error en el viaje. Nada importante. Cuando
      estés listo, necesito que hagas algo por mí. He visto anomalias al llegar, mata
      300 esqueletos para investigarlo.
    finish-message: Esto es malo... Por lo que veo se está produciendo un cambio genético
      en la composición de su código. No comprendo muy bien que pasa, pero es una
      mala señal. Vé con Lancer en el spawn y dile lo que ha pasado, yo voy a explorar
      más al respecto.
    npc-giver-id: 114
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      type: SKULL_ITEM
      meta:
        ==: ItemMeta
        meta-type: SKULL
        lore:
        - Ukeke1
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Skeleton
          mob-amounts:
          - 300
          start-message: '&6&lMISIONES &E>> &7Comienza tu misión: &aUkeke1'
          complete-message: '&6&lMISIONES &E>> &7Has completado la misión: &aUkeke1'
    rewards:
      money: 5000
    options:
      allow-commands: true
      allow-quitting: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
      require-same-quest: true
```
