### ISSUE TITLE
Specifying enchant to get not working

### ISSUE THREAD

**Issue by DrakePork** [PikaMug/Quests#1458]
**What is your Quests version / build number (do _not_ say "latest")?** 
4.0.0-rc.2-b157

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
With the new changes in how the plugin handles enchant items, specifying what enchant to get no longer works. If you just specify the item you want to enchant without specifying which enchant it works, but if you specify an enchant to get it will no longer work.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
[Pastebin of quest with specified enchant](https://pastebin.com/Ym4xALm7)

**Comment by PikaMug** [comment]
Thanks for the report. I've confirmed the issue, although your shared quest is missing a node and should look like:
```yaml
stages:
  ordered:
    '1':
      items-to-enchant:    <--- MISSING NODE
      - ==: org.bukkit.inventory.ItemStack
        v: 2584
        type: DIAMOND_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
```

Correcting this allows me to take the quest properly, but there is still something awry with the enchantment event. Hoping to find a solution soon.
