### ISSUE TITLE
Quests no longer loading

### ISSUE THREAD

**Issue by KeeLampshade** [PikaMug/Quests#1561]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.0.0-rc.3
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Quests from quests.yml are not loading. The yml file still has all of the quests in it, but when I run the reload command in-game it says 0 Quests loaded. Happened without my noticing and now can't get them in-game again. No idea how it happened so no idea to replicate it.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/d13nMT0V

**Comment by PikaMug** [comment]
Thanks for the report. I would guess that this part is to blame:

```yaml
        initialAction:
          book: ''
          cancelTimer: false
          clearInv: false
          commands: []
          denizenScript: ''
          effects: {}
          explosions: []
          failQuest: false
          health: -1.0
          hunger: -1
          items: []
          lightningStrikes: []
          message: null
          mobSpawns: []
          name: AppleStart
          potionEffects: []
          saturation: -1
          stormDuration: 0
          stormWorld: null
          teleport: null
          thunderDuration: 0
          thunderWorld: null
          timer: 0
        name: Apple Pickin'
        npcStart: !!net.citizensnpcs.npc.CitizensNPC
          flyable: false
          name: Old Peculier
          protected: true
        regionStart: null
```

Backup your file, then try deleting that section and let me know if you need further assistance.
