### ISSUE TITLE
Not showing all particles

### ISSUE THREAD

**Issue by QuakyCZ** [PikaMug/Quests#1597]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.0 rc.4
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Hello, when I try to edit the particle effect of new quest, it doesn't appear. For me works just note, heart and composter. Am I doing something wrong? Thank you for answer.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

```yml
npc-effects:
  enabled: true
  new-quest: heart
  redo-quest: angry_villager
```

![img](https://i.ibb.co/Hp8pNmp/2021-02-01-13-41-19.png)
```yml
npc-effects:
  enabled: true
  new-quest: happy_villager
  redo-quest: angry_villager
```
![img](https://i.ibb.co/fGqYdZV/2021-02-01-13-41-18.png)
