### ISSUE TITLE
Quest error messages spamming console

### ISSUE THREAD

**Issue by sweatingbullets67** [PikaMug/Quests#1689]
**What is your Quests version / build number (do _not_ say "latest")?** Version 4.0.2

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?** 
-"[16:48:41 ERROR]: [Quests] currentStage was null for 6e0f5881-9cd5-4feb-841d-804ea4a23d44 on chat for quest Local Crawlers" 
-"[17:15:29 ERROR]: Could not pass event BlockDamageEvent to Quests v4.0.2-b238" 
   these are example messages of what I get any time I make a new quest. I've made 33 quests before this without any issues, now when I make a quest, these error messages spam the console. This also occurs when I duplicate an existing quest, changing basic details like name of the quest and the starting NPC.
  Also if it helps. Despite the error messages, the quests still work fine. It's just flooding the console and we are concerned of just not knowing what the issue is.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
Sorry, I don't know what you mean by using a pastebin, but here's one of the quests that are spamming the console.
```
 custom2:
    name: Crawling Critters
    ask-message: Kill 10 spiders
    finish-message: Well done!
    npc-giver-id: 39
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Spider
          mob-amounts:
          - 10
          start-message: kill 10 spiders
    rewards:
      quest-points: 1
    planner:
      cooldown: 900
```
