### ISSUE TITLE
 You can't reach the a items task like crafting after you quit game

### ISSUE THREAD

**Issue by qnsqns** [PikaMug/Quests#1784]
What is your Quests version / build number (do not say "latest")?
4.06
Describe the problem and how to replicate it. Any console errors to post using a pastebin?
it is when you testing the quest，when you quit the game ，you can't reach the a items task like crafting .Until you accept the task again
If applicable, can you provide an example quest from quests.yml using a pastebin?
```yaml
  custom2:
    name: 铁甲
    ask-message: 挑战目标！
    finish-message: 做得好！
    stages:
      ordered:
        '1':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: IRON_HELMET
          - ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: IRON_CHESTPLATE
          - ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: IRON_LEGGINGS
          - ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: IRON_BOOTS
    planner:
      override: true
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: false
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: true
```
