### ISSUE TITLE
Quest Requirements are not working anymore

### ISSUE THREAD

**Issue by kromacie** [PikaMug/Quests#1786]
Hi, I have a problem with your plugin. It seems that it's not working on my paper 1.17.1 server.
The description is below.

**What is your Quests version / build number (do _not_ say "latest")?**
Plugin: Quests 4.0.7
Client: Optifine 1.17.1
Server: Paper 1.17.1

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Set quest requirement to 2x dirt, collect 2 or more blocks of dirt. Try to accept quest having 2x dirt in our inventory. Quest is not accepted even though you meet the requirements.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
```
# For non-English characters, this file MUST stay encoded in UTF-8
quests:
  custom1:
    name: Test Quest
    ask-message: Challenge objectives!
    finish-message: Well done!
    requirements:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: DIRT
        amount: 2
      remove-items:
      - false
    stages:
      ordered:
        '1':
          npc-ids-to-talk-to:
          - 3
          npc-ids-to-kill:
          - 12
          npc-kill-amounts:
          - 1
          locations-to-reach:
          - world 7.0 71.0 288.0
          reach-location-radii:
          - 10
          reach-location-names:
          - Some place in the grass
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```

I really appreciate any help you can provide. Thanks.
