### ISSUE TITLE
[bug][sql] kill mob/item delivery task cannot get update after relogging to server

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1792]
**What is your Quests version / build number (do _not_ say "latest")?**

Quests-4.0.7#264

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

0. wipe database
1. make a quest that kill mobs, lets say 1000 zombie
2. kill some zombie
3. relogin into server
4. kill some zombie
can reproduce that zombie kill count does not change when kill zombie

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://paste.gg/p/anonymous/7493dd27935b44cc81e8cce24cbc282d

**Comment by PikaMug** [comment]
I wasn't able to reproduce this with YAML, but I'll try again with MYSQL and get back to you.

**Comment by hkkongou** [comment]
> I wasn't able to reproduce this with YAML, but I'll try again with MYSQL and get back to you.

hi, i also tested with other objective with yaml or mysql and i found out that this is a problem for MYSQL kill mob counting.
other objectives such as breaking blocks work with MYSQL or YAML, but KILL MOB does not work for MYSQL, work for YAML.

so the only problem is kill mob objective in mysql is not updating after the the player relogin server.
in mysql mode, kill mob object only counting the kills when the player take a quest without relogin, after relogin, the number is stuck.

**Comment by hkkongou** [comment]
update: also tested with item delivery , mysql also does not update.
quest in the following, only require delivery vanilla rotten flesh to 1 npc, right clicking the npc with vanilla rotten flesh, the npc does not resonse with anything, no message is saying the item is appropriate or not .

```
  default2:
    name: Mob Hunter
    ask-message: §eKill an assortment of Mobs.
    finish-message: §eExcellent. Here is a §dDiamond Sword§e.
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: ROTTEN_FLESH
            amount: 64
          npc-delivery-ids:
          - 2011
          delivery-messages:
          - .
          finish-event: NiceFinish
          death-event: DeathFail
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2586
        type: DIAMOND_SWORD
      quest-points: 1
      exp: 100
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```
