### ISSUE TITLE
mob-spawn-locations contains an invalid location

### ISSUE THREAD

**Issue by SergiX44** [PikaMug/Quests#1815]
**What is your Quests version / build number (do _not_ say "latest")?**
v.4.1.0-b272

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Hello, a few days ago I noticed this error in creating an action that summons mobs: 
mob-spawn-locations contains an invalid location
https://pastebin.com/hMQBEg8w
I have used this feature before and it has always worked.
i tried changing spawn location and mobs, but it keeps giving me error. An empty action is generated in the actions.yml file.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
```
test:
    mob-spawns:
      '0': {}
```
modifying the action.yml file manually solves the problem.
```
arena6_w2:
    mob-spawns:
      '0':
        spawn-location: world_quest -234.0 5.0 -263.0
        mob-type: WITHER_SKELETON
        spawn-amounts: 3
```
