### ISSUE TITLE
Data Loss After new Update

### ISSUE THREAD

**Issue by dsevvv** [PikaMug/Quests#1908]
### What is your Quests version / build number (do _not_ say "latest")?

Quests 4.2.3-b307

### Describe the problem and how to replicate it.

After updating to the new version released, the next day I have noticed that all players that join the server have their Quests data RESET. This is a massive issue. Please help.

### Any console errors to share?

```shell
None
```

### If applicable, can you provide an example quest from quests.yml?

```shell
custom2:
    name: §4§lDragon Slayer | Part 1
    ask-message: '&aDo you believe you can slay the dragon? **&6&lREWARDS&a** &dDragon
      Egg x4&a, &65 Quest Points&a, &e1000 Experience&a.'
    finish-message: Impressive... take this.
    npc-giver-id: 21
    requirements:
      quest-points: 20
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Ender Dragon
          mob-amounts:
          - 1
        '2':
          npc-ids-to-talk-to:
          - 21
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2865
        type: DRAGON_EGG
        amount: 4
      quest-points: 5
      exp: 1000
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```

**Comment by PikaMug** [comment]
My guess would be this is related to your use of the `§` character in quest names. Try replacing all instances of `§` with `&`.

**Comment by dsevvv** [comment]
When I am creating these quests I only ever use the '&' selector. When the Quests get saved it is converted.

**Comment by PikaMug** [comment]
That doesn't happen for me using the editor:
```yml
  custom4:
    name: '&aTest'
    ask-message: Challenge objectives!
    finish-message: Well done!
    stages:
      ordered:
        '1':
          break-block-names:
          - dirt
          break-block-amounts:
          - 1
          break-block-durability:
          - 0
```

Please try making the change anyway and report back.

**Comment by dsevvv** [comment]
> That doesn't happen for me using the editor:
> 
> ```yaml
>   custom4:
>     name: '&aTest'
>     ask-message: Challenge objectives!
>     finish-message: Well done!
>     stages:
>       ordered:
>         '1':
>           break-block-names:
>           - dirt
>           break-block-amounts:
>           - 1
>           break-block-durability:
>           - 0
> ```
> 
> Please try making the change anyway and report back.

Sorry for taking a couple days.

I went ahead and changed all of the cases of § to & and added "" where needed.

Player data was still wiped when the player joined.

**Comment by PikaMug** [comment]
Thank you. Are you using YAML (default) or MySQL for player data storage?

**Comment by legendofgow** [comment]
We have the same problem with all quests
Paper 1.18.2

```
quests:
  custom1:
    name: Zabij 25 szkieletow
    ask-message: Rzuć wyzwanie celom!
    finish-message: Dobra robota!
    npc-giver-id: 16
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Skeleton
          mob-amounts:
          - 25
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2865
        type: IRON_NUGGET
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Silver
            Coin"}],"text":""}'
          lore:
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Material"}],"text":""}'
          - '{"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"A
            very shiny silver coin."}],"text":""}'
          enchants:
            DURABILITY: 1
          attribute-modifiers:
            GENERIC_ATTACK_SPEED:
            - ==: org.bukkit.attribute.AttributeModifier
              amount: 0.0
              name: mmoitemsDecoy
              uuid: 87851e28-af12-43f6-898e-c62bde6bd0ec
              operation: 0
          ItemFlags:
          - HIDE_ENCHANTS
          - HIDE_ATTRIBUTES
          internal: H4sIAAAAAAAA/31QTUvDQBCd3halUgUPngxzyEkUT0Jva7q2C9lN2V2EsA1LLFGDJYU0CqX0R/U3+MfcVhotgjA8mHnz8eYdARA4FyLhhgntBqmkgkcuThSDG4vhVORNUZf5DK/QR3hHg4+iXgaL17LyWM58FkznZXWNGYGzdtEWnUnHDIighilOYwK9Q5oP4Fjz+JEpFyVcEui2vFfBoBs+6+8DkT9A4GSkjUodk9GISqNhvELd5A32cV/yCpOhbub1Evt2he26Pe8+N4um9gN2gu/VU13kb2X1EtxOMMN1tiZw+mcEevagFbMOXPz4xTW9j5mLFH0wXA47v5/YmXhp/zcNvgAOgskVggEAAA==
      money: 1000
      quest-points: 1
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: true
```

Using YAML
