### ISSUE TITLE
Major issue with quests / new version 4.4.0

### ISSUE THREAD

**Issue by KobrazGaming** [PikaMug/Quests#1937]
### What is your Quests version / build number (do *not* say "latest")?

4.4.0 

### Describe the problem and how to replicate it.

Server was running 4.3.1, im working for a large server network with 200+ quests and unfortunately weve run into a pretty big issue thats scaring us... The plugin was working fine until we updated it to the most recent version, we shut down the server, everything saved successfully. We then uninstalled 4.3.1 and replaced it with 4.4.0, this is where the problems began. Server started with no problems, i tried to start a quest that had requirements to check everything was still working, i typed /quests take NAME, it returned yes/no i clicked yes, and it returned a weird value, it said "Requirements:" with nothing after, which was strange because the quest i was taking did indeed have requirements. I thought nothing of it, did some more testing and realized it literally broke every single quest we had installed, every quest regardless of if it had requirements or not, when started will return "Requirements:" when taken. This was not an issue before the update, we have tried countless times uninstalling and reinstalling older versions or current versions to repair the issue, with no luck. Were starting to get worried it corrupted or damaged something. Any help or a fix would be amazing. 

### Any console errors to share?

```shell
This error is not pasting any console errors.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom3:
    name: Stimulating Developments Part III
    ask-message: Welcome back, Osiris has been working on a new serum that provides
      tamed animals with a health and speed boost. But for that, we need you to tame
      a wolf. Good luck!
    finish-message: Nicely Done!
    requirements:
      quests:
      - custom1
      - custom2
    stages:
      ordered:
        '1':
          mobs-to-tame:
          - wolf
          mob-tame-amounts:
          - 1
    rewards:
      money: 2000
      permissions:
      - osirislevel.1
```
