### ISSUE TITLE
Problem with objective : Killing NPC

### ISSUE THREAD

**Issue by WorldofOlendor** [PikaMug/Quests#1938]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.4.0 build #325

### Describe the problem and how to replicate it.

When I create a quest in which I have to kill NPCs and I try to complete it, the NPC kills are not counted, thus preventing me from progressing in the quest objectives.
There are no errors in the console and the rest of the quest works.

### Any console errors to share?

```shell
No console errors appears
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom38:
    name: Entrons chez les Chevaliers
    ask-message: Alors comme ça, tu souhaites devenir un Chevalier ? Pour ça il va
      te falloir accomplir mes épreuves l'ami.
    finish-message: Ce sera un honneur pour l'Ordre des Chevaliers de te compter dans
      ses rangs. Je te rappel qu'il te faut bien choisir ta division. N'oublie pas
      cela lors de ton entretien avec Dame Almarth.
    npc-giver-id: 4567
    requirements:
      permissions:
      - Citoyen
    stages:
      ordered:
        '1':
          npc-ids-to-talk-to:
          - 3736
          locations-to-reach:
          - Olengard -1196.0 54.0 1856.0
          reach-location-radii:
          - 5
          reach-location-names:
          - Sentier de Genesis
          start-message: Tout d'abord, tu vas te rendre à l'extérieur de la ville,
            aux abords du cimetierre. Un voyageur se trouve là-bas. Il te donnera
            une tâche, une fois accompli, reviens me voir.
          complete-message: Dites l'ami, pourriez-vous m'aider ? Un brigant sur la
            coline au derrière-moi n'arrête pas d'attaquer les visiteurs. Pourriez-vous
            lui donner une bonne correction ?
        '2':
          npc-ids-to-kill:
          - 4116
          npc-kill-amounts:
          - 1
          start-message: '=== Objectif : Éliminez le Brigant de l''Est se trouvant
            au sommet de la colline ==='
          complete-message: === Objectif Accompli ; Retournez parler au voyageur.
            ===
        '3':
          npc-ids-to-talk-to:
          - 3736
          - 4567
          start-message: '=== Objectif : Retournez parler au voyageur puis retournez
            voir le Recruteur. ==='
          complete-message: Alors comme ça le brigant n'était pas mort ? Surprenant.
        '4':
          npc-ids-to-talk-to:
          - 3689
          start-message: Bien, maintenant que ça c'est fait, rend-toi auprès de l'entraîneur,
            il paraît qu'il à besoin d'un coup de main. Si tu le cherches, il se trouve
            sur notre terrain d'entraînement plus loin sur le chemin.
          complete-message: C'est toi l'nouveau ? J'ai besoin d'un coup de main.
        '5':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: SHIELD
          npc-delivery-ids:
          - 3689
          delivery-messages:
          - Un nouveau bouclier, enfin !
          start-message: Vois-tu, mon bouclier s'est briser récemment. Malheureusement
            pour moi, j'ai pas le temps d'en récupérer un. Ce serait sympa si tu pouvais
            t'en occuper pour moi.
          complete-message: Merci l'ami. Tu me sauves la vie !
        '6':
          npc-ids-to-talk-to:
          - 4567
          start-message: '=== Nouvel Objectif : Retournez parler au recruteur ==='
          complete-message: Bien, passons à la dernière épreuve !
        '7':
          npc-ids-to-kill:
          - 4114
          npc-kill-amounts:
          - 1
          start-message: Il y a, au nord d'ici, sur une petite île avec trois arbres
            dessus, un bandit qui campe depuis quelques semaines. Si tu parviens à
            l'éliminer, je te donnerais le ticket de validation pour ton entrée chez
            nous.
          complete-message: === Objectif accompli ! ===
        '8':
          npc-ids-to-talk-to:
          - 4567
          start-message: '=== Objectif : Retournez parler au recruteur. ==='
          complete-message: Ainsi donc tu y es parvenu, bravo.
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: PAPER
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"text":"Ticket de Validation"}],"text":""}'
          lore:
          - '{"extra":[{"text":"Valide votre entrée dans l''ordre des Chevaliers"}],"text":""}'
```
