### ISSUE TITLE
Can't Start a quest / 1.16.5

### ISSUE THREAD

**Issue by 91leMAC** [PikaMug/Quests#1939]
### What is your Quests version / build number (do *not* say "latest")?

4.4.0

### Describe the problem and how to replicate it.

**Problem :** I create a new quest, but I can't start it, I try with an NPC and a block location but still not starting the quest.

### Any console errors to share?

```shell
>.... [18:13:37 INFO]: 90leMAC issued server command: /questadmin reload
>.... [18:13:37 WARN]: [Quests] There are new language phrases in /lang/en-US/strings_new.yml for the current version! You must transfer them to, or regenerate, strings.yml to remove this warning!
>.... [18:13:37 WARN]: [Quests] There are new language phrases in /lang/en-US/strings_new.yml for the current version! You must transfer them to, or regenerate, strings.yml to remove this warning!
>.... [18:13:37 WARN]: [Quests] There are new language phrases in /lang/en-US/strings_new.yml for the current version! You must transfer them to, or regenerate, strings.yml to remove this warning!
>.... [18:13:37 WARN]: [Quests] There are new language phrases in /lang/en-US/strings_new.yml for the current version! You must transfer them to, or regenerate, strings.yml to remove this warning!
>.... [18:13:37 WARN]: [Quests] There are new language phrases in /lang/en-US/strings_new.yml for the current version! You must transfer them to, or regenerate, strings.yml to remove this warning!
>.... [18:13:37 WARN]: [Quests] There are new language phrases in /lang/en-US/strings_new.yml for the current version! You must transfer them to, or regenerate, strings.yml to remove this warning!
>.... [18:13:37 WARN]: [Quests] There are new language phrases in /lang/en-US/strings_new.yml for the current version! You must transfer them to, or regenerate, strings.yml to remove this warning!
>.... [18:13:37 WARN]: [Quests] There are new language phrases in /lang/en-US/strings_new.yml for the current version! You must transfer them to, or regenerate, strings.yml to remove this warning!
>.... [18:13:37 WARN]: [Quests] There are new language phrases in /lang/en-US/strings_new.yml for the current version! You must transfer them to, or regenerate, strings.yml to remove this warning!
>.... [18:13:37 WARN]: [Quests] There are new language phrases in /lang/en-US/strings_new.yml for the current version! You must transfer them to, or regenerate, strings.yml to remove this warning!
>.... [18:13:37 WARN]: [Quests] There are new language phrases in /lang/en-US/strings_new.yml for the current version! You must transfer them to, or regenerate, strings.yml to remove this warning!
>.... [18:13:37 INFO]: [Quests] Loaded language en-US. Translations via Crowdin
>.... [18:13:37 WARN]: me.blackvein.quests.exceptions.QuestFormatException: npc-giver-id has invalid NPC ID 1, see quest of ID default1
>.... [18:13:37 WARN]: at me.blackvein.quests.Quests.loadQuest(Quests.java:1866)
>.... [18:13:37 WARN]: at me.blackvein.quests.Quests.loadQuests(Quests.java:1794)
>.... [18:13:37 WARN]: at me.blackvein.quests.Quests.lambda$reload$5(Quests.java:1720)
>.... [18:13:37 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:98)
>.... [18:13:37 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [18:13:37 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:20)
>.... [18:13:37 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
>.... [18:13:37 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
>.... [18:13:37 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [18:13:37 WARN]: me.blackvein.quests.exceptions.QuestFormatException: npc-giver-id has invalid NPC ID 17, see quest of ID custom2
>.... [18:13:37 WARN]: at me.blackvein.quests.Quests.loadQuest(Quests.java:1866)
>.... [18:13:37 WARN]: at me.blackvein.quests.Quests.loadQuests(Quests.java:1794)
>.... [18:13:37 WARN]: at me.blackvein.quests.Quests.lambda$reload$5(Quests.java:1720)
>.... [18:13:37 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:98)
>.... [18:13:37 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [18:13:37 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:20)
>.... [18:13:37 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
>.... [18:13:37 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
>.... [18:13:37 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [18:13:37 WARN]: me.blackvein.quests.exceptions.QuestFormatException: npc-giver-id has invalid NPC ID 40, see quest of ID custom3
>.... [18:13:37 WARN]: at me.blackvein.quests.Quests.loadQuest(Quests.java:1866)
>.... [18:13:37 WARN]: at me.blackvein.quests.Quests.loadQuests(Quests.java:1794)
>.... [18:13:37 WARN]: at me.blackvein.quests.Quests.lambda$reload$5(Quests.java:1720)
>.... [18:13:37 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:98)
>.... [18:13:37 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [18:13:37 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:20)
>.... [18:13:37 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
>.... [18:13:37 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
>.... [18:13:37 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [18:13:37 WARN]: [Quests] Unable to consider custom objectives because quest for default1 was null
>.... [18:13:37 WARN]: [Quests] Unable to consider custom objectives because quest for custom2 was null
>.... [18:13:37 WARN]: [Quests] Unable to consider custom objectives because quest for custom3 was null
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
name: test1
    ask-message: voici les objectifs de test1
    finish-message: Voici le message de fin de test1
    npc-giver-uuid: 9b63cdef-8da1-4aee-8514-d59975a94107
    block-start: world 1787.0 76.0 -2649.0
    stages:
      ordered:
        '1':
          break-block-names:
          - DIRT
          break-block-amounts:
          - 3
          break-block-durability:
          - 0
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2586
        type: DIRT
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"text":"rewardTest1"}],"text":""}'
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```
