### ISSUE TITLE
'Kill NPC' Quests not being completed when done with ranged weapons

### ISSUE THREAD

**Issue by samwise-gamgee1** [PikaMug/Quests#1940]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.4.0-b325

### Describe the problem and how to replicate it.

When performing a quest with an objective to Kill an NPC (usually using the sentinel plugin), killing the NPC counts for the quest if you do so in melee but not if you do so at range. For example, killing the NPC with a sword or an axe always works and advances the quest to its next stage, killing with a trident only works if you do so in melee, and throwing potions, shooting with crossbows/bows, and throwing tridents never count for the quest. The NPC may die, but unless you land the finishing blow in melee the quest won't progress. Please fix this so the quest plugin attributes ranged weapons to players when killing quest NPCs, and thank you.

### Any console errors to share?

```shell
There are no console outputs whatsoever when the required quest NPC is killed at range; the outputs are normal when the NPC is killed in melee.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Here's one such quest. Pretty simple one; "Assassinate the Goblin King." You have to find the place where he lives, then kill him and escape with the axes he wields. That's it. 

custom20:
    name: Assassinate the Goblin King
    ask-message: Greetings, traveller. If you've a spare axe to lend to our hold's
      cause, there's dirty work we need done. The King of Goblin Town southwest of
      here holds a great many curses to his name, yet we have been unable to slay
      him in battle. There is now a bounty.
    finish-message: Stranger, how you came to slay the Goblin King in his own stronhold
      is a feat I cannot imagine, but you have earned great honors and riches for
      this deed. Thank you, brother in arms.
    npc-giver-id: 739
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 2975
      type: DIAMOND_AXE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_purple","text":"Assassinate
          the Goblin King"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"Greetings,
          traveller. If you''ve a spare "}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"axe
          to lend to our hold''s cause, there''s "}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"dirty
          work we need done. The King of "}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"Goblin
          Town southwest of here holds a "}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"great
          many curses to his name, yet we "}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"have
          been unable to slay him in battle. "}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"There
          is now a bounty. "}],"text":""}'
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_DESTROYS
        - HIDE_PLACED_ON
        - HIDE_POTION_EFFECTS
        - HIDE_DYE
    stages:
      ordered:
        '1':
          npc-ids-to-kill:
          - 879
          npc-kill-amounts:
          - 1
          start-message: The bounty is simple. Southwest of here stands a great mountain
            infested with Goblins. At its rotten heart stands the Goblin King of Goblin
            Town. Slay him and return the axes he wields in disrespect of my ancestors.
            Good luck.
        '2':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: DIAMOND_AXE
            amount: 2
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              display-name: '{"extra":[{"bold":true,"italic":true,"underlined":true,"strikethrough":false,"obfuscated":false,"color":"green","text":"Great
                Blue Choppa"}],"text":""}'
              lore:
              - '{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"The
                Great Blue Choppas are a pair of"}],"text":""}'
              - '{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"beautiful
                diamond axes, taken from the"}],"text":""}'
              - '{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"corpse
                of a great Dawi lord many generations"}],"text":""}'
              - '{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"ago.
                The Goblin King of Goblin Town"}],"text":""}'
              - '{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"now
                wields them as his own weapons,"}],"text":""}'
              - '{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"taking
                many human and Dawi heads alike"}],"text":""}'
              - '{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"with
                the once-honorable weapons."}],"text":""}'
              enchants:
                VANISHING_CURSE: 1
              Unbreakable: true
          npc-delivery-ids:
          - 739
          delivery-messages:
          - I have not seen these axes since the battle of Granite Plains a generation
            ago...
          start-message: Excellent. Now quick, escape the town and return here with
            the axes. If you escape alive and bring me what is by right mine, I will
            hold the bounty fulfilled.
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: EMERALD
        amount: 32
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: IRON_CHESTPLATE
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: IRON_LEGGINGS
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: IRON_BOOTS
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: SHIELD
      exp: 150
    planner:
      cooldown: 86400
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```
