### ISSUE TITLE
Timer to fail quest quits quest after logging out or will not fail quest at all

### ISSUE THREAD

**Issue by joco3626** [PikaMug/Quests#1941]
### What is your Quests version / build number (do *not* say "latest")?

4.3.1

### Describe the problem and how to replicate it.

When a timer (via events) is added to a quest (time to fail quest) the quest either stays in the user's quest list past the time its set to fail after, or it will remove itself after the player logs out (quest is set to allow users to quit during the quest). This has happened with every quest I have used a timer on, these quests consist only of 1 stage. 

### Any console errors to share?

```shell
None
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom6:
    name: §bAcacia Woodcutter (WedThurs)
    ask-message: §bChop 100 acacia logs within the next 24h!
    finish-message: Great job! What are you gonna build with all that wood?
    npc-giver-id: 127
    stages:
      ordered:
        '1':
          break-block-names:
          - ACACIA_LOG
          break-block-amounts:
          - 100
          break-block-durability:
          - 0
          start-event: 24hTimer
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2586
        type: TRIPWIRE_HOOK
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Daily
            Quest "},{"bold":true,"italic":false,"color":"gold","text":"Key"}],"text":""}'
          lore:
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Daily
            Quest Key"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Use
            On The Quest Prize Chest!"}],"text":""}'
          enchants:
            LUCK: 1
          ItemFlags:
          - HIDE_ENCHANTS
          internal: H4sIAAAAAAAAAONiYOBgEHQuSqyqBBIlqcW6YIqBK7A0tbjEJTEzp5IBAErRIZwkAAAA
      money: 250
      quest-points: 1
    planner:
      start: 12:0:2022:0:0:0:EST
      end: 13:0:2022:23:59:59:EST
      repeat: 604800
      cooldown: 172800
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```
