### ISSUE TITLE
quests condition does not prevent custom and npc talk objectives

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1943]
### What is your Quests version / build number (do *not* say "latest")?

Quests-4.4.0#328

### Describe the problem and how to replicate it.

Quests stage condition will not prevent npc talk to objective and custom objective to be finished when condition is not met.

I have 

```
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Conversation NPC Objective
              count: 1
              data:
                ObjectiveNPC: '&7與 愛梅斯 對話#0                (右鍵NPC)'
                NPC: '9604'
                Close: 'true'
                msg1: '20;&a愛梅斯&7: &f動作蠻快的呢......'
                msg2: '60;&a愛梅斯&7: &f接下來就交給我轉換碎片吧。'
                msg3: NONE
                msg4: NONE
                msg5: NONE
                msg6: NONE
                msg7: NONE
                msg8: NONE
                msg9: NONE
                msg10: NONE
                end: '100'
          break-block-names:
          - SAND
          break-block-amounts:
          - 1
          break-block-durability:
          - 0
          npc-uuids-to-talk-to:
          - 454c13bd-93dc-4293-9324-09ad2bb26c47
          condition: SOUL_FRAGMENT10
```

With condition
```
  SOUL_FRAGMENT10:
    check-placeholder-id:
    - '%checkitem_namecontains:靈魂碎片,amt:10%'
    check-placeholder-value:
    - 'yes'

```
the condition is from papi module which check item name contains word "靈魂碎片" or not

When i does not met the condition, with break block objective, the condition blocked me to the next stage
but when i does not met the condition with NPC talk to or custom objective, the condition didn't block me to the next stage

which mean, if i does not met the condition , with NPC talk to stage and or custom objective, i can still go to next stage (the above quests have sand break objective , so that the quests is blocked to next stage with condition not met)

These objective should be tested one by one, i didn't test all but, so far i only used npc talk to and custom objective , and found this problem. And also found that break blocks behaving normally.

### Any console errors to share?

```shell
no error
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
https://paste.denizenscript.com/View/96142
```
