### ISSUE TITLE
Shift-clicking to craft multiple stacks of and item will only count as one stack toward quest objective progress

### ISSUE THREAD

**Issue by MarxminSD** [PikaMug/Quests#1944]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.4.0-b325

### Describe the problem and how to replicate it.

If I want to create a quest that requires a player to craft 512 or 8 stacks Oak Planks, I would need to set it up as so, since the limit is 64 when creating item crafting/smelting requirements in game:
(I used 8 stacks of oak logs to fulfill the one below when shift-clicking, as opposed to 2 stacks)
![image](https://user-images.githubusercontent.com/96161173/166117338-8245d5e4-3bc5-404c-91bd-5a305c64a2e5.png)
![image](https://user-images.githubusercontent.com/96161173/166117526-5291bb3b-7f32-403d-b95d-c9923e48f624.png)

When the player goes to craft the planks, if they use a stack of Oak Logs and shift-click planks, it will only fulfill one of the above objectives, although 256 were crafted. 

**You can set limits above 64 in the quests.yml and it functions normally, but I don't think it's common knowledge and found out via the Discord support 👍 

### Any console errors to share?

```shell
No console errors.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'3':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_PLANKS
            amount: 64
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_PLANKS
            amount: 64
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_PLANKS
            amount: 64
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_PLANKS
            amount: 64
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_PLANKS
            amount: 64
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_PLANKS
            amount: 64
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_PLANKS
            amount: 64
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_PLANKS
            amount: 64
          items-to-smelt:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: STONE
            amount: 64
          items-to-smelt:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: STONE
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: IRON_INGOT
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: IRON_INGOT
            amount: 64
```
