### ISSUE TITLE
Placing blocks does not negate from 'Blocks Broken'

### ISSUE THREAD

**Issue by therbz** [PikaMug/Quests#1951]
### What is your Quests version / build number (do *not* say "latest")?

4.4.0-b325

### Describe the problem and how to replicate it.

1- Set up a quest where the only stage is 'Break Blocks' of any type with an amount more than 1
2- Join the quest, break 1 of those blocks and your 'Blocks broken' counter will increase
3- If you place that block that you just broke and then break it again, the counter will still increase

This is problematic with Ancient Debris as players can find 1 Ancient Debris and keep breaking/placing that same block until they reach the end of the stage. This also works with any block that drops in block form (instead of an item), such as logs.

The intended behaviour should be that placing a block of a type will reduce the 'Blocks Broken' counter by 1 for that type of block (or have this as an option).

I'm not sure if this is a bug or a feature request, but I figured something like this would have already been thought of before.

### Any console errors to share?

```shell
N/A
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom1:
    name: Netherite Miner
    ask-message: Challenge objectives!
    finish-message: Well done!
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 2975
      type: ANCIENT_DEBRIS
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"text":"Netherite Miner"}],"text":""}'
        lore:
        - '{"extra":[{"text":"Challenge objectives!"}],"text":""}'
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_DESTROYS
        - HIDE_PLACED_ON
        - HIDE_POTION_EFFECTS
    stages:
      ordered:
        '1':
          break-block-names:
          - ANCIENT_DEBRIS
          break-block-amounts:
          - 16
          break-block-durability:
          - 0
    rewards:
      money: 1000
      exp: 2000
      commands:
      - cr give to <player> ultimate
      details-override:
      - $1000
      - 2000 EXP
      - x1 Ultimate Crate Key
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```
