### ISSUE TITLE
Objective Progress Duplication Bug

### ISSUE THREAD

**Issue by AccioAce** [PikaMug/Quests#1952]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.4.0-b328
Paper version: 1.18.2

### Describe the problem and how to replicate it.

It seems like when players use a **silktouch** pickaxe to mine all types of ores like emerald, diamond, etc as their quest, it duplicates. For example players needs to mine 0/1024 emerald ores and uses a silktouch pickaxe to mine 5 ores the quest system tells them they mined 7 or 9 sometime instead of 5 ores. **This issue occurs if you place the ore's down yourself and then mine them which causes the duplication.**

### Any console errors to share?

```shell
No console error
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Here's the quests.yml -> https://www.toptal.com/developers/hastebin/guzabipuna.yaml
```

**Comment by AlmightyPest** [comment]
A bit more detail^^

So when a player breaks an ore with a pickaxe that has silk touch and placed it back down it'll count it toward the quest. I.e. I have a quest where I need to break 10 emerald ores. I place down 3 emerald ores, break them with silk touch, place them back down, break them, I get 6 emerald ores broken for the quest. That's 6/10 emerald ores broken.

Players shouldn't be able to place down the ores for the quest to count them, I'm assuming. (This happens to all ores)

**Comment by PikaMug** [comment]
Does this still occur on https://ci.codemc.io/job/PikaMug/job/Quests/330/ ?

**Comment by AccioAce** [comment]
> Does this still occur on https://ci.codemc.io/job/PikaMug/job/Quests/330/ ?

Hello, nope it doesn't seem to work since another bug occur. I notice that when I tried to break the ore's with silk touch and non silk touch pickaxe none of the progress is being process through.

**Comment by PikaMug** [comment]
The quest link you provided is empty or expired. I tested this with the following quest on build 330 and it worked fine; blocks broken incremented by 1 every time using a new Diamond Pickaxe with Silk Touch.

```yaml
  custom36:
    name: silkTouch
    ask-message: Challenge objectives!
    finish-message: Well done!
    stages:
      ordered:
        '1':
          break-block-names:
          - IRON_ORE
          break-block-amounts:
          - 20
          break-block-durability:
          - 0
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```
