### ISSUE TITLE
Not all conditions need to be met in order to progress in a quest objective

### ISSUE THREAD

**Issue by MarxminSD** [PikaMug/Quests#1955]
### What is your Quests version / build number (do *not* say "latest")?

Version 4.4.0-b328

### Describe the problem and how to replicate it.

When settings conditions for a quest, only of one them need to be met in order for a player to progress in an objective. In this instance, my example condition looks like:

![image](https://user-images.githubusercontent.com/96161173/167333634-57d75a8f-04b0-4925-9935-ab41cd095e01.png)

For the quest in specific (quests.yml below) the player needs to kill 5 Zombies. When killing a zombie while wearing no chainmail armor, kills do not count. When wearing only one piece, the kills do count, although an identifier for each armor slot with its corresponding value has been listed.

/papi parse returns AIR when wearing nothing in the slot, and CHAINMAIL_HELMET, CHAINMAIL_CHESTPLATE, etc when wearing the corresponding piece of armor. The placeholder looks like it's working properly.

[Video here](https://streamable.com/ktol1c)

### Any console errors to share?

```shell
No Console errors.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom8:
    name: look
    ask-message: Challenge objectives!
    finish-message: Well done!
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 5
          condition: chainmailarmor
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```
