### ISSUE TITLE
Delivry messages are not sort when i give items

### ISSUE THREAD

**Issue by SkytraceXLSU** [PikaMug/Quests#1959]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.4.0-b332

### Describe the problem and how to replicate it.

when i give item that's say the wrong item like i give 3 coal of 64 
the message are "give 64 potato"

![image](https://user-images.githubusercontent.com/78903583/167966167-308ad810-f6f1-4901-91f6-0748a538eedf.png)
          - Donner 64 potato
          - Donner 64 coal

### Any console errors to share?

```shell
no error
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
# For non-English characters, this file MUST stay encoded in UTF-8
quests:
  custom1:
    name: Pére_Cornelius
    ask-message: Salutation petiot, Tu m'as l'air plutôt costaud et robuste, Que dirais-tu
      de m'aider ?!Mes forces et mes jambes s'efforcent de me quitter chaque jour
      un peu plus et je n'ai pas manger ce midi...
    finish-message: Je parlerais de tes accomplissements à mon neveu Siegfried, il
      risque de beaucoup apprécier aussi d'autant plus qu'il a autant besoin d'aide
      que moi. Si tu veux en savoir plus retrouve-le dans le sanctuaire dans la dimension
      END. Tu m'as été d'une grande utilitée et je tiens à te récompenser. Tient,
      il te servira plus qu'à moi !
    npc-giver-uuid: 668f260c-da94-4c2b-8ee5-78eac979a944
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: APPLE
            amount: 2
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: CAKE
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: WATER_BUCKET
          npc-delivery-uuids:
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          delivery-messages:
          - Donner 2 pommes
          - Donner 1 gateau
          - Donner 1 seau d'eau
          complete-message: Ahah ! Je savais que je pouvais compter sur toi, je ne
            vois plus très bien et ma vu me fait défaut
        '2':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: SPYGLASS
          npc-delivery-uuids:
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          delivery-messages:
          - Donner 1 longue-vue
          complete-message: Hélas, cette longue-vue est cassée. Je vais la fabriquer
            moi même, rien de mieux qu'une remise en pratique !
        '3':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: COPPER_INGOT
            amount: 2
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: AMETHYST_SHARD
          npc-delivery-uuids:
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          delivery-messages:
          - Donner 2 lingots de cuivre
          - Donner 1 fragment d'amethyste
          complete-message: Woww mais tu es très élégant. J'ai enfin retrouvé la vue
            de ma jeunesse, maintenant que c'est fait, nous allons pouvoir nous débarasser
            des rats qui infestent le village.
        '4':
          mobs-to-kill:
          - Silverfish
          mob-amounts:
          - 500
          complete-message: Incroyable, nous voilà enfin débarasser des maladies et
            de ces maudits voleurs de fromages !Pour éviter qu'ils nous envahissent
            de nouveaux, je vais préparer une potion d'empoissonnement.
        '5':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: WATER_BUCKET
            amount: 3
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: NETHER_WART
            amount: 1
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: SPIDER_EYE
            amount: 1
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: REDSTONE
            amount: 1
          npc-delivery-uuids:
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          delivery-messages:
          - Donner 3 seau d'eau
          - Donner 1 verrue du nether
          - Donner 1 oeil d'araignée
          - Donner 1 poudre de redstone
          complete-message: Super, avec ça ils ne reviendront pas ! Mon bateau se
            fait vieux comme son propriétaire, il aurait bien besoin d'une réparation
        '6':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_LOG
            amount: 512
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_PLANKS
            amount: 256
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: SPRUCE_SLAB
            amount: 192
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: GRAY_WOOL
            amount: 128
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: BLACK_WOOL
            amount: 128
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: DARK_OAK_LOG
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: SPRUCE_FENCE
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: DARK_OAK_DOOR
            amount: 1
          npc-delivery-uuids:
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          delivery-messages:
          - Merci !
          - Merci !
          - Merci !
          - Merci !
          - Merci !
          - Merci !
          - Merci !
          - Merci !
          complete-message: J'aimerais préparer mon dernier voyage, mes heures sont
            compter et je souhaite en profiter maintenant que tu l'as réparé ! Va
            donc me préparer mes provisions pour passer l'hiver en pleine mer.
        '7':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: POTATO
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: COAL
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: BOOKSHELF
            amount: 15
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: ENCHANTING_TABLE
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: ANVIL
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: FURNACE
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: NETHERITE_SWORD
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: COMPASS
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: CLOCK
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: FISHING_ROD
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: FLINT_AND_STEEL
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: BUCKET
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: JUKEBOX
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: BOWL
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_BOAT
          npc-delivery-uuids:
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          delivery-messages:
          - Donner 64 potato
          - Donner 64 coal
          - Donner 15 bibliothèques
          - Donner 1 table d'enchantement
          - Donner 1 anclume
          - Donner 1 épée en Netherite
          - Donner 1 boussole
          - Donner 1 montre
          - Donner 1 four
          - Donner 1 canne à pêche
          - Donner 1 briquet
          - Donner 1 seau
          - Donner 1 jukebox
          - Donner 1 bol
          - Donner 1 bateau en chêne
          complete-message: Tu es définitivement mon sauveur ! Je ne voudrais pas
            abuser de ta bonne volontée mais je suis trop vieux pour marcher jusqu'à
            mon bateau sans mon talisman.
        '8':
          locations-to-reach:
          - world 498.0 81.0 -3033.0
          reach-location-radii:
          - 2
          reach-location-names:
          - Coffre de Cornelius
          start-message: -Trouve mon bateau et ramène moi mon talisman.
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: EMERALD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":true,"color":"dark_red","text":"
            kkk"},{"bold":true,"italic":false,"obfuscated":false,"color":"dark_green","text":"
            "},{"bold":true,"italic":false,"underlined":true,"color":"dark_green","text":"Talisman
            du père Cornelius"},{"bold":false,"italic":false,"underlined":false,"obfuscated":true,"color":"dark_red","text":"
            kkk"}],"text":""}'
          lore:
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_blue","text":"☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼"}],"text":""}'
          - '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_red","text":"Ce
            talisman appartient à "},{"bold":true,"italic":false,"underlined":true,"color":"gold","text":"Cornelius"}],"text":""}'
          - '{"extra":[{"bold":true,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_red","text":"Ferez-vous
            "},{"bold":true,"italic":false,"underlined":true,"color":"aqua","text":"le
            choix"},{"bold":true,"italic":true,"underlined":false,"color":"dark_red","text":"
            de lui rendre?"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_blue","text":"☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼"}],"text":""}'
          attribute-modifiers:
            GENERIC_MAX_HEALTH:
            - ==: org.bukkit.attribute.AttributeModifier
              amount: 4.0
              name: generic.max_health
              slot: OFF_HAND
              uuid: 3f8e2c5b-408b-1910-3e34-6e6f4c4c98c8
              operation: 0
      commands:
      - trmenu open opentalismanquest <player>
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
  custom2:
    name: Pére_Cornelius_vol
    ask-message: -Ramène moi mon talisman.
    finish-message: Je parlerais de tes accomplissements à mon neveu Siegfried, il
      risque de beaucoup apprécier aussi d'autant plus qu'il a autant besoin d'aide
      que moi. Si tu veux en savoir plus retrouve-le dans le sanctuaire dans la dimension
      END. Tu m'as été d'une grande utilitée et je tiens à te récompenser. Tient,
      il te servira plus qu'à moi !
    stages:
      ordered:
        '1':
          npc-uuids-to-talk-to:
          - 668f260c-da94-4c2b-8ee5-78eac979a944
    rewards:
      commands:
      - saveditems get quest_casque_1 -t:<player>
  custom3:
    name: Pére_Cornelius_rendre
    ask-message: -Ramène moi mon talisman.
    finish-message: Je parlerais de tes accomplissements à mon neveu Siegfried, il
      risque de beaucoup apprécier aussi d'autant plus qu'il a autant besoin d'aide
      que moi. Si tu veux en savoir plus retrouve-le dans le sanctuaire dans la dimension
      END. Tu m'as été d'une grande utilitée et je tiens à te récompenser. Tient,
      il te servira plus qu'à moi !
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: EMERALD
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":true,"color":"dark_red","text":"
                kkk"},{"bold":true,"italic":false,"obfuscated":false,"color":"dark_green","text":"
                "},{"bold":true,"italic":false,"underlined":true,"color":"dark_green","text":"Talisman
                du père Cornelius"},{"bold":false,"italic":false,"underlined":false,"obfuscated":true,"color":"dark_red","text":"
                kkk"}],"text":""}'
              lore:
              - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_blue","text":"☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼"}],"text":""}'
              - '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_red","text":"Ce
                talisman appartient à "},{"bold":true,"italic":false,"underlined":true,"color":"gold","text":"Cornelius"}],"text":""}'
              - '{"extra":[{"bold":true,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_red","text":"Ferez-vous
                "},{"bold":true,"italic":false,"underlined":true,"color":"aqua","text":"le
                choix"},{"bold":true,"italic":true,"underlined":false,"color":"dark_red","text":"
                de lui rendre?"}],"text":""}'
              - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_blue","text":"☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼"}],"text":""}'
              attribute-modifiers:
                GENERIC_MAX_HEALTH:
                - ==: org.bukkit.attribute.AttributeModifier
                  amount: 4.0
                  name: generic.max_health
                  slot: OFF_HAND
                  uuid: 3f8e2c5b-408b-1910-3e34-6e6f4c4c98c8
                  operation: 0
          npc-delivery-uuids:
          - 668f260c-da94-4c2b-8ee5-78eac979a944
          delivery-messages:
          - Donner 1 Talisman
    rewards:
      commands:
      - saveditems get quest_casque_1 -t:<player>
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
  custom4:
    name: Siegfried_le_guerrier_desohonorer
    ask-message: Aieeeee... Que ça fait mal... Ce maudit dragon m'aura décidement
      mené la vie dûr... Ohh, navré, je ne t'avais pas remarqué ! Tu es sûrement l'aventurier
      qui a aidé mon oncle n'est ce pas ? Il m'a raconté tes louanges et m'en à fait
      ton éloge. Il t'en as sûrement déjà parlé, mais en effet j'aurais bien besoin
      d'un coup de main, je vais te raconter... J'ai tenter un combat mythique et
      préstigieux contre L'ENDER DRAGON pour affluer ma renommée et ainsi parler de
      moi à travers les différentes dimensions jusqu'à en devenir un sujet implaccable
      mais ça ne s'est pas passé comme prévu... Hélas, malgrè mon expérience et l'art
      du combat acquis par le passé, Je suis allé l'affronter sans tactiques et sans
      réfléchir et j'en reste maintenant en vain devant mon bras cassé. Il me faut
      maintenant m'en remettre à toi, ma carrière en dépend jeune aventurier, Veange
      moi ! Je vais t'entrainer pour que tu sois préparer à affronter l'enderdragon
      et tu en seras récompenser par mon plastron unique et mythique en échange, acclame
      ma victoire et fait mon éloge dans toutes les brasseries que tu verras.
    finish-message: Bien joué !
    npc-giver-uuid: 75ac1657-a439-453d-af08-187340fadc50
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Pig
          mob-amounts:
          - 500
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```
