### ISSUE TITLE
Quests and Citizens, NPC not giving quest

### ISSUE THREAD

**Issue by Andie10496** [PikaMug/Quests#1969]
### What is your Quests version / build number (do *not* say "latest")?

4.4.0-b325

### Describe the problem and how to replicate it.

I have made a quest and successfully assigned my citizen NPC to give the quest, the NPC has the logo above their head to give the quest, but when you click on the npc nothing happens. 

### Any console errors to share?

```shell
No console errors
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom2:
    name: §5Feed Me
    ask-message: Listen here, I have wanted cake for weeks. Get me a cake and we can
      be friends.
    finish-message: I love you.
    npc-giver-uuid: f6eda628-f556-4fa4-a604-9bc30a8dc37c
    stages:
      ordered:
        '1':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: CAKE
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: CAKE
          npc-delivery-uuids:
          - f6eda628-f556-4fa4-a604-9bc30a8dc37c
          delivery-messages:
          - Heck yeah!
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: STICK
        amount: 3
      quest-points: 1
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```
