### ISSUE TITLE
npc-uuids-to-talk-to does not allow players to talk when hand have item

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1973]
### What is your Quests version / build number (do *not* say "latest")?

[13:36:44 INFO]: Quests 4.4.3-b343
[13:36:44 INFO]: 建立者 ： Blackvein 接任者 ： PikaMug & contributors
[13:36:44 INFO]: https://github.com/PikaMug/Quests

### Describe the problem and how to replicate it.

i have
```
    stages:
      ordered:
        '1':
          npc-uuids-to-talk-to:
          - 454c13bd-93dc-4293-9324-09ad2bb26c47
```

if i have item in my hand, i cannot talk to the npc

### Any console errors to share?

```shell
no error
```
