### ISSUE TITLE
Blocks to break does not show

### ISSUE THREAD

**Issue by belphegorspn** [PikaMug/Quests#1974]
### What is your Quests version / build number (do *not* say "latest")?

The version used is 4.5.0

### Describe the problem and how to replicate it.

Update your quests to 4.5.0, restart your server, check your current quest (/quest) and the blocks to break won't show.
![image](https://user-images.githubusercontent.com/66054833/174512808-a2a6e5bc-57fb-4bb5-b360-e0c348789a9d.png)

### Any console errors to share?

```shell
There were no console errors at all. Not that I've seen. I can't check right now, I've downgraded the plugin.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
name: Fledgeling
    ask-message: Let this quest guide you to become stronger!
    finish-message: You have yet again proven yourself, adventurer.
    npc-giver-uuid: 78afe7a0-81b9-45a0-86bd-dc565fe789c0
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 2975
      type: GOLDEN_SWORD
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_purple","text":"Fledgeling"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"Let
          this quest guide you to become "}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"stronger!
          "}],"text":""}'
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_DESTROYS
        - HIDE_PLACED_ON
        - HIDE_POTION_EFFECTS
        - HIDE_DYE
    requirements:
      quests:
      - custom2
    stages:
      ordered:
        '1':
          break-block-names:
          - STONE
          - IRON_ORE
          - COAL_ORE
          - DEEPSLATE_GOLD_ORE
          - DEEPSLATE_DIAMOND_ORE
          break-block-amounts:
          - 320
          - 64
          - 64
          - 32
          - 10
          break-block-durability:
          - 0
          - 0
          - 0
          - 0
          - 0
          mobs-to-kill:
          - Zombie
          - Skeleton
          - Spider
          mob-amounts:
          - 5
          - 5
          - 5
          start-message: Let's go caving, adventurer!
          complete-message: The risk was all worth it, after all!
        '2':
          use-block-names:
          - FURNACE
          - CRAFTING_TABLE
          - CHEST
          use-block-amounts:
          - 10
          - 64
          - 64
          use-block-durability:
          - 0
          - 0
          - 0
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: IRON_HELMET
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: IRON_CHESTPLATE
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: IRON_LEGGINGS
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: IRON_BOOTS
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: IRON_SWORD
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: SHIELD
          items-to-smelt:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: IRON_INGOT
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: GOLD_INGOT
            amount: 32
          start-message: Gear up with an iron set!
          complete-message: Now you're protected from the darkness and the lurking
            hostile creatures.
        '3':
          mobs-to-kill:
          - Zombie
          - Skeleton
          - Spider
          - Creeper
          mob-amounts:
          - 150
          - 150
          - 150
          - 50
          start-message: The world has become darker recently...
          complete-message: We must become stronger!
        '4':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: WITHER_ROSE
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: RED_MUSHROOM
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: POPPY
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: BLUE_ORCHID
          npc-delivery-uuids:
          - 479d8e13-86f4-4c62-b6e5-f213b842457b
          - 2fce29a7-85a5-41db-b7fc-1947cb110213
          - cae88d5d-3cc1-4b04-91e1-9411badc7691
          - f2ef832c-ff69-4a83-a311-55d59f0259cd
          delivery-messages:
          - 'Hmm.. thanks! '
          - ' Reminds me of home. Thank you. '
          - ' This is beautiful. Thanks. '
          - ' For me? that''s very sweet of you'
          start-message: Meed the locals at /warp Market
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: GOLDEN_CARROT
        amount: 64
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: DIAMOND
        amount: 3
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: ENCHANTED_GOLDEN_APPLE
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: EXPERIENCE_BOTTLE
        amount: 32
      exp: 160
      commands:
      - broadcast Congratulations <player>! You have finished the &bFledgeling quest.
      - adjustbonusclaimblocks <player> 500
      - lp user <player> promote player
      permission-worlds: []
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```
