### ISSUE TITLE
Quests - Cooldowns not working

### ISSUE THREAD

**Issue by paleFinton** [PikaMug/Quests#1975]
### What is your Quests version / build number (do *not* say "latest")?

4.5.1 - b346

### Describe the problem and how to replicate it.

Whenever I accept a quest, I can complete it. There should be a 1 hour cooldown (or any cooldown), but the quest doesn't recognize there is a cooldown, it will just let you complete it, and take it again without waiting for the cooldown.

### Any console errors to share?

```shell
N/A.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
name: Baked Potatoes
    ask-message: Hey there! Would you please bake 64 potatoes and bring them back
      to me? I will reward you!
    finish-message: Thank you! Here is your reward!
    npc-giver-uuid: c4860ec3-e369-4f58-9e11-6909d7c16ddc
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3105
      type: POTATO
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_purple","text":"Baked
          Potatoes "},{"italic":false,"color":"green","text":"(Completed)"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"Hey
          there! Would you please bake 64 "}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"potatoes
          and bring them back to me? I "}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"will
          reward you! "}],"text":""}'
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_DESTROYS
        - HIDE_PLACED_ON
        - HIDE_POTION_EFFECTS
        - HIDE_DYE
    requirements:
      quest-points: 1
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3105
            type: BAKED_POTATO
            amount: 64
          npc-delivery-uuids:
          - c4860ec3-e369-4f58-9e11-6909d7c16ddc
          delivery-messages:
          - Thank you!
          start-message: Bring 64 Baked Potatoes back to Cora for a reward
          complete-message: Thank you for the Potatoes!
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: IRON_BLOCK
      - ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: EXPERIENCE_BOTTLE
        amount: 32
      - ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: GOLDEN_APPLE
        amount: 3
      money: 250
      quest-points: 2
    planner:
      cooldown: 3600
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
