### ISSUE TITLE
Set ask message not working as intended

### ISSUE THREAD

**Issue by PancakeCatsss** [PikaMug/Quests#1976]
### What is your Quests version / build number (do *not* say "latest")?

[Imgur](https://i.imgur.com/bWCmZ5k.png)

### Describe the problem and how to replicate it.

Setting the ask message does not display it on the item lore when linked to an NPC, still shows "Challenge objectives!"

[Imgur](https://i.imgur.com/YLuGxZv.png)

[Imgur](https://i.imgur.com/63MEwHz.png)

### Any console errors to share?

```shell
No console errors
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
The quest it's self, does it with all quests.


  custom11:
    name: Shopping-Cart
    ask-message: test
    finish-message: Well done!
    npc-giver-uuid: bb984672-1dd7-4157-80cf-483ff2042eb7
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 2975
      type: IRON_BLOCK
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_purple","text":"Shopping-Cart"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"Challenge
          objectives! "}],"text":""}'
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_DESTROYS
        - HIDE_PLACED_ON
        - HIDE_POTION_EFFECTS
        - HIDE_DYE
    requirements:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: IRON_BLOCK
        amount: 768
      remove-items:
      - false
    stages:
      ordered:
        '1':
          locations-to-reach:
          - muchpancakes 64.0 89.0 421.0
          reach-location-radii:
          - 10
          - 5
          reach-location-names:
          - John
          - 'Location #2'
          start-message: '&7[&a&lJohn&7] &3Thanks! I''ll need 12 stacks of Iron blocks
            to make these shopping carts, bring them to me and I''ll make you one
            too!'
          complete-message: '&7[&a&lJohn&7] &3You again! I found more Iron and have
            made an extra cart just for you!'
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: PAPER
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Shopping
            Cart"}],"text":""}'
          lore:
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"light_purple","text":""}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Fuel"},{"italic":false,"color":"white","text":":"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"-
            "},{"italic":false,"color":"green","text":"Potato"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"-
            "},{"italic":false,"color":"green","text":"Carrot"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"-
            "},{"italic":false,"color":"green","text":"Wheat"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"-
            "},{"italic":false,"color":"green","text":"Banana"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"-
            "},{"italic":false,"color":"green","text":"Pear"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"-
            "},{"italic":false,"color":"green","text":"Rice"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"-
            "},{"italic":false,"color":"green","text":"Garlic"}],"text":""}'
          custom-model-data: 10135
          internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGHgLc7ILyjIzEuPT04sKuFg4MxLzE0tLkhMTkVWy8AAAGG82UU+AAAA
      money: 1000
      quest-points: 25
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
```
