### ISSUE TITLE
Wrong order of items in GUI

### ISSUE THREAD

**Issue by SadCarrot12** [PikaMug/Quests#1979]
### What is your Quests version / build number (do *not* say "latest")?

4.5.0

### Describe the problem and how to replicate it.

The problem is, in the GUI i have items like this

Log III, Axe, Log I, Log II

Where it should be 

Axe, Log I, Log II, Log III

### Any console errors to share?

```shell
None
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom6:
    name: Złamana siekiera
    ask-message: Moja siekiera się złamała czy możesz przynieść mi nową?
    finish-message: Nareszcie mogę wrócić do pracy
    npc-giver-uuid: d9215340-cab6-44bc-bc90-18157afc1f51
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 2975
      type: IRON_AXE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_purple","text":"Złamana
          siekiera"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"Moja
          siekiera się złamała czy możesz "}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"przynieść
          mi nową? "}],"text":""}'
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_DESTROYS
        - HIDE_PLACED_ON
        - HIDE_POTION_EFFECTS
        - HIDE_DYE
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: IRON_AXE
          npc-delivery-uuids:
          - d9215340-cab6-44bc-bc90-18157afc1f51
          delivery-messages:
          - Dziękuję Ci. Jeszcze tylko <amount>!
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: SLIME_BALL
        amount: 15
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"Monety"}],"text":""}'
          enchants:
            ARROW_DAMAGE: 5
          internal: H4sIAAAAAAAA/+NiYOBg4PaNDPHwdI4PiQxwZWBJzs/MYwAAJ/xf+RgAAAA=
      exp: 50
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
  custom7:
    name: Drwal I
    ask-message: Zbierz 64 Dębowych kłód
    finish-message: Dobra robota!
    npc-giver-uuid: d9215340-cab6-44bc-bc90-18157afc1f51
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 2975
      type: OAK_LOG
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_purple","text":"Drwal
          I"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"Zbierz
          64 Dębowych kłód "}],"text":""}'
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_DESTROYS
        - HIDE_PLACED_ON
        - HIDE_POTION_EFFECTS
        - HIDE_DYE
    requirements:
      quests:
      - custom6
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_LOG
            amount: 64
          npc-delivery-uuids:
          - d9215340-cab6-44bc-bc90-18157afc1f51
          delivery-messages:
          - Dziękuję Ci. Jeszcze tylko <amount>!
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: SLIME_BALL
        amount: 10
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"Monety"}],"text":""}'
          enchants:
            ARROW_DAMAGE: 5
          internal: H4sIAAAAAAAA/+NiYOBg4PaNDPHwdI4PiQxwZWBJzs/MYwAAJ/xf+RgAAAA=
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
  custom9:
    name: Drwal II
    ask-message: Przynieś 64 dębowych i brzozowych kłód
    finish-message: Dobra robota!
    npc-giver-uuid: d9215340-cab6-44bc-bc90-18157afc1f51
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 2975
      type: OAK_LOG
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Drwal
          II"}],"text":""}'
    requirements:
      quests:
      - custom7
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_LOG
            amount: 64
          npc-delivery-uuids:
          - d9215340-cab6-44bc-bc90-18157afc1f51
          delivery-messages:
          - Dziękuję Ci. Jeszcze tylko <amount>!
        '2':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: BIRCH_LOG
            amount: 64
          npc-delivery-uuids:
          - d9215340-cab6-44bc-bc90-18157afc1f51
          delivery-messages:
          - Dziękuję Ci. Jeszcze tylko <amount>!
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: SLIME_BALL
        amount: 20
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"Monety"}],"text":""}'
          enchants:
            ARROW_DAMAGE: 5
          internal: H4sIAAAAAAAA/+NiYOBg4PaNDPHwdI4PiQxwZWBJzs/MYwAAJ/xf+RgAAAA=
      exp: 50
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
  custom11:
    name: Drwal III
    ask-message: Przynieś mi 3 stacki dębowego drewna.
    finish-message: Dobra robota!
    npc-giver-uuid: d9215340-cab6-44bc-bc90-18157afc1f51
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 2975
      type: OAK_LOG
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_purple","text":"Drwal
          III"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"Przynieś
          mi 3 stacki dębowego drewna. "}],"text":""}'
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_DESTROYS
        - HIDE_PLACED_ON
        - HIDE_POTION_EFFECTS
        - HIDE_DYE
    requirements:
      quests:
      - custom9
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_LOG
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_LOG
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: OAK_LOG
            amount: 64
          npc-delivery-uuids:
          - d9215340-cab6-44bc-bc90-18157afc1f51
          - d9215340-cab6-44bc-bc90-18157afc1f51
          - d9215340-cab6-44bc-bc90-18157afc1f51
          delivery-messages:
          - Jeszcze trochę.
          - Jeszcze trochę.
          - Jeszcze trochę.
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
