### ISSUE TITLE
Questgui not accept quest in npc in language polish QUESTS

### ISSUE THREAD

**Issue by steveminecraft2** [PikaMug/Quests#1992]
### What is your Quests version / build number (do *not* say "latest")?

Quests version 4.5.1-b348
QuestsGUI version 0.46

### Describe the problem and how to replicate it.

Change in the settings of the quests plugin to the Polish language pl-PL. Make a quest with delivering an item to an npc, set the gui to the same npc and add a display item in the gui. When you open the gui to start the quest, you click on the item but nothing happens, the item returns to its place in the gui and you can't start the quest. But if you change the language back to en-US, when you click on the item, the quest is accepted normally.

### Any console errors to share?

```shell
no
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
# For non-English characters, this file MUST stay encoded in UTF-8
quests:
  test:
    name: test
    ask-message: Hey, test?
    finish-message: test!
    npc-giver-uuid: f1261e6d-9470-4c54-953a-e3b768f7e046
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3105
      type: FISHING_ROD
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3105
            type: COOKED_BEEF
            amount: 32
          npc-delivery-uuids:
          - f1261e6d-9470-4c54-953a-e3b768f7e046
          delivery-messages:
          - test!
          start-message: test!
          complete-message: test!
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
