### ISSUE TITLE
Daily Quest error

### ISSUE THREAD

**Issue by sienedo** [PikaMug/Quests#1993]
### Where else have you looked for answers to this question?

So i tried to set it like this
```yml
name: Daily Mobs 2
    ask-message: Challenge objectives!
    finish-message: Well done!
    npc-giver-uuid: 9d1c57ea-c6fd-4dd9-b284-414837b7ce92
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3105
      type: IRON_SWORD
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_purple","text":"Daily
          Mobs 2 "},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"(Completed)"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"Challenge
          objectives! "}],"text":""}'
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_DESTROYS
        - HIDE_PLACED_ON
        - HIDE_POTION_EFFECTS
        - HIDE_DYE
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Skeleton
          mob-amounts:
          - 5
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: EXPERIENCE_BOTTLE
        amount: 5
    planner:
      start: 28:6:2022:12:0:0:Asia/Jakarta
      end: 1:11:2022:11:43:40:Asia/Jakarta
      repeat: 86400
      cooldown: 32400
      override: true
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```

### Share your question with as much detail as possible.

but I kinda confused if i set planner : override true 
then i able to retake the quest as many as possible somehow, regardsless cooldown time. even if repeat should be only run after 24 hours. 

i'm not sure where i did wrong here, please help me in this if there's anything that i missed.

thank you
