### ISSUE TITLE
1.18.2 EXP  pre-condition doesnt work

### ISSUE THREAD

**Issue by WhosthisJulian** [PikaMug/Quests#1997]
### What is your Quests version / build number (do *not* say "latest")?

4.5.2

### Describe the problem and how to replicate it.

1.18.2 EXP  pre-condition doesnt work

### Any console errors to share?

```shell
no
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom13:
    name: Olaf Krause
    ask-message: Ziele herausfordern!
    finish-message: Gut gemacht!
    npc-giver-uuid: 2cfb1f3c-e4fd-4929-8a1d-33151181391b
    requirements:
      exp: 72

...
```
