### ISSUE TITLE
Quest stage autocompleting after logging off and on.

### ISSUE THREAD

**Issue by falconer02** [PikaMug/Quests#2008]
### What is your Quests version / build number (do *not* say "latest")?

4.5.3-b359
Module - QuestKillMythic-1.0

### Describe the problem and how to replicate it.

Hello! First off: great work with the plugin. Having a ton of fun with it. Keep up the great work with it!

The issue is when a player gets to the "Kill Mythic Objective" stage (kill a custom mythic mob boss), they can simply log out and back on, and that stage will autocomplete. Any idea what's going on? I checked the closed tickets and didn't see any parallel problems like I have here.

### Any console errors to share?

```shell
No console errors
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Here's an example of the stage of a quest:
        '2':
          custom-objectives:
            custom1:
              name: Kill Mythic Objective
              count: 1
              data:
                Progress Message: 'Kill Shalra: %count%'
                MythicMob: 0ShalraPhaseII0
                MythicLevel: '0'
          delay: 3
          complete-message: '&4Shalra &2destroyed!!!'
    rewards:
      exp: 150
```
