### ISSUE TITLE
API for Plan doesn`t responding

### ISSUE THREAD

**Issue by pavl21** [PikaMug/Quests#2016]
### What is your Quests version / build number (do *not* say "latest")?

4.5.3-b359

### Describe the problem and how to replicate it.

![image](https://user-images.githubusercontent.com/36771750/189113240-400b2ce5-ff10-4d9f-9038-27452c7bb6f5.png)

No values

### Any console errors to share?

```shell
No
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom3:
    name: Frei von Zombies!
    ask-message: Töte 20 Zombies
    finish-message: Gut gemacht!
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - zombie
          mob-amounts:
          - 20
    rewards:
      money: 50
```
