### ISSUE TITLE
quests condition does not prevent password-phrases

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#2022]
### What is your Quests version / build number (do *not* say "latest")?

Quests-4.6.0#361

### Describe the problem and how to replicate it.

i have
quest stage
```
        '13':
          password-displays:
          - 等待故事對話完成
          password-phrases:
          - aengkojwengoiu
          condition: nrpg_tutorial_castle13-upgrade
          objective-override:
          - 擊殺怪物獲取10個靈魂碎片，空手右鍵給予愛梅斯
          start-event: nrpg_tutorial_castle1-8
```
condition
```
  nrpg_tutorial_castle13-upgrade:
    check-placeholder-id:
    - '%checkitem_namecontains:+1&8),lorecontains:NRPG%'
    check-placeholder-value:
    - 'yes'
```

when the condition placeholder value is no, the quest stage finish by itself , condition does not stop the stage to start until condition was met.

### Any console errors to share?

```shell
no error
```
