### ISSUE TITLE
Quests Timer & Losing Quest Progress

### ISSUE THREAD

**Issue by joco3626** [PikaMug/Quests#2027]
### What is your Quests version / build number (do *not* say "latest")?

4.6.0-b361

### Describe the problem and how to replicate it.

Quests with a timer will be removed from a player's quest journal if a player logs out, the timers on the quests are 24h and 7 days long. Quests without timers have no issue staying in a player's quest journal.

### Any console errors to share?

```shell
n/a
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom97:
    name: §eStone Breaker (Weekly)
    ask-message: §bBreak 500 stone within 7 days!
    finish-message: Well done!
    npc-giver-id: 135
    stages:
      ordered:
        '1':
          break-block-names:
          - STONE
          break-block-amounts:
          - 500
          break-block-durability:
          - 0
          start-event: 1WeekTimer
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2586
        type: TRIPWIRE_HOOK
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Weekly
            Quest "},{"bold":true,"italic":false,"color":"gold","text":"Key"}],"text":""}'
          lore:
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Weekly
            Quest Key"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Use
            On The Quest Prize Chest!"}],"text":""}'
          enchants:
            LUCK: 1
          ItemFlags:
          - HIDE_ENCHANTS
          internal: H4sIAAAAAAAAAONiYOBgEHQuSqyqBBIlqcW6YIqBO7A0tbgkPDU1O6eSAQCODZHoJQAAAA==
      money: 600
      quest-points: 5
    planner:
      start: 9:0:2022:0:0:0:EST
      end: 15:0:2022:23:59:59:EST
      repeat: 1209600
      cooldown: 604800
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false


  1WeekTimer:
    timer: 604800


  custom87:
    name: §dWheat Farming (FriSatSun)
    ask-message: §bHarvest 1000 wheat within the next 24h!
    finish-message: You're going to have so many haybales!
    npc-giver-id: 5
    stages:
      ordered:
        '1':
          break-block-names:
          - WHEAT
          break-block-amounts:
          - 1000
          break-block-durability:
          - 0
          start-event: 24hTimer
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2586
        type: TRIPWIRE_HOOK
        amount: 2
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Daily
            Quest "},{"bold":true,"italic":false,"color":"gold","text":"Key"}],"text":""}'
          lore:
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Daily
            Quest Key"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Use
            On The Quest Prize Chest!"}],"text":""}'
          enchants:
            LUCK: 1
          ItemFlags:
          - HIDE_ENCHANTS
          internal: H4sIAAAAAAAAAONiYOBgEHQuSqyqBBIlqcW6YIqBK7A0tbjEJTEzp5IBAErRIZwkAAAA
      money: 800
      quest-points: 8
    planner:
      start: 14:0:2022:0:0:0:EST
      end: 16:0:2022:23:59:59:EST
      repeat: 604800
      cooldown: 172800
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false


24hTimer:
    clear-inventory: false
    fail-quest: false
    timer: 86400
```
