### ISSUE TITLE
Progression Bug

### ISSUE THREAD

**Issue by Superfudge247** [PikaMug/Quests#2029]
### What is your Quests version / build number (do *not* say "latest")?

Quests-4.5.1.jar
Spigot Latest 1.19.2 #271

### Describe the problem and how to replicate it.

I have a quest on my server for farming "Melons" it works in this order

Stage 1
Break 64 Melon Blocks

Stage 2
Deliver 64 Melon Blocks to NPC "ID 56"
Deliver 64 Melon Slices to NPC "ID 56"

However when I log off the server and log back on it completes Stage 2 even if I haven't delivered a single items.
This means once the player is on stage 2 if they quit and rejoin they affectively can skil stage 2 and complete the quest

I cannot yet confirm if this is happening to other quests but I will be sure to keep you updated if I find its a trend with the "Delivery"

I will upload an example of the quest that I have located that is producing the bugs above

### Any console errors to share?

```shell
18.11 17:36:34 [Server] ERROR Could not pass event PlayerJoinEvent to ExcellentCrates v4.0.6
18.11 17:36:34 [Server] INFO java.lang.IllegalStateException: no implementation set
18.11 17:36:34 [Server] INFO at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:79) ~[Citizens.jar:?]
18.11 17:36:34 [Server] INFO at net.citizensnpcs.api.CitizensAPI.getNPCRegistry(CitizensAPI.java:115) ~[Citizens.jar:?]
18.11 17:36:34 [Server] INFO at su.nexmedia.engine.hooks.Hooks.isCitizensNPC(Hooks.java:82) ~[NexEngine.jar:?]
18.11 17:36:34 [Server] INFO at su.nexmedia.engine.api.data.AbstractUserManager.getUserData(AbstractUserManager.java:53) ~[NexEngine.jar:?]
18.11 17:36:34 [Server] INFO at su.nightexpress.excellentcrates.key.KeyManager.giveKeysOnHold(KeyManager.java:172) ~[ExcellentCrates-4.0.6.jar:?]
18.11 17:36:34 [Server] INFO at su.nightexpress.excellentcrates.key.KeyListener.onUserLoad(KeyListener.java:30) ~[ExcellentCrates-4.0.6.jar:?]
18.11 17:36:34 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor534.execute(Unknown Source) ~[?:?]
18.11 17:36:34 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
18.11 17:36:34 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-271]
18.11 17:36:34 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
18.11 17:36:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
18.11 17:36:34 [Server] INFO at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:372) ~[paper-1.19.2.jar:git-Paper-271]
18.11 17:36:34 [Server] INFO at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$0(PlayerList.java:309) ~[paper-1.19.2.jar:git-Paper-271]
18.11 17:36:34 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-271]
18.11 17:36:34 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
18.11 17:36:34 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
18.11 17:36:34 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-271]
18.11 17:36:34 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-271]
18.11 17:36:34 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
18.11 17:36:34 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-271]
18.11 17:36:34 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-271]
18.11 17:36:34 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
18.11 17:36:34 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-271]
18.11 17:36:34 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-271]
18.11 17:36:34 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-271]
18.11 17:36:34 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom3:
    name: '&eFarming Quest 3'
    ask-message: §6Grow some fresh Melons for Henry!
    finish-message: Farming Quest 3 - [COMPLETED]
    npc-giver-id: 25
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3120
      type: MELON_SLICE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"Farming
          Quest 3"}],"text":""}'
    requirements:
      quests:
      - custom2
    stages:
      ordered:
        '1':
          break-block-names:
          - MELON
          break-block-amounts:
          - 64
          break-block-durability:
          - 0
          delay: 5
          start-message: '&a[Henry] &fYou did good last time we spoke I would like
            to see your skills at growing &d"Melons" &fyou know the drill.'
        '2':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3120
            type: MELON
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3120
            type: MELON_SLICE
            amount: 64
          npc-delivery-ids:
          - 25
          - 25
          delivery-messages:
          - '&a[Henry] &fYou need 64 &d"Melons" &fin total however, these will do
            for now.'
          - '&a[Henry] &fYou need 64 &d"Melons Slices" &fin total however, these will
            do for now.'
          delay: 5
          complete-message: '&a[Henry] &fYou produced some good quality &d"Melons"
            &ffor a beginner farmer, these are so very juicy!.'
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: LAPIS_LAZULI
        amount: 64
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: DIAMOND_HOE
      money: 500
      quest-points: 3
      exp: 100
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```
