### ISSUE TITLE
Quests can be taken again and again

### ISSUE THREAD

**Issue by TheLaoming** [PikaMug/Quests#2031]
### What is your Quests version / build number (do *not* say "latest")?

**Quests version:** 4.5.1-b348 but tested with all versions above up to 4.6.0.
**Server version:** 1.18.2 Paper-388

### Describe the problem and how to replicate it.

**Issue 1:** So I'm mostly using NPC's for quests and everything is okay, but I decided to use Block as my "NPC" for one very specific quest. The problem is in a moment you want to take your quest. You can take the same Quest again and again, infinitely. It happens only when you use a block. Here's the proof:  [https://imgur.com/a/79uKeZb](https://imgur.com/a/79uKeZb)

Thanks for the answer or possible fix.

### Any console errors to share?

```shell
Nothing at all
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Sure, here:

custom97:
    name: Podzemní Svatyně
    ask-message: Chceš očistit tuto podzemní svatyni?
    finish-message: Svatyně byla očistěna
    block-start: RPGMAIN 188.0 -5.0 85.0
    requirements:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: HONEY_BOTTLE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#C0B9C8","text":"Vernenova
            Svěcená voda"}],"text":""}'
          lore:
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#BD78CF","text":"Quest
            item"}],"text":""}'
          - '{"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Tuto
            svěcenou vodu lze použít pro"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"očištění
            Gelderenských svatyň."}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"◄--------------------------------►"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"["},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#BF3B35","text":"Vedlejší
            úkol"},{"italic":false,"color":"gray","text":"]"}],"text":""}'
          custom-model-data: 13
          attribute-modifiers:
            GENERIC_ATTACK_SPEED:
            - ==: org.bukkit.attribute.AttributeModifier
              amount: 0.0
              name: mmoitemsDecoy
              uuid: 87851e28-af12-43f6-898e-c62bde6bd0ec
              operation: 0
          ItemFlags:
          - HIDE_ATTRIBUTES
          internal: H4sIAAAAAAAA/9VSv0scQRR+xmYRlKgEIQRcpkilEpCQ08pxd6IL+0NvJgfHcgzn3Yg/LreyN3vEiJ2FjW0srK6aysJW0GL27n9I7V+ScQ8vhhTWDsPjMd8333vv400AWPAuCCKPkYBytxriwHO4H5UJ/I7Rx4ZWP7Ta0aqp1RetSlqZl93tTHSkvS/Fd7SAzDUYy2Rid7r9q4ZoJ5ndTZqZ3fop7KMkG9zn19I+SpMhM+lf7A96sn/Vzq/tDdFqilS0O4f5XWPPCNTl8eB8qWCWHi7PFl84D79uh6px0ei6Vl+1Wi4SEz9XRLMlDgY9Uym/PUxahlhDNQtmRhM/Rs6qWwSsADNS9rBvwdt/Yc+FWVohDgkxr0SuCaQcknAMPvw1zqN43SfcC40GdpgXhWMWTI5wYyuBxaJHR6tPRYMrRV6qiLRtPOvWbTq0L+892le3YGqTsnKVk9DZxCGjsHaCqKxLtIqenszs0QaVSXqMVuMTNCr3hPP8piNT8yGuodPa6Ti8H1Gcb5RFAQ8il/jcxQwDwKQF0/9pwJvYODb3fNQtH1eJO7Rt/oUNee5CsVY38WvbF/gD3bBBDCYDAAA=
      remove-items:
      - false
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill Mythic Objective
              count: 3
              data:
                Progress Message: Zabito %count% Gobliní kostliovec
                MythicMob: goblin_kostlivec2
                MythicLevel: '0'
          start-event: Podzemní svatyně kostlivci
          finish-event: Podzemní svatyně očista
    rewards:
      commands:
      - si give q_innos_slza 1 <player> true
      details-override:
      - Získal jis Innosovu slzu
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
