### ISSUE TITLE
[Bug report] Abuse of craft blocking (e.setCancelled(true);)

### ISSUE THREAD

**Issue by moda84** [PikaMug/Quests#2037]
### What is your Quests version / build number (do *not* say "latest")?

4.6.1

### Describe the problem and how to replicate it.

Hi!
Quests ignore blocking craft from other plugins.
Just repeating click on result slot in crafttable and Quests accepted craft!
![image](https://user-images.githubusercontent.com/44532692/204556033-b11cfd86-c8c2-4788-ab78-a28c8de3b042.png)

### Any console errors to share?

```shell
Nothing
```

### If applicable, can you provide an example quest from quests.yml?
```yaml
custom7:
    name: Охотник (Проверка навыка II)
    ask-message: Итак! Лук есть, а есть ли навыки в изготовлении костной муки? Сделай
      её и принеси мне.
    finish-message: Вроде хорошо перемолол, молодец.
    npc-giver-uuid: 55a990ef-181f-409b-8ffc-e173858a32ab
    requirements:
      quests:
      - custom6
    stages:
      ordered:
        '1':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 3120
            type: BONE_MEAL
            amount: 24
          npc-uuids-to-talk-to:
          - 55a990ef-181f-409b-8ffc-e173858a32ab
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: EXPERIENCE_BOTTLE
        amount: 7
      money: 70
```
