### ISSUE TITLE
Party Duplicate

### ISSUE THREAD

**Issue by MrJuju0319** [PikaMug/Quests#2040]
### What is your Quests version / build number (do *not* say "latest")?

 Quests 4.6.1-b373
 Parties 3.2.6 (Bukkit) - Developed by AlessioDP

### Describe the problem and how to replicate it.

hello, I have a little problem, when I do quests with multiplayer and the 'party' plugin, the objectives are duplicated, whereas I would like them to be added (I mine 1 block, all the others are also to 1 block) except that currently when I mine 1 block it goes to 2 or 3 depending on the number in the 'party'.

Example: I'm in 'party' with 10 players when I mine 1 block the objective goes to 10 and not 1.

Do you have a solution? https://www.spigotmc.org/resources/quests.3711/ and https://www.spigotmc.org/resources/parties-an-advanced-parties-manager.3709/
ps: i'm french

### Any console errors to share?

```shell
No erreur
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
default2:
    name: Mob Hunter
    ask-message: §eKill an assortment of Mobs.
    finish-message: §eExcellent. Here is a §dDiamond Sword§e.
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Pig
          mob-amounts:
          - 3
          finish-event: NiceFinish
          death-event: DeathFail
        '2':
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 2
          finish-event: NiceFinish
          death-event: DeathFail
        '3':
          mobs-to-kill:
          - Skeleton
          mob-amounts:
          - 1
          death-event: DeathFail
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: DIAMOND_SWORD
      quest-points: 1
      exp: 100
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: true
      ignore-block-replace: true
```
