### ISSUE TITLE
Placeholder API doesn't work with ask message

### ISSUE THREAD

**Issue by CorruptCreeper** [PikaMug/Quests#2042]
### What is your Quests version / build number (do *not* say "latest")?

Quests Build [# 375]

### Describe the problem and how to replicate it.

Using the lastest version of Citizens, Quests, and Placeholder API with correct modules on a paper server. I am unable to use placeholders from placeholder api such as %player_name%, or %player_displayname% in the ask-message for a quest
below is an example
![image](https://user-images.githubusercontent.com/120017792/206155662-d216e0d5-d1bd-44bc-858b-01cf8fa331ae.png)
These are the logs
[log.txt](https://github.com/PikaMug/Quests/files/10175157/log.txt)

### Any console errors to share?

```shell
There is no console errors other than these unrelated PlaceholderAPI Warnings
[23:31:34 WARN]: [PlaceholderAPI] Cannot load expansion playerstats due to a missing plugin: PlayerStats
[23:31:34 WARN]: [PlaceholderAPI] Cannot load expansion playertime due to a missing plugin: PlayerTime
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
default2:
    name: Mob Hunter
    ask-message: <yellow>%player_name%, Mine <pink>2<yellow> blocks of <pink>Iron Ore<yellow>.
    finish-message: §eExcellent. Here is a §dDiamond Sword§e.
    npc-giver-uuid: 645d5c3d-e0c4-4bdc-8b0d-85c0adcabc11
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Pig
          mob-amounts:
          - 3
          finish-event: NiceFinish
          death-event: DeathFail
        '2':
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 2
          finish-event: NiceFinish
          death-event: DeathFail
        '3':
          mobs-to-kill:
          - Skeleton
          mob-amounts:
          - 1
          death-event: DeathFail
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: DIAMOND_SWORD
      quest-points: 1
      exp: 100
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
