### ISSUE TITLE
Set GUI Item Display

### ISSUE THREAD

**Issue by Drizzt11** [PikaMug/Quests#2048]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.6.1-b373
QuestsGUI 0.51

### Describe the problem and how to replicate it.

I dont know what is causing it but I was able to create 3 quests no problem until I reached a spot where I cannot set the GUI Item Display.  I select Diamond Sword as my GUI Item and when I hit done and then I got to look at the GUI Item Display in the settings it says "None Set" like it didnt even set.

### Any console errors to share?

```shell
No Console Errors
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
quests:
  custom1:
    name: Armory - Blaze (Nether)
    ask-message: 'Kill 5 Blazes. Then report to Knight Jim. Rewards: $750 2QP 250XP'
    finish-message: Quest Completed!
    npc-giver-uuid: c7c5e3a3-ae80-4d51-a170-eeb2a72a87ab
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3218
      type: DIAMOND_SWORD
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Blaze
          mob-amounts:
          - 5
          start-message: Kill 5 Blazes.
          complete-message: Quest Objective Completed!
        '2':
          npc-uuids-to-talk-to:
          - c7c5e3a3-ae80-4d51-a170-eeb2a72a87ab
          start-message: Speak to Knight Jim.
          complete-message: Quest Objective Completed!
    rewards:
      money: 750
      quest-points: 2
      exp: 250
    planner:
      cooldown: 86400
```
