### ISSUE TITLE
Display-name error

### ISSUE THREAD

**Issue by sciqni** [PikaMug/Quests#2049]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.6.1
QuestsGUI 0.51

### Describe the problem and how to replicate it.

Whit the plugin questsGUI when u do /quests list the display name it's wrong.
for example
quests:
  custom1:
    name: Consumatore1
    ask-message: Challenge objectives!
    finish-message: Well done!
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      type: GOLDEN_APPLE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §eConsumatore §l#1
        
   The name of the item in /quests list that will come out is Consumatore1 and not §eConsumatore §l#1 (the display-name:)

### Any console errors to share?

```shell
No
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
quests:
  custom1:
    name: Consumatore1
    ask-message: Challenge objectives!
    finish-message: Well done!
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      type: GOLDEN_APPLE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §eConsumatore §l#1
```
