### ISSUE TITLE
Huge lags caused by Quests

### ISSUE THREAD

**Issue by LoganScho** [PikaMug/Quests#2064]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.6.0-b361

### Describe the problem and how to replicate it.

Sometimes I have big lag on my server during a few minutes. When I look into a spigot timings report, I can see a some info that I don't see usually. It is related to Quests but I don't know what it is or what cause it.
![image](https://user-images.githubusercontent.com/47453840/214156203-ab082212-e6b9-45fa-8ff7-9f757cbacb32.png)

In the example quest, I've put the data of the quest I was personally doing when the lags happened but I'm not alone on the server

### Any console errors to share?

```shell
There is no console error, just lags
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom3:
    name: §e§lHache Habile
    ask-message: §6§lVous êtes prêt à conquérir le coeur des habitants de Eyrar ?
    finish-message: §6§lVoici pour toi, la hâche de mon grand-père. Je pense qu'elle
      sera entre de bonnes mains !
    npc-giver-uuid: 595a11ac-8942-4c4f-8397-3bd865e6f004
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3120
      type: STONE_AXE
    requirements:
      quests:
      - custom2
    stages:
      ordered:
        '1':
          npc-uuids-to-talk-to:
          - 1069272b-f55b-4d78-a38e-3b6013e550f8
          start-message: '&6&lLe bois, c''est la base d''une relation solide par ici
            !'
        '2':
          break-block-names:
          - SPRUCE_LOG
          break-block-amounts:
          - 500
          break-block-durability:
          - 0
          start-message: '&6&lTu dis savoir utiliser une hache ? Prouve-le moi ! &e&lCoupe
            500 bûches de sapin !'
        '3':
          npc-uuids-to-talk-to:
          - 1069272b-f55b-4d78-a38e-3b6013e550f8
          complete-message: '&6&lPas mal, pas mal !'
        '4':
          break-block-names:
          - OAK_LOG
          break-block-amounts:
          - 500
          break-block-durability:
          - 0
          start-message: '&6&lLe sapin c''est assez facile, mais comment tu te débrouilles
            avec un bois plus solide ?'
        '5':
          npc-uuids-to-talk-to:
          - 1069272b-f55b-4d78-a38e-3b6013e550f8
          complete-message: '&6&lImpressionant !'
        '6':
          use-block-names:
          - OAK_LOG
          use-block-amounts:
          - 500
          use-block-durability:
          - 0
          start-message: '&6&lMaintenant montres moi comment tu t''y prends pour enlever
            l''écorce d''une bûche !'
        '7':
          npc-uuids-to-talk-to:
          - 1069272b-f55b-4d78-a38e-3b6013e550f8
          complete-message: '&6&lBravo, tu es vraiment doué avec une hache, mes respects
            !'
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: IRON_AXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Hache
            de Thorkild"}],"text":""}'
          repair-cost: 511
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: OAK_SAPLING
        amount: 5
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: SPRUCE_SAPLING
        amount: 5
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: BIRCH_SAPLING
        amount: 5
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: JUNGLE_SAPLING
        amount: 5
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: ACACIA_SAPLING
        amount: 5
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: DARK_OAK_SAPLING
        amount: 5
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: MANGROVE_PROPAGULE
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: IRON_NUGGET
        amount: 64
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"1
            Ecu"}],"text":""}'
          repair-cost: 511
      quest-points: 5
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
