### ISSUE TITLE
Action isn't giving the correct amount of items

### ISSUE THREAD

**Issue by RocketManKian** [PikaMug/Quests#2080]
### What is your Quests version / build number (do *not* say "latest")?

4.7.2-b391

### Describe the problem and how to replicate it.

Make an action like the one below

`  GiveMap:
    message: "<green>Follow the Adventurer Map to find the Lost Temple!"
    items:
    - ==: org.bukkit.inventory.ItemStack
      v: 3218
      type: FILLED_MAP
      meta:
        ==: ItemMeta
        meta-type: MAP
        display-name: '{"extra":[{"text":"Desert Explorer Map"}],"text":""}'
        internal: H4sIAAAAAAAA/+NiYOBk4HZJTc4vSizJzM8r5mJgYGBkZGApqSxIlWJjYC7KL3FIa2AAAQ4GpswUBkZtNgbGKocf/8BiQHaFwzdNBggAAE4gVFpOAAAA
        map-id: 518
        amount: 1`
        
Then apply it to a Quest Stage and for some reason it'll give you two items, when in chat it says "Desert Explorer Map x 1".

### Any console errors to share?

```shell
N/A
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom2:
    name: Desert Diving
    ask-message: C'mere mate! We have a temple to explore...
    finish-message: Well done!
    npc-giver-uuid: 293b346d-4475-489b-a250-f525bf8efb24
    stages:
      ordered:
        '1':
          locations-to-reach:
          - TheWilds 100070.0 102.0 100020.0
          reach-location-radii:
          - 5
          reach-location-names:
          - Desert Temple
          finish-event: GiveMap
          complete-message: Well done! You reached the Temple of Indiana Jones
```
