### ISSUE TITLE
REDO QUEST BUG

### ISSUE THREAD

**Issue by Regwield** [PikaMug/Quests#2083]
### What is your Quests version / build number (do *not* say "latest")?

4.8.0

### Describe the problem and how to replicate it.

When I try to redo the quest that I've already done, it is not giving me the quest and saying anything as well.

No requirements set on the mission.

![image2](https://user-images.githubusercontent.com/97476291/229294080-3de8091b-f8fd-4830-9308-5fa6ba4141ae.png)
3f61c6b.png)

Timings are done.

![image](https://user-images.githubusercontent.com/97476291/229294097-e9d0494e-2585-4506-838f-d44f84a1cafe.png)

When I go to the NPC and click on it in order to redo the mission it says this in chat and not giving me the quest.

![image3](https://user-images.githubusercontent.com/97476291/229294031-57d6850a-f5bc-4c0d-8c98-c174ed7caf1f.png)
27.png)

### Any console errors to share?

```shell
No errors appear on console.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
default2:
    name: Mob Hunter
    ask-message: §eKill an assortment of Mobs.
    finish-message: §eExcellent. Here is a §dDiamond Sword§e.
    npc-giver-uuid: d5e318a5-35eb-41c0-95cf-859aa522c7e1
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Pig
          mob-amounts:
          - 3
          finish-event: NiceFinish
          death-event: DeathFail
        '2':
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 2
          finish-event: NiceFinish
          death-event: DeathFail
        '3':
          mobs-to-kill:
          - Skeleton
          mob-amounts:
          - 1
          death-event: DeathFail
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3218
        type: DIAMOND_SWORD
      quest-points: 1
      exp: 100
    planner:
      start: 1:3:2023:16:40:50:Turkey
      end: 1:3:2023:19:50:50:Turkey
      repeat: 18
      cooldown: 18
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
