### ISSUE TITLE
MISSION QUIT

### ISSUE THREAD

**Issue by Regwield** [PikaMug/Quests#2085]
### What is your Quests version / build number (do *not* say "latest")?

4.8.1

### Describe the problem and how to replicate it.

When I try to quit the mission and type /quests quit "mission name" it says "An unknown error occured. See console output." but there is no error on console, if I type "yes" or "no" commands are working fine.  The issue is, the system is sending a warning message in chat rather than sending "mission quit informations". 

![image](https://user-images.githubusercontent.com/97476291/229312113-dae8cb71-e6c8-428b-b8e2-7508a0b33be2.png)

### Any console errors to share?

```shell
No errors appear on console.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
default2:
    name: Mob Hunter
    ask-message: §eKill an assortment of Mobs.
    finish-message: §eExcellent. Here is a §dDiamond Sword§e.
    npc-giver-uuid: d5e318a5-35eb-41c0-95cf-859aa522c7e1
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Pig
          mob-amounts:
          - 3
          finish-event: NiceFinish
          death-event: DeathFail
        '2':
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 2
          finish-event: NiceFinish
          death-event: DeathFail
        '3':
          mobs-to-kill:
          - Skeleton
          mob-amounts:
          - 1
          death-event: DeathFail
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3218
        type: DIAMOND_SWORD
      quest-points: 1
      exp: 100
    planner:
      start: 1:3:2023:16:40:50:Turkey
      end: 1:3:2023:19:50:50:Turkey
      repeat: 18
      cooldown: 18
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
