### ISSUE TITLE
Quest Block Not Working

### ISSUE THREAD

**Issue by Regwield** [PikaMug/Quests#2088]
### What is your Quests version / build number (do *not* say "latest")?

4.8.1

### Describe the problem and how to replicate it.

Quest block is not working as mentioned in wiki. (Quest which must be taken before this one). I am choosing "set quest blocks" and typing the quest that has to be taken before the quest (default4) that I am editing (test1). But nothing is happening, even tho I did not take the quest that has to be taken before (default4) taking"test1", it is giving me the quest (test1)

### Any console errors to share?

```shell
No errors on console.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
default4:
    name: Timed Quest
    ask-message: <yellow>Dig up <pink>10<yellow> blocks of <pink>Dirt<yellow> before
      time runs out!
    finish-message: <yellow>You did it in time! Have an <pink>Iron Shovel<yellow>
      and some <green>experience<yellow>.
    requirements:
      quest-points: 1
      fail-requirement-message: <red>Complete <pink>Iron Miner<red> or <pink>Mob Hunter<red>
        first.
    stages:
      ordered:
        '1':
          break-block-names:
          - DIRT
          break-block-amounts:
          - 10
          break-block-durability:
          - 0
          start-event: TimerStart
          finish-event: CancelTimer
    rewards:
      items:
      - name-GOLD_INGOT:amount-1
      exp: 150
  custom1:
    name: test1
    ask-message: Challenge objectives!
    finish-message: Well done!
    npc-giver-uuid: 4e4ab01c-14f1-417c-885f-d4460de9b675
    requirements:
      quests:
      - default4
    stages:
      ordered:
        '1':
          npc-uuids-to-talk-to:
          - c61361cc-a312-4155-87ef-721a4769cbcd
```
