### ISSUE TITLE
Brewing Stand Quests Bypasses

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2096]
### What is your Quests version / build number (do *not* say "latest")?

4.8.1-b404

### Describe the problem and how to replicate it.

Any quest created that requires brewing a potion can be easily bypassed by simply putting the correct potion into the brewing stand, taking it out of the brewing stand, and then putting it back. So all a player needs to do is own exactly 1 potion that the quest is calling for, accept the quest, and just spam putting in and taking it out of the stand to complete the quest. Having it like this makes all brewing quests entirely pointless. An option similar to "ignore-block-replace: true" for break/place quests should exist for other types of quests. Brewing, smelting, crafting, etc should all behave like that to prevent easy abuse.

### Any console errors to share?

```shell
n/a
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom2:
    name: Witching 101
    ask-message: The trick is getting the nether wart before the lava gets you. Get
      $30,000 for completion!
    finish-message: Rewarded for completing Witching 101!
    stages:
      ordered:
        '1':
          items-to-brew:
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: POTION
            amount: 64
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:fire_resistance
    rewards:
      money: 30000
      quest-points: 1
    planner:
      cooldown: 86400
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: false
      share-progress-level: 1
      same-quest-only: true
      share-distance: 50.0
      handle-offline-players: false
      ignore-block-replace: true
```
