### ISSUE TITLE
Mooshroom appears without display name

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2099]
### What is your Quests version / build number (do *not* say "latest")?

4.8.2-b406

### Describe the problem and how to replicate it.

Create any quest that includes Mooshrooms (or MushroomCow) and do /quest to check the quest requirements.

### Any console errors to share?

```shell
N/a
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom34:
    name: Mooshroom Research
    ask-message: In the field of mycology there is mushroom for discussion. Get $20,000
      for completion!
    finish-message: Rewarded for completing Mooshroom Research!
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - MushroomCow
          mob-amounts:
          - 32
    rewards:
      money: 20000
      quest-points: 1
    planner:
      cooldown: 86400
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: false
      share-progress-level: 1
      same-quest-only: true
      share-distance: 50.0
      handle-offline-players: false
      ignore-block-replace: true
```
