### ISSUE TITLE
Custom Item name not being used.

### ISSUE THREAD

**Issue by Triple3Aaron** [PikaMug/Quests#2116]
### What is your Quests version / build number (do *not* say "latest")?

Quests-4.8.2.jar

### Describe the problem and how to replicate it.

For one of my quests, I require the player to craft a custom item named "Coal Prestige Core" and the quest understands and only accepts the custom item, but it tells the player to craft a Coal Block. Is there a way to get it to show the Custom Item name instead? Below is the config for the entire stage. I used the ingame quest editor to add the item and it displays correctly. It just tells the player to craft a Coal Block though.

        '5':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: COAL_BLOCK
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"Coal
                Prestige Core"}],"text":""}'
              enchants:
                DURABILITY: 1
              repair-cost: 1

### Any console errors to share?

```shell
No console errors
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
This is the entire quest config, but the only issue is with the name showing as coal block for stage 5 in stead of Coal Prestige Core.

  custom1:
    name: Coal Rank
    ask-message: Challenge objectives!
    finish-message: Well done!
    npc-giver-uuid: 593a3e48-d429-49b2-b719-ff262c9dd507
    requirements:
      money: 50000
      permissions:
      - prefix.0.&7&l[Member]
    stages:
      ordered:
        '1':
          break-block-durability: []
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: STONE_SWORD
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: STONE_PICKAXE
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: STONE_AXE
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: STONE_SHOVEL
          start-message: You'll want something better than the starter tools to begin.
        '2':
          mobs-to-kill:
          - Cow
          mob-amounts:
          - 16
          start-message: Kill a few cows to make some food and armor.
        '3':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: LEATHER_HELMET
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: LEATHER_CHESTPLATE
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: LEATHER_LEGGINGS
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: LEATHER_BOOTS
          items-to-smelt:
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: COOKED_BEEF
            amount: 16
          start-message: Time to make that armor and food for the journey ahead.
        '4':
          break-block-names:
          - COAL_ORE
          break-block-amounts:
          - 256
          break-block-durability:
          - 0
          start-message: I know it's a lot of coal. You'll thank me for it later.
        '5':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: COAL_BLOCK
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"Coal
                Prestige Core"}],"text":""}'
              enchants:
                DURABILITY: 1
              repair-cost: 1
    rewards:
      commands:
      - lp user <player> parent set default
      - lp user <player> parent set coal
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
