### ISSUE TITLE
Quest "Block Breaking" stops counting at random numbers

### ISSUE THREAD

**Issue by LilSwiffer** [PikaMug/Quests#2121]
### What is your Quests version / build number (do *not* say "latest")?

4.8.2

### Describe the problem and how to replicate it.

I created a quest called Coal Miner II, set the requirement to break 300 coal ore. It randomly stopped going up at 281 ores mined. So I lowered the requirement to 250, it then stopped going up at 240.

### Any console errors to share?

```shell
No errors in console
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom2:
    name: Coal Miner II
    ask-message: '- Mine 250 Coal Ore'
    finish-message: Well done!
    stages:
      ordered:
        '1':
          break-block-names:
          - COAL_ORE
          break-block-amounts:
          - 250
          break-block-durability:
          - 0
    rewards:
      money: 100000
      commands:
      - excellentcrates key give <player> quest_crate_key 2
```
