### ISSUE TITLE
The time in the in-game editor is different from the one in the yaml file

### ISSUE THREAD

**Issue by poyu39** [PikaMug/Quests#2130]
### What is your Quests version / build number (do *not* say "latest")?

![image](https://github.com/PikaMug/Quests/assets/42506064/7b863919-745a-4f8f-8549-753a3719b3f7)

### Describe the problem and how to replicate it.

I want to set planner by in-game editor but when i input and click finish, it display i set a wrong time.

### Any console errors to share?

```shell
no
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
spawner_lv1:
    name: §6[實驗體研究]§f掃蕩荒野 lv1
    ask-message: §7[§#54ade3星羽§7] §b請到荒野星球掃蕩實驗體
    finish-message: §7[§#54ade3星羽§7] §b好像有甚麼東西從實驗體身上掉落下來了
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Zombie
          - Skeleton
          - Spider
          - Creeper
          mob-amounts:
          - 10
          - 10
          - 10
          - 10
    rewards:
      commands:
      - ei give <player> spawner_lv1 1
      details-override:
      - §#BBBCE6[R] §#dda288實驗體殘骸 §7lv1 §6x1
    planner:
      start: 27:6:2023:0:0:0:Asia/Taipei
      end: 27:6:2023:23:59:59:Asia/Taipei
      repeat: 86400
      cooldown: 86400
      override: true
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
