### ISSUE TITLE
quest cooldown not working

### ISSUE THREAD

**Issue by lowkikarit** [PikaMug/Quests#2137]
### What is your Quests version / build number (do *not* say "latest")?

Quests version : 4.8.3 Yuzu Update

### Describe the problem and how to replicate it.

I added a quest to my Citizen 2 NPC.
I set the cooldown for 9 hours/32400 before players can take the quest again but,
The quest icon says completed but can be taken again by players right after finishing it without going to cooldown.

### Any console errors to share?

```shell
Nope
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
# For non-English characters, this file MUST stay encoded in UTF-8
quests:
  custom1:
    name: Coal Miner
    ask-message: Challenge objectives!
    finish-message: Well done!
    npc-giver-uuid: 3a514d3a-b40b-4cd7-9ee7-1de524c765f1
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3465
      type: COAL_ORE
    stages:
      ordered:
        '1':
          npc-uuids-to-talk-to:
          - 3a514d3a-b40b-4cd7-9ee7-1de524c765f1
        '2':
          break-block-names:
          - COAL_ORE
          break-block-amounts:
          - 24
          break-block-durability:
          - 0
        '3':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: COAL
            amount: 24
          npc-delivery-uuids:
          - c0475fa5-d89f-4a7f-9483-0a0f171beb5b
          delivery-messages:
          - Thank you. Only <amount> more to go!
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: TORCH
        amount: 64
      - ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: TORCH
        amount: 64
      - ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: TORCH
        amount: 64
      exp: 500
    planner:
      start: 3:7:2023:6:0:0:Asia/Singapore
      end: 3:7:2023:22:0:0:Asia/Singapore
      repeat: 86400
      cooldown: 32400
      override: true
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: false
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: true
      ignore-block-replace: true
```
