### ISSUE TITLE
Quest objectives overflowing in quest journal

### ISSUE THREAD

**Issue by Masterfixer06** [PikaMug/Quests#2141]
### What is your Quests version / build number (do *not* say "latest")?

4.8.3-b423

### Describe the problem and how to replicate it.

I made a quest that has too many assignments/objectives (I don't know how you call them) in one stage, so when I do /quests journal not all the assignments show up in the journal, because the journal is too small. So now, there is no way for players to see all of their assignments of that stage.

Maybe make the quest journal have multiple pages when the assignments are overflowing on one page? Or is there a fix for this I have overlooked?

Thanks in advance!

### Any console errors to share?

```shell
no
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom5:
    name: Stone Season
    ask-message: Ad likes rocks.
    finish-message: Well done!
    npc-giver-uuid: 24040d52-459e-4c16-92eb-3733938c3c19
    stages:
      ordered:
        '1':
          break-block-names:
          - STONE
          - ANDESITE
          - DIORITE
          break-block-amounts:
          - 1000
          - 200
          - 200
          break-block-durability:
          - 0
          - 0
          - 0
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: COBBLESTONE
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: COBBLESTONE
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: COBBLESTONE
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: COBBLESTONE
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: STONE
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: STONE
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: DIORITE
            amount: 50
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: ANDESITE
            amount: 50
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: AMETHYST_BLOCK
            amount: 10
          npc-delivery-uuids:
          - 882e0ad8-2916-4310-acfc-c74d59b305a2
          - 882e0ad8-2916-4310-acfc-c74d59b305a2
          - 882e0ad8-2916-4310-acfc-c74d59b305a2
          - 882e0ad8-2916-4310-acfc-c74d59b305a2
          - 882e0ad8-2916-4310-acfc-c74d59b305a2
          - 882e0ad8-2916-4310-acfc-c74d59b305a2
          - 882e0ad8-2916-4310-acfc-c74d59b305a2
          - 882e0ad8-2916-4310-acfc-c74d59b305a2
          - 882e0ad8-2916-4310-acfc-c74d59b305a2
          delivery-messages:
          - Thank you. Only <amount> more to go!
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: EMERALD
        amount: 13
      - ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: DIAMOND
        amount: 8
      - ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: IRON_INGOT
        amount: 37
      - ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: ANCIENT_DEBRIS
        amount: 2
      - ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: ENCHANTED_BOOK
        meta:
          ==: ItemMeta
          meta-type: ENCHANTED
          stored-enchants:
            DURABILITY: 3
      - ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: ENCHANTED_BOOK
        meta:
          ==: ItemMeta
          meta-type: ENCHANTED
          stored-enchants:
            BINDING_CURSE: 1
      - ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: SCULK_SENSOR
        amount: 6
      - ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: MANGROVE_PROPAGULE
        amount: 11
      quest-points: 3000
      exp: 250
```
