### ISSUE TITLE
Some error is spamming my console sometimes

### ISSUE THREAD

**Issue by pjindras** [PikaMug/Quests#2143]
### What is your Quests version / build number (do *not* say "latest")?

 Quests 4.8.3-b42

### Describe the problem and how to replicate it.

https://paste.hostify.cz/?8e21269f59a72167#FxHYCzfRMAVu2ajLS5ZDCoHSqFBuQ7of6WiXGPeVdBez

Player cannot take a quest from NPC.

### Any console errors to share?

```shell
https://paste.hostify.cz/?8e21269f59a72167#FxHYCzfRMAVu2ajLS5ZDCoHSqFBuQ7of6WiXGPeVdBez
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
quests:
  custom1:
    name: Q1 - Vítej v našem městě!
    ask-message: Vítám tě tu u nás, v našem skromném, ale zato pestrém městečku. Doufám,
      že máš rád dobrodružství a nebojíš se práce. Mám na tebe totiž prosbu. Jdeš
      do toho?
    finish-message: Děkuji ti moc za pomoc! Konečně mám čím dostavit svůj domek na
      venkově. Zde přijmi moji odměnu. §cSlyšel jsem, že kovář by potřeboval taky
      s něčím pomoci.
    npc-giver-uuid: a606b52f-f6cd-43b4-a036-8a4bd51d2caf
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: OAK_LOG
            amount: 16
          npc-delivery-uuids:
          - a606b52f-f6cd-43b4-a036-8a4bd51d2caf
          delivery-messages:
          - Děkuji. Zbývá už jen <amount>!
    rewards:
      money: 200
      quest-points: 1
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
