### ISSUE TITLE
Custom Module Objective Message Duplication

### ISSUE THREAD

**Issue by Dylan-Buchanan** [PikaMug/Quests#2153]
### What is your Quests version / build number (do *not* say "latest")?

4.8.3

### Describe the problem and how to replicate it.

When given the objective for a quest that uses a custom quest objective the message is duplicated.

### Any console errors to share?

```shell
No console errors but I assume it is an error with the Quest API
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
ordered:
        '1':
          custom-objectives:
            custom1:
              name: Total Blocks Broken Objective
              count: 1
              data:
                Total: '150'
                Obj Name: This is doubled and shouldn't be
          start-event: a-mine-pickaxe
          delay: 2
          start-message: '&aMiner: &fLet''s start with the basics'
```
