### ISSUE TITLE
Quests can be taken infinitely and talk to npc does nothing

### ISSUE THREAD

**Issue by Casanaura** [PikaMug/Quests#2155]
### What is your Quests version / build number (do *not* say "latest")?

5.0.0-RC.2-B433
Also tried with 5.0.0-RC.1 (The one from this Github)

### Describe the problem and how to replicate it.

I have two problems, actually.

The first one is, when you select "Talk to NPC" as a part of a Stage, it won't validate and you can't continue to the next stage (or finnish the quest).

My second error is, i have one single quest but i can take it infinitely; that means that after i finish the quest, i can take it again, and again, and again. And there's no option to turn repeatable quests off. I've tried setting a cooldown but still does nothing to fix this issue.

### Any console errors to share?

```shell
No errors
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
# For non-English characters, this file MUST stay encoded in UTF-8
quests:
  custom1:
    name: Carrera de Cheff I
    ask-message: Nuestra Cheff ha estado muy atareada últimamente y le gustaría recibir
      ayuda para preparar los alimentos del Restaurante
    finish-message: §c§lINFO§4 »§7 Has desbloqueado las misiones de Cocinero/a. Ahora
      podrás trabajar para el Restaurante Yamikeshi cada vez que tú quieras.
    npc-giver-uuid: c69ecc9e-2c96-4e30-995b-9c40024086cd
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3578
      type: MUSHROOM_STEW
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3578
            type: PAPER
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"light_purple","text":"Nota
                de Yuki"}],"text":""}'
              lore:
              - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}'
              - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Una
                nota escrita a mano"}],"text":""}'
              - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"por
                Yuki."}],"text":""}'
          npc-delivery-uuids:
          - 849d8f81-3c22-4643-b3fc-313d6ecf4b4a
          delivery-messages:
          - ¡Gracias! Sólo te faltan <amount> más
          start-event: cheffCareerI
          start-message: '&aYuki:&7 Baja a la cocina, preséntate con Alessa y entrega
            esta nota de mi parte; con eso estará más que contenta de recibirte como
            aprendíz.'
          complete-message: '&aAlessa:&7 Hmmm... Supongo que si vienes recomendado/a
            por Yuki no tengo más opción que aceptarte y enseñarte a cocinar... ¡Vale!
            Nos vemos mañana.'
    rewards:
      quest-points: 1
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
