### ISSUE TITLE
NPC tries giving quests 

### ISSUE THREAD

**Issue by Assasinowy** [PikaMug/Quests#2156]
### What is your Quests version / build number (do *not* say "latest")?

4.8.3 and i will write here Citizens version bcz i think that it will matter more 2.0.29

### Describe the problem and how to replicate it.

There isnt much details just use the quest version command npc and citizens in quests go to NPC kill NPC and select this npc add random kill value and viola if you press right click on the NPC that is supposed to be killed he will say "Nie ma więcej dostępnych zadań" in polish and in english i think "There are no more quests available"

### Any console errors to share?

```shell
no
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom2:
    name: §6§lDealer Kenji
    ask-message: Do roboty
    finish-message: Dobra robota!
    npc-giver-uuid: 508ab801-96b7-427f-98f2-16b2fc03e71b
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      type: ENCHANTED_BOOK
      meta:
        ==: ItemMeta
        meta-type: ENCHANTED
        display-name: §5§lZadanie Dealer Kenji§l
        lore:
        - '§eKenji ostatnio nie slucha '
        - '§esie naszych rozkazow i '
        - '§edziala samowolnie. Dostalismy '
        - '§einformacje, ze planuje bunt. '
        - §eChyba wiesz, co masz zrobic?
    stages:
      ordered:
        '1':
          locations-to-reach:
          - GTAMAPA 2706.0 77.0 1537.0
          reach-location-radii:
          - 5
          reach-location-names:
          - siedziby dealera Kenji
        '2':
          npc-uuids-to-kill:
          - 3d567b3a-cf64-43b8-a614-d12cde8eee6d
          npc-kill-amounts:
          - 3
        '3':
          npc-uuids-to-talk-to:
          - 508ab801-96b7-427f-98f2-16b2fc03e71b
    rewards:
      money: 150
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
