### ISSUE TITLE
Bug 1000 potions

### ISSUE THREAD

**Issue by danyadanya2005** [PikaMug/Quests#2160]
### What is your Quests version / build number (do *not* say "latest")?

![image](https://github.com/PikaMug/Quests/assets/51532656/339daa86-2bfe-4e8b-9a87-fb65ed4a1687)
Purpur version git-Purpur-2015 
[Quests] Loading server plugin Quests v5.0.0-rc.2-b435

### Describe the problem and how to replicate it.

brew more than 1000 potions. the plugin doesn’t see them and says “make Air 0 from 0”

### Any console errors to share?

```shell
no
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
stages:
      ordered:
        '1':
          items-to-brew:
          - ==: org.bukkit.inventory.ItemStack
            v: 2584
            type: LINGERING_POTION
            amount: 1000
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:leaping
```
