### ISSUE TITLE
Progress Reset with Location Objectives

### ISSUE THREAD

**Issue by Altashie** [PikaMug/Quests#2164]
### What is your Quests version / build number (do *not* say "latest")?

5.0.0-rc.2-b435

### Describe the problem and how to replicate it.

I have an issue where if I set a quest to have multiple reach-location objectives for a single stage, and a player only reaches some of those locations, then their progress for which locations they visited resets when the plugin is reloaded.

### Any console errors to share?

```shell
None
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom128:
    name: LOCA
    ask-message: Challenge objectives!
    finish-message: Well done!
    block-start: Events -4492.0 62.0 -3820.0
    stages:
      ordered:
        '1':
          locations-to-reach:
          - Events -4488.0 63.0 -3822.0
          - Events -4488.0 63.0 -3818.0
          - Events -4488.0 63.0 -3815.0
          reach-location-radii:
          - 5
          - 5
          - 5
          reach-location-names:
          - 'Location #1'
          - 'Location #2'
          - 'Location #3'
```
