### ISSUE TITLE
Placeholder 

### ISSUE THREAD

**Issue by Blskk** [PikaMug/Quests#2183]
### What is your Quests version / build number (do *not* say "latest")?

version: 5.0.0-rc.4-b446

### Describe the problem and how to replicate it.

If the player currently has unfinished quests, the Placeholder will become invalid when they log in again

 %quests_player_compass_quest_name% 
%Quests_player_compass_quest_objectives%

### Any console errors to share?

```shell
no
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
quests:
  default1:
    name: Iron Miner
    ask-message: <yellow>Mine <pink>2<yellow> blocks of <pink>Iron Ore<yellow>.
    finish-message: <yellow>Well done. Here is your reward.
    redo-delay: 1800
    requirements:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: STONE_PICKAXE
      remove-items:
      - false
      fail-requirement-message: <red>You must have a <pink>Stone Pickaxe<red> first.
    stages:
      ordered:
        '1':
          break-block-names:
          - IRON_ORE
          break-block-amounts:
          - 2
          break-block-durability:
          - 0
    rewards:
      money: 1000
      quest-points: 1
  default2:
    name: Mob Hunter
    ask-message: <yellow>Kill an assortment of Mobs.
    finish-message: <yellow>Excellent. Here is a <pink>Diamond Sword<yellow>.
    stages:
      ordered:
        '1':
          death-event: DeathFail
          mobs-to-kill:
          - Pig
          mob-amounts:
          - 3
          finish-event: NiceFinish
        '2':
          death-event: DeathFail
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 2
          finish-event: NiceFinish
        '3':
          death-event: DeathFail
          mobs-to-kill:
          - Skeleton
          mob-amounts:
          - 1
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: DIAMOND_SWORD
      exp: 100
      quest-points: 1
  default3:
    name: Catch Fish
    ask-message: <yellow>Catch some fish!
    finish-message: <yellow>Good job. Here is some <green>experience<yellow>.
    stages:
      ordered:
        '1':
          start-event: GiveRod
          death-event: DeathFail
          fish-to-catch: 2
    rewards:
      exp: 250
```
