### ISSUE TITLE
The overhead note effect does not work

### ISSUE THREAD

**Issue by Dragsio** [PikaMug/Quests#2189]
### What is your Quests version / build number (do *not* say "latest")?

5.0.0-rc.4-b446

### Describe the problem and how to replicate it.

The note above the heads of the npcs does not work, it was still working before the update from the previous build. I have it set in config.yml

```yaml
npc-effects:
  enabled: true
  new-quest: note
  redo-quest: heart
```

### Any console errors to share?

```shell
none
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom69:
    name: Samved
    ask-message: Good day sir. My name is Sam.
    finish-message: Goodbye then. But if you want to see something else, go to Hill.
You might find something interesting there. 
The heat lies here -15428 65 4576
    npc-giver-uuid: 224d726b-638a-4406-97fa-1d478235b3fd
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: DIAMOND_HOE
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              enchants:
                DURABILITY: 3
          npc-delivery-uuids:
          - 224d726b-638a-4406-97fa-1d478235b3fd
          delivery-messages:
          - Thanks
          start-message: Could I ask you a favor? I make a living as a gardener
             but my tools broke. Could you please get me a new one? bring me
             please undamaged diamond hoe with enchant unbreaking 3 let me
             it will last.
          complete-message: Thank you so much.
        '2':
          password-displays:
          - 8 letters, plant
          password-phrases:
          - potatoes
          start-message: But do you know what my favorite plant is? Her tubers are great
             to eat. You can boil them, mash them and put them in a sauce. And they are great
             like french fries. Do you know what vegetables I'm talking about?
          complete-message: Correctly. POTATOES
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3700
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: minecraft:strong_strength
      money: 50
      quest-points: 1
      commands:
      - resadmin pset hill <player> move t
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
