### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by vxkShelby** [PikaMug/Quests#2190]
### What is your Quests version / build number (do *not* say "latest")?

v3.15-b636bef

### Describe the problem and how to replicate it.

Console Errors

### Any console errors to share?

```shell
04.03 11:25:26 [Server] ERROR [Quests] Could not set color for the initialized boss bar implementation, using default instead!
04.03 11:25:26 [Server] INFO java.lang.IllegalStateException: color section is missing
04.03 11:25:26 [Server] INFO at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.loadConfig(BossBar_Bukkit.java:96) ~[Quests-3.15-b636bef.jar:?]
04.03 11:25:26 [Server] INFO at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.<init>(BossBar_Bukkit.java:37) ~[Quests-3.15-b636bef.jar:?]
04.03 11:25:26 [Server] INFO at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:680) ~[Quests-3.15-b636bef.jar:?]
04.03 11:25:26 [Server] INFO at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:308) ~[Quests-3.15-b636bef.jar:?]
04.03 11:25:26 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
04.03 11:25:26 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
04.03 11:25:26 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at java.lang.Thread.run(Thread.java:840) ~[?:?]
04.03 11:25:26 [Server] ERROR [Quests] Could not set style for the initialized boss bar implementation, using default instead!
04.03 11:25:26 [Server] INFO java.lang.IllegalStateException: style section is missing
04.03 11:25:26 [Server] INFO at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.loadConfig(BossBar_Bukkit.java:96) ~[Quests-3.15-b636bef.jar:?]
04.03 11:25:26 [Server] INFO at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.<init>(BossBar_Bukkit.java:40) ~[Quests-3.15-b636bef.jar:?]
04.03 11:25:26 [Server] INFO at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:680) ~[Quests-3.15-b636bef.jar:?]
04.03 11:25:26 [Server] INFO at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:308) ~[Quests-3.15-b636bef.jar:?]
04.03 11:25:26 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
04.03 11:25:26 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
04.03 11:25:26 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
04.03 11:25:26 [Server] INFO at java.lang.Thread.run(Thread.java:840) ~[?:?]
04.03 11:25:26 [Server] INFO [Quests] Metrics started. This can be disabled at /plugins/bStats/config.yml.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
# This is a quest which requires the previous quest to be complete to start.

tasks:
  # Unlike the previous quest, this quest has multiple tasks.
  mining:
    type: "blockbreak"
    amount: 100
  building:
    type: "blockplace"
    amount: 100
display:
  name: "&cExample II (Multiple Tasks)"
  lore-normal:
    - "&cThis category is designed to show you the different"
    - "&cattributes a quest can have. This quest requires"
    - "&cmultiple things to be done, unlike the previous one."
    - ""
    - "&7This quest requires you to:"
    - "&7 - Break &f100 &7blocks."
    - "&7 - Place &f100 &7blocks."
    - ""
    - "&7Rewards:"
    - "&7 - &f15 diamonds&7."
    - "&7 - &f$50&7 added to your in-game balance."
  lore-started:
    - ""
    - "&7Your current progression:"
    - "&7 - &f{mining:progress}&7/100 blocks broken."
    - "&7 - &f{building:progress}&7/100 blocks placed."
  type: "GRASS_BLOCK"
rewards:
  - "give {player} diamond 15"
  - "eco give {player} 50"
placeholders:
  description: "&7Break and place &f100 blocks &7of any type."
  progress: " &8- &f{mining:progress}&7/100 broken, &f{building:progress}&7/100 placed"
options:
  category: "examples"
  # Unlike the previous quest, this quest has "example1" as a required quest. You cannot start this quest without "example1" quest complete.
  requires:
    - "example1"
  repeatable: false
  cooldown:
    enabled: true
    time: 1440
  # The sort order has been changed so this quest will appear after in the GUI
  sort-order: 2
```
