### ISSUE TITLE
Quests with Unite and Party

### ISSUE THREAD

**Issue by GuiduusRC98** [PikaMug/Quests#2211]
### What is your Quests version / build number (do *not* say "latest")?

Quests 5.0.0-b452

### Describe the problem and how to replicate it.

On my server based on the story of Harry Potter I added the unite and party add-ons, I questioned that when doing missions where they must defeat mobs of mythicmobs they are generated with a command event for example 1 voldemort, but when doing it together with other people it spawns by example 4 voldemort if 4 people do it together 
### Any console errors to share?

```shell
there is no error in the console
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000016':
    name: El señor tenebroso
    ask-message: §bBellatrix Lestrange - §7El señor tenebroso te tiene justo donde
      queria y nadie podra defenderte... ¡¡YO MATE A SIRIUS BLACK JAJAJAJAJAJA!!
    finish-message: §b<INFO> §7Felicidades, finalizaste el 5to año de Hogwarts.
    npc-giver-uuid: 60f00698-6d0a-4bd7-b7c9-57e94883f6e3
    requirements:
      permissions:
      - mision71
      fail-requirement-message:
      - '&b<INFO> &7Antes debes realizar otras misiones, utiliza &b/misiones&7.'
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Husk
          mob-amounts:
          - 1
          locations-to-kill:
          - extras 4.0 3.0 1461.0
          kill-location-radii:
          - 200
          kill-location-names:
          - voldemort_1
          start-event: ComenzarMision14E
          objective-override:
          - '&b<INFO> &7Derrota a voldemort.'
```
```yaml
 ComenzarMision14E:
    commands:
    - c forcecast <player> misionComenzar    
    - tp <player> 32 53 1489
    - mm m spawn Voldemort_señor_primero 1 extras,78,52,1469
```
