### ISSUE TITLE
My server got crashed due to Quests.

### ISSUE THREAD

**Issue by TheProOne1** [PikaMug/Quests#2212]
### What is your Quests version / build number (do *not* say "latest")?

5.0.1

### Describe the problem and how to replicate it.

The server was working fine until the server got crashed and the following console error spammed continously in console:

### Any console errors to share?

```shell
[08:43:03] [Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH  - git-Purpur-2176 (MC: 1.20.4) ---
[08:43:03] [Watchdog Thread/ERROR]: The server has not responded for 40 seconds! Creating thread dump
[08:43:03] [Watchdog Thread/ERROR]: ------------------------------
[08:43:03] [Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Purpur!):
[08:43:03] [Watchdog Thread/ERROR]: ------------------------------
[08:43:03] [Watchdog Thread/ERROR]: Current Thread: Server thread
[08:43:03] [Watchdog Thread/ERROR]: 	PID: 65 | Suspended: false | Native: false | State: WAITING
[08:43:03] [Watchdog Thread/ERROR]: 	Stack:
[08:43:03] [Watchdog Thread/ERROR]: 		java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method)
[08:43:03] [Watchdog Thread/ERROR]: 		java.base@21.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[08:43:03] [Watchdog Thread/ERROR]: 		java.base@21.0.3/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
[08:43:03] [Watchdog Thread/ERROR]: 		java.base@21.0.3/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
[08:43:03] [Watchdog Thread/ERROR]: 		java.base@21.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
[08:43:03] [Watchdog Thread/ERROR]: 		java.base@21.0.3/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
[08:43:03] [Watchdog Thread/ERROR]: 		java.base@21.0.3/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
[08:43:03] [Watchdog Thread/ERROR]: 		Quests-5.0.1.jar//me.pikamug.quests.player.BukkitQuester.saveData(BukkitQuester.java:3759)
[08:43:03] [Watchdog Thread/ERROR]: 		Quests-5.0.1.jar//me.pikamug.quests.listeners.BukkitPlayerListener.onPlayerQuit(BukkitPlayerListener.java:941)
[08:43:03] [Watchdog Thread/ERROR]: 		com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor946.execute(Unknown Source)
[08:43:03] [Watchdog Thread/ERROR]: 		org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[08:43:03] [Watchdog Thread/ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[08:43:03] [Watchdog Thread/ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[08:43:03] [Watchdog Thread/ERROR]: 		io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[08:43:03] [Watchdog Thread/ERROR]: 		io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[08:43:03] [Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[08:43:03] [Watchdog Thread/ERROR]: 		net.minecraft.server.players.PlayerList.remove(PlayerList.java:615)
[08:43:03] [Watchdog Thread/ERROR]: 		net.minecraft.server.players.PlayerList.remove(PlayerList.java:599)
[08:43:03] [Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2164)
[08:43:03] [Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2144)
[08:43:03] [Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2131)
[08:43:03] [Watchdog Thread/ERROR]: 		net.minecraft.network.Connection.handleDisconnection(Connection.java:847)
[08:43:03] [Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254)
[08:43:03] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1781)
[08:43:03] [Watchdog Thread/ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487)
[08:43:03] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558)
[08:43:03] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246)
[08:43:03] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[08:43:03] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda/0x00007ff3ccbdd1c8.run(Unknown Source)
[08:43:03] [Watchdog Thread/ERROR]: 		java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596)
[08:43:03] [Watchdog Thread/ERROR]: 		java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
[08:43:03] [Watchdog Thread/ERROR]: ------------------------------
[08:43:03] [Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH ---
[08:43:03] [Watchdog Thread/ERROR]: ------------------------------
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
quests:
  '000001':
    name: Dragon Slayer
    ask-message: Welcome to the Quest Dungeon. I'm §aDragon Slayer§r, the creator
      of the deadliest and mightiest sword in minecraft. Complete this §cimpossible
      quest §rand win my creation, the §4Dragon Slayer Sword.§r
    finish-message: You're the worthy one. You managed to finish the impossible stages
      of this quest. Here is the strongest sword in the universe to you.
    npc-giver-uuid: e8c04355-4c0d-4f7c-a170-76d8a693e31e
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: NETHERITE_SWORD
          npc-delivery-uuids:
          - e8c04355-4c0d-4f7c-a170-76d8a693e31e
          delivery-messages:
          - Thank you. Only <amount> more to go!
          start-message: Let's begin now, shall we? Bring me a netherite sword.
          complete-message: Good job. It's time for the next stage now.
        '2':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: CHERRY_DOOR
            amount: 64
          npc-delivery-uuids:
          - e8c04355-4c0d-4f7c-a170-76d8a693e31e
          delivery-messages:
          - Thank you. Only <amount> more to go!
          start-event: DragonSlayerStage2
          finish-event: DragonSlayerStage2End
          start-message: I like cherry, so why not cherry doors? heh. And here's free
            blindess for you to make this stage easier for you :D
          complete-message: Got em all? Interesting. Alright let's move ahead!
        '3':
          break-block-names:
          - EMERALD_ORE
          break-block-amounts:
          - 48
          break-block-durability:
          - 0
          start-event: DragonSlayerStage3
          finish-event: DragonSlayerStage3End
          start-message: let's see your mining skills. find and break 48 emerald ores
            if you can.
          complete-message: Not bad. Let's go to the next stage.
        '4':
          mobs-to-kill:
          - Pillager
          mob-amounts:
          - 24
          start-event: DragonSlayerStage4
          finish-event: DragonSlayerStage4End
          start-message: Are you worthy enough to handle this sword? let's test your
            killing skills. kill 24 pillagers if you think you can even find them
            heh
          complete-message: impressive. let's go to the next test.
        '5':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: WAXED_WEATHERED_CUT_COPPER_STAIRS
            amount: 64
          npc-delivery-uuids:
          - e8c04355-4c0d-4f7c-a170-76d8a693e31e
          delivery-messages:
          - Thank you. Only <amount> more to go!
          start-event: DragonSlayerStage5
          start-message: hmmm, so you've reached stage 5 now. things will start getting
            super hard from now. complete this stage by bringing me 64 waxed weathered
            cut copper stairs
          complete-message: excellent work. you managed to complete this stage as
            well, but beware of what lies ahead. next stage!
        '6':
          players-to-kill: 69
          start-message: I demand blood, do you have the skills to give that to me?
            if you think you do, kill 50 players.
          complete-message: ah, fresh juicy blood. thank you! next stage ahead.
        '7':
          mobs-to-kill:
          - Evoker
          mob-amounts:
          - 32
          start-message: Still tryna get my sword? good luck then because the next
            upcoming stages will be impossible for you. Kill 32 evokers now.
          complete-message: Impressive. Next stage coming up!
        '8':
          items-to-consume:
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: ENCHANTED_GOLDEN_APPLE
            amount: 32
          start-message: prove how rich you are, only the worthy ones can have the
            strongest and deadliest sword here. Eat 32 enchanted golden apples.
          complete-message: Woah, unbelievable. You finished this one too? You're
            gettin really close, let's go ahead!
        '9':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: NETHERITE_BLOCK
            amount: 64
          npc-delivery-uuids:
          - e8c04355-4c0d-4f7c-a170-76d8a693e31e
          delivery-messages:
          - Thank you. Only <amount> more to go!
          start-message: hmm, you're a tough guy. but that's not all what takes to
            become the conqueror of my deadly sword, bring me 64 netherite ingots.
          complete-message: Unbelievable, 64 netherite ingots? woah.
        '10':
          locations-to-reach:
          - world 46969.0 68.0 46969.0
          reach-location-radii:
          - 2
          reach-location-names:
          - 46969 69 46969
          start-event: TimerStart
          start-message: wait, wait..... WHAT? you managed to reach the LAST stage
            of this impossible quest? very well then. this is your final and the hardest
            stage. &c&lReach the coords 46969 69 46969 within 2 HOURS, otherwise you
            FAIL THIS QUEST, FOREVER.
          complete-message: NO...... NO. this can't be - you managed to finish the
            impossible quest, you're a true dominator of this universe and you shall
            recieve my reward.
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3700
        type: NETHERITE_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"text":"","extra":[{"text":"D","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF0000","bold":true},{"text":"R","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FE1700","bold":true},{"text":"A","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FE2E00","bold":true},{"text":"G","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FD4600","bold":true},{"text":"O","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FD5D00","bold":true},{"text":"N
            ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FC7400","bold":true},{"text":"S","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FC8B00","bold":true},{"text":"L","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FBA200","bold":true},{"text":"A","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FBB900","bold":true},{"text":"Y","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FAD100","bold":true},{"text":"E","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FAE800","bold":true},{"text":"R","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#F9FF00","bold":true}]}'
          lore:
          - '{"text":"","extra":[{"text":"ᴛ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFFFFF","bold":false},{"text":"ʜ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFF7F7","bold":false},{"text":"ᴇ
            ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFEFEF","bold":false},{"text":"ᴍ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFE7E7","bold":false},{"text":"ɪ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFDFDF","bold":false},{"text":"ɢ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFD7D7","bold":false},{"text":"ʜ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFCFCF","bold":false},{"text":"ᴛ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFC7C7","bold":false},{"text":"ɪ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFBFBF","bold":false},{"text":"ᴇ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFB7B7","bold":false},{"text":"s","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFAFAF","bold":false},{"text":"ᴛ
            ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFA7A7","bold":false},{"text":"s","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF9F9F","bold":false},{"text":"ᴡ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF9695","bold":false},{"text":"ᴏ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF8B88","bold":false},{"text":"ʀ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF807C","bold":false},{"text":"ᴅ
            ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF7570","bold":false},{"text":"ᴏ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF6A63","bold":false},{"text":"ғ
            ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF6057","bold":false},{"text":"ᴀ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF554A","bold":false},{"text":"ʟ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF4A3E","bold":false},{"text":"ʟ
            ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF3F32","bold":false},{"text":"ᴛ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF3425","bold":false},{"text":"ɪ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF2A19","bold":false},{"text":"ᴍ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF1F0C","bold":false},{"text":"ᴇ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF1400","bold":false}]}'
          - '""'
          - '{"text":"","extra":[{"text":"E","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#CC0000","bold":true},{"text":"N","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#D00B00","bold":true},{"text":"C","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#D51700","bold":true},{"text":"H","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#D92200","bold":true},{"text":"A","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#DD2D00","bold":true},{"text":"N","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#E13900","bold":true},{"text":"T","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#E64400","bold":true},{"text":"M","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#EA4F00","bold":true},{"text":"E","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#EE5B00","bold":true},{"text":"N","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#F26600","bold":true},{"text":"T","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#F77100","bold":true},{"text":"S","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FB7D00","bold":true},{"text":":","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF8800","bold":true}]}'
          - '{"text":"","extra":[{"text":"M","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF0000","bold":false},{"text":"e","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF1F00","bold":false},{"text":"n","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF3F00","bold":false},{"text":"d","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF5E00","bold":false},{"text":"i","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF7D00","bold":false},{"text":"n","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF9C00","bold":false},{"text":"g
            ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFBC00","bold":false},{"text":"X","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFDB00","bold":false}]}'
          - '{"text":"","extra":[{"text":"U","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF0000","bold":false},{"text":"n","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF1600","bold":false},{"text":"b","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF2C00","bold":false},{"text":"r","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF4200","bold":false},{"text":"e","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF5800","bold":false},{"text":"a","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF6E00","bold":false},{"text":"k","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF8300","bold":false},{"text":"i","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF9900","bold":false},{"text":"n","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFAF00","bold":false},{"text":"g
            ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFC500","bold":false},{"text":"X","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFDB00","bold":false}]}'
          - '{"text":"","extra":[{"text":"S","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF0000","bold":false},{"text":"w","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF1200","bold":false},{"text":"e","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF2500","bold":false},{"text":"e","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF3700","bold":false},{"text":"p","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF4900","bold":false},{"text":"i","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF5B00","bold":false},{"text":"n","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF6E00","bold":false},{"text":"g
            ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF8000","bold":false},{"text":"E","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF9200","bold":false},{"text":"d","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFA400","bold":false},{"text":"g","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFB700","bold":false},{"text":"e
            ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFC900","bold":false},{"text":"X","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFDB00","bold":false}]}'
          - '{"text":"","extra":[{"text":"F","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF0000","bold":false},{"text":"i","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF1600","bold":false},{"text":"r","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF2C00","bold":false},{"text":"e
            ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF4200","bold":false},{"text":"A","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF5800","bold":false},{"text":"s","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF6E00","bold":false},{"text":"p","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF8300","bold":false},{"text":"e","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF9900","bold":false},{"text":"c","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFAF00","bold":false},{"text":"t
            ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFC500","bold":false},{"text":"X","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFDB00","bold":false}]}'
          - '{"text":"","extra":[{"text":"S","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF0000","bold":false},{"text":"h","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF1800","bold":false},{"text":"a","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF3100","bold":false},{"text":"r","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF4900","bold":false},{"text":"p","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF6100","bold":false},{"text":"n","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF7A00","bold":false},{"text":"e","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF9200","bold":false},{"text":"s","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFAA00","bold":false},{"text":"s
            ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFC300","bold":false},{"text":"X","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFDB00","bold":false}]}'
          - '{"text":"","extra":[{"text":"L","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF0000","bold":false},{"text":"o","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF1800","bold":false},{"text":"o","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF3100","bold":false},{"text":"t","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF4900","bold":false},{"text":"i","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF6100","bold":false},{"text":"n","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF7A00","bold":false},{"text":"g
            ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF9200","bold":false},{"text":"V","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFAA00","bold":false},{"text":"I","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFC300","bold":false},{"text":"I","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FFDB00","bold":false}]}'
          enchants:
            FIRE_ASPECT: 10
            LOOT_BONUS_MOBS: 5
            MENDING: 10
            DAMAGE_ALL: 10
            SWEEPING_EDGE: 10
            DURABILITY: 10
          ItemFlags:
          - HIDE_ENCHANTS
    planner:
      cooldown: 1
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
