### ISSUE TITLE
Potions ending in II

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2232]
### What is your Quests version / build number (do *not* say "latest")?

5.0.3-b474

### Describe the problem and how to replicate it.

Any quest that has a potion with a II (Healing II, Swiftness II, etc.) with the Consume objective will not appear. It appears when tasking to brew, but not other objective types.
![image](https://github.com/PikaMug/Quests/assets/64336395/e8ac0df8-3887-4a6d-b1ed-ff71d6f89a8e)

### Any console errors to share?

```shell
n/a
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000168':
    name: Healing Alchemist
    ask-message: '        &x&e&9&9&8&2&0&l⭐ &x&f&f&d&5&7&e&l<quest> &x&e&9&9&8&2&0&l⭐'
    finish-message: '&8&l[&x&7&6&8&b&f&5&lBOT&8&l]&r &fTake another quest with &x&f&f&d&5&7&e&l/quests&f!'
    stages:
      ordered:
        '1':
          items-to-brew:
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: POTION
            amount: 9
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:healing
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: POTION
            amount: 9
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:strong_healing
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: SPLASH_POTION
            amount: 9
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:healing
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: SPLASH_POTION
            amount: 9
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:strong_healing
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: LINGERING_POTION
            amount: 9
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:healing
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: LINGERING_POTION
            amount: 9
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:strong_healing
          start-event: 24HrTimer
        '2':
          items-to-consume:
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: POTION
            amount: 9
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:healing
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: POTION
            amount: 9
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:strong_healing
          start-event: 24HrTimer
    rewards:
      money: 15000
      quest-points: 1
      custom-rewards:
        req1:
          name: mcMMO Overhaul Skill Reward
          data:
            Skill Amount: '5'
            Skill Type: Alchemy
    planner:
      cooldown: 604800
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: false
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
