### ISSUE TITLE
Custom Named Items

### ISSUE THREAD

**Issue by NGamerW** [PikaMug/Quests#2234]
### What is your Quests version / build number (do *not* say "latest")?

5.0.4

### Describe the problem and how to replicate it.

When i save items with a custom names that should be crafted for a quest in quest, they wont get noticed when they are crafted. Like when i make a quest to craft **Dared Pickaxe** and the name is bold and gray it wont register it when its crafted.

Sometimes it works but mostly not, i dont know where the issue is so i cant replicate it by command. But i know that it doesnt work 99%.

### Any console errors to share?

```shell
no errors
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom1:
    name: 'Rylon: The Beginning'
    ask-message: Rylon
    finish-message: Well done!
    block-start: empty world 165358.0 66.0 165360.0
    stages:
      ordered:
        '1':
          break-block-names:
          - OAK_LOG
          break-block-amounts:
          - 6
          break-block-durability:
          - 0
          start-event: RunCommand
          start-message: Break 6 Oak Logs
        '2':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: WOODEN_PICKAXE
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Dared
                Pickaxe"}],"text":""}'
              lore:
              - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"Can
                Break:"}],"text":""}'
              - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"-
                Stone"}],"text":""}'
          start-message: Buy the Recipe book from the allay! &c&lDont shift-click
            items from the crafting table in your inventory!
```
