### ISSUE TITLE
repeat cycle 

### ISSUE THREAD

**Issue by BLACKGAMER1221** [PikaMug/Quests#2238]
### What is your Quests version / build number (do *not* say "latest")?

5.0.4-b475 (late release on spigot)

### Describe the problem and how to replicate it.

repeat cycle is not work 
 i have a completed quest but when i reach the repeat cycle it is still say 
 "you have already completed [quest name]" and not work 
 
 example  planner config: 
 
```
 planner:
      start: 29:5:2024:21:20:9:Etc/UTC
      end: 29:5:2024:21:50:32:Etc/UTC
      repeat: 120
      override: true
```

### Any console errors to share?

```shell
no error
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000001':
    name: §7§l§oBeginner Miner
    ask-message: §8Mine §6§l450 §8Dirt
    finish-message: Well done!
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3839
      type: IRON_PICKAXE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"text":"","extra":[{"text":"Beginner Miner","obfuscated":false,"italic":true,"underlined":false,"strikethrough":false,"color":"gray","bold":true}]}'
        lore:
        - '{"text":"","extra":[{"text":"Mine ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"dark_gray","bold":false},{"text":"450
          ","italic":false,"color":"gold","bold":true},{"text":"Dirt","italic":false,"color":"dark_gray","bold":false}]}'
        ItemFlags:
        - HIDE_ADDITIONAL_TOOLTIP
        custom: H4sIAAAAAAAA/+NiYGBmYHNJzE1MT2UAAQCogW6XEQAAAA==
    stages:
      ordered:
        '1':
          break-block-names:
          - DIRT
          break-block-amounts:
          - 450
          break-block-durability:
          - 0
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3839
        type: DIAMOND
        amount: 3
      - ==: org.bukkit.inventory.ItemStack
        v: 3839
        type: GOLDEN_APPLE
        amount: 2
      - ==: org.bukkit.inventory.ItemStack
        v: 3839
        type: COOKED_BEEF
        amount: 32
      - ==: org.bukkit.inventory.ItemStack
        v: 3839
        type: TRIPWIRE_HOOK
        amount: 2
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"text":"","extra":[{"text":"♠ ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":true},{"text":"COMMON
            KEYS ","italic":false,"color":"white","bold":true},{"text":"♠","italic":false,"color":"gray","bold":true}]}'
          enchantment-glint-override: true
          PublicBukkitValues: |-
            {
                "crazycrates:crazycrates_crate_key": "common"
            }
          custom: H4sIAAAAAAAA/+NiYOBiYE/JLC7ISazkYGDxS8xNZVhdrVSSWlGiZKX0aOYCBSUdpeT8nPwiIDe9KLESyE3Kz0lRsiopKk3VUcosSczJTFaySkvMKQZygdqKEpWsouEmOPv7+vr7KXi7RgYjm1SekVmSimYUhl6g7fgsr40FQgZOBh7XvOSMxLyS3NS8kmIuBgYGNg4GpswUIINYmgEA9A9W+wcBAAA=
    planner:
      start: 29:5:2024:21:20:9:Etc/UTC
      end: 29:5:2024:21:50:32:Etc/UTC
      repeat: 120
      override: true
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```

**Comment by PikaMug** [comment]
Try setting a player cooldown

**Comment by BLACKGAMER1221** [comment]
it work but now i have another problem 
i set block break to 1 (so i can test it with breaking only one dirt)
 and i set repeat cycle to 5 min and player cooldown to 20min and override true 
config: 
```
planner:
      start: 30:5:2024:14:1:51:Etc/UTC
      end: 30:5:2024:14:15:3:Etc/UTC
      repeat: 300
      cooldown: 1200
      override: true
```
so It should be such that when you break a dirt and complete the quest you shouldn't be able to retake the quest before the repeat cycle reached.
 but i can take infinite amount of quest without any cooldown
