### ISSUE TITLE
1 of X amount of items is already crafted/delivered on quest start

### ISSUE THREAD

**Issue by StKillReal** [PikaMug/Quests#2240]
### What is your Quests version / build number (do *not* say "latest")?

![image](https://github.com/PikaMug/Quests/assets/60330193/bb1bde49-9a27-47c2-a2b2-f4eda21ebe9c)

### Describe the problem and how to replicate it.

For example, I created a quest where I need to bring two stacks of iron bars to NPC, but when I start it, I see 2 of 128 is already bringed.
![image](https://github.com/PikaMug/Quests/assets/60330193/ced4702b-9c06-432a-9598-29ae8b42441e)

Example №2 - I need to craft 2 anvils, but because of this bug I can't complete the task, cause it shows that I've already crafted it. When I actually craft them, nothing happening.
![image](https://github.com/PikaMug/Quests/assets/60330193/ea57f058-d1ad-4e8c-8bbc-1d6d2f713226)

### Any console errors to share?

```shell
No errors on quest start or task complete
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom8:
    name: anvils
    ask-message: bring 2 anvils
    finish-message: Thanks!
    npc-giver-uuid: e0a98829-cf96-4ea0-9c6e-c14d3a9684f2
    stages:
       ordered:
        '1':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: ANVIL
            amount: 1
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: ANVIL
            amount: 1
          complete-message: Let's bring it!
        '2':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: ANVIL
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: ANVIL
          npc-delivery-uuids:
          - e0a98829-cf96-4ea0-9c6e-c14d3a9684f2
          - e0a98829-cf96-4ea0-9c6e-c14d3a9684f2
          delivery-messages:
          - I need 2 anvils
    rewards:
      money: 300
      quest-points: 1
    planner:
      cooldown: 86400
```
