### ISSUE TITLE
Still Repeat Cycle

### ISSUE THREAD

**Issue by BLACKGAMER1221** [PikaMug/Quests#2244]
### What is your Quests version / build number (do *not* say "latest")?

5.0.4-b475

### Describe the problem and how to replicate it.

repeat cycle is still not work  and i can take infinite amount of quest without cooldown. 
i asked it on discord but your admin (Deadlykill) said ask on github 

![sdcwcvadbnqf](https://github.com/PikaMug/Quests/assets/76135089/739cf01b-13fa-4285-bde0-33cd67025e0b)

config: 
```
planner:
      start: 1:6:2024:0:1:0:Etc/UTC
      end: 1:6:2024:23:59:0:Etc/UTC
      repeat: 86400
      cooldown: 86300
      override: true
```
Video: 

https://github.com/PikaMug/Quests/assets/76135089/3bbc8508-c5c0-4ac5-bda7-e15a048fbea6

if you can't play video in github: 

https://mega.nz/file/I9Jx3IKY#2hEP9-niFAOZDIhbO-IpuHpTe7rxuZu2GXqHwp8rmO4

### Any console errors to share?

```shell
no error
```
