### ISSUE TITLE
Crafting quests when inventory is full

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2245]
### What is your Quests version / build number (do *not* say "latest")?

5.0.5-b480

### Describe the problem and how to replicate it.

Make any crafting quest that makes more then 1 item of any type. Fill up your inventory with any random junk to occupy space, and then shift+click to craft. Regardless if the materials are actually used and the item is actually crafted, it will mark the quest as complete. Video attached if I didn't describe it well. Harder crafting quests (like crafting beacons) can more or less be bypassed without spending materials.

https://github.com/PikaMug/Quests/assets/64336395/35754d09-06d3-4f32-9737-a279df7f7b38

### Any console errors to share?

```shell
n/a
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'9999':
    name: Test Crafting
    ask-message: '        &x&e&9&9&8&2&0&l⭐ &x&f&f&d&5&7&e&l<quest> &x&e&9&9&8&2&0&l⭐'
    finish-message: §8§l[§x§7§6§8§b§f§5§lBOT§8§l]§r §fTake another quest with §x§f§f§d§5§7§e§l/quests§f!
    stages:
      ordered:
        '1':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: MUSHROOM_STEW
            amount: 64
```
