### ISSUE TITLE
Can't continue quests when I need to bring item with custom name and lore

### ISSUE THREAD

**Issue by StKillReal** [PikaMug/Quests#2250]
### What is your Quests version / build number (do *not* say "latest")?

![image](https://github.com/user-attachments/assets/b78d6397-135e-4ed7-879e-a03cad320e0f)

### Describe the problem and how to replicate it.

I have a quest with 3 stanges. First and second stages about finfing locations and in third I need to bring some items to NPC. When I complete second stage nothing happen. Even if u use /quest command I just see an error in chat and console.
+ error on second stage complete
![image](https://github.com/user-attachments/assets/fbf45ead-fd59-444b-aaef-a5f335031c06)

+ error on questsadmin reset command
![image](https://github.com/user-attachments/assets/6a908ab7-fa9b-4001-8393-1695e659c8e1)

+ error on questadmin nextage command
![image](https://github.com/user-attachments/assets/955a482c-da25-4d44-afdd-10a6b727fea9)

### Any console errors to share?

```shell
In description
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom27:
    name: name
    ask-message: text
    npc-giver-uuid: db08d0df-1083-497e-a243-defdc26269a8
    stages:
      ordered:
        '1':
          locations-to-reach:
          - world 299.0 59.0 -18.0
          reach-location-radii:
          - 5
          reach-location-names:
          - Глубь пещеры
          complete-message: text
        '2':
          locations-to-reach:
          - world 282.0 57.0 -20.0
          reach-location-radii:
          - 5
          reach-location-names:
          - Пещера
          complete-message: text
        '3':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: REINFORCED_DEEPSLATE
            amount: 2
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              display-name: '{"text":"","extra":["Часть древних ворот"]}'
              lore:
              - '{"text":"","extra":["Часть древних ворот, разрушеннных несколько
                веков назад"]}'
          npc-delivery-uuids:
          - db08d0df-1083-497e-a243-defdc26269a8
          delivery-messages:
          - Мне необходимо 2 части, а тут только одна
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3953
        type: NETHERITE_HELMET
        meta:
          ==: ItemMeta
          meta-type: ARMOR
          display-name: '{"text":"","extra":[{"text":"Незеритовый шлем от незнакомца","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"light_purple","bold":false}]}'
          lore:
          - '{"text":"","extra":[{"text":"Награда за прохождение квеста","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"light_purple","bold":false}]}'
          - '{"text":"","extra":[{"text":"Поиск сквозь века","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"light_purple","bold":false}]}'
          enchants:
            minecraft:respiration: 10
          repair-cost: 7
      quest-points: 1
      commands:
      - bc Игрок <player> прошел квест "Опасное местечко" от незнакомца из пещеры
      details-override:
      - '&dНезеритовый шлем от незнакомца'
      - '&f1 &aQкоин'
    planner:
      cooldown: 1209600
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
