### ISSUE TITLE
Use placeholder for player name doesn't work

### ISSUE THREAD

**Issue by Galen3** [PikaMug/Quests#2255]
### What is your Quests version / build number (do *not* say "latest")?

Quests 5.0.1-b454

### Describe the problem and how to replicate it.

I need to execute a command to give an item to a user and many placeholders doesn't work like: %player_name% %name% <player> etc.. please help :(

### Any console errors to share?

```shell
Shows the placeholder instead the name of the user
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Actions

test_potion:
    commands:
    - ei give %player_name% white_potion 1
```
