### ISSUE TITLE
When crafting Items, unable to craft anything when quest starts. Only when it ends.

### ISSUE THREAD

**Issue by Reflect-good** [PikaMug/Quests#2257]
### What is your Quests version / build number (do *not* say "latest")?

5.0.6-b491

### Describe the problem and how to replicate it.

A quest is given to craft 8 flint and steels, after quest starts, they are unable to craft anything.

### Any console errors to share?

```shell
only this: java.lang.NullPointerException: null
after they try and craft an item.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
quests:
  '000001':
    name: obsidian
    ask-message: Challenge objectives!
    finish-message: Well done!
    npc-giver-uuid: 4722279f-a2a4-49c1-b3c7-187507c6055a
    stages:
      ordered:
        '1':
          break-block-names:
          - OBSIDIAN
          break-block-amounts:
          - 192
          break-block-durability:
          - 0
        '2':
          break-block-names:
          - CRYING_OBSIDIAN
          break-block-amounts:
          - 16
          break-block-durability:
          - 0
        '3':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: FLINT_AND_STEEL
            amount: 8
        '4':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: CONDUIT
        '5':
          break-block-names:
          - TORCHFLOWER
          break-block-amounts:
          - 1
          break-block-durability:
          - 0
    rewards:
      permissions:
      - nether.portal
      - multiverse.portal.access.nether
      - multiverse.portal.access.portal
      permission-worlds: []
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
