### ISSUE TITLE
Duplicate objective on 1.21

### ISSUE THREAD

**Issue by Reflect-good** [PikaMug/Quests#2262]
### What is your Quests version / build number (do *not* say "latest")?

5.0.6-b493

### Describe the problem and how to replicate it.

![image](https://github.com/user-attachments/assets/ce87cd34-76d7-4d4f-81c9-bf273c7bc46b)
When delivering items to NPCs, it sometimes bugs out and duplicates the item or goes negative, not sure what causes this, just been hearing it from my players.

### Any console errors to share?

```shell
Nothing shows up in console.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
quests:
  '000001':
    name: Nether
    ask-message: Challenge objectives!
    finish-message: Well done!
    npc-giver-uuid: f2513580-9294-4f69-a4b5-59d1f5e7cf34
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: OBSIDIAN
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: OBSIDIAN
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: OBSIDIAN
            amount: 64
          npc-delivery-uuids:
          - f2513580-9294-4f69-a4b5-59d1f5e7cf34
          - f2513580-9294-4f69-a4b5-59d1f5e7cf34
          - f2513580-9294-4f69-a4b5-59d1f5e7cf34
          delivery-messages:
          - Thank you. Only §5<amount> §rmore to go!
          - Thank you. Only §5<amount> §rmore to go!
          - Thank you. Only §5<amount> §rmore to go!
        '2':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: SOUL_SAND
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: SOUL_SAND
            amount: 64
          npc-delivery-uuids:
          - f2513580-9294-4f69-a4b5-59d1f5e7cf34
          - f2513580-9294-4f69-a4b5-59d1f5e7cf34
          delivery-messages:
          - Thank you. Only §5<amount> §rmore to go!
        '3':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: FLINT_AND_STEEL
            amount: 8
          npc-delivery-uuids:
          - f2513580-9294-4f69-a4b5-59d1f5e7cf34
          delivery-messages:
          - Thank you. Only §5<amount> §rmore to go!
        '4':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: CONDUIT
          npc-delivery-uuids:
          - f2513580-9294-4f69-a4b5-59d1f5e7cf34
          delivery-messages:
          - Thank you. Only §5<amount> §rmore to go!
        '5':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: TORCHFLOWER
          npc-delivery-uuids:
          - f2513580-9294-4f69-a4b5-59d1f5e7cf34
          delivery-messages:
          - Thank you. Only §5<amount> §rmore to go!
    rewards:
      permissions:
      - multiverse.portal.access.nether
      - multiverse.portal.access.portal
      - nether.portal
      permission-worlds: []
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
