### ISSUE TITLE
Update on Null upon crafting with almost full inventory

### ISSUE THREAD

**Issue by Reflect-good** [PikaMug/Quests#2268]
### What is your Quests version / build number (do *not* say "latest")?

5.0.6-b493

### Describe the problem and how to replicate it.

I know I’ve reported this before, but I came back with an update, it seems as if you have 3 missing slots from your inventory it sees it was the players inventory is full, but when 4 slots are open, it acts normal as if your inventory was never full.

https://github.com/user-attachments/assets/b4dd3e0a-c1dd-42b5-a544-89f0879c6808

### Any console errors to share?

```shell
None, just a NULL on action bar
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'4':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: CONDUIT
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: CONDUIT
          npc-delivery-uuids:
          - f2513580-9294-4f69-a4b5-59d1f5e7cf34
          delivery-messages:
          - Thank you. Only §5<amount> §rmore to go!
        '5':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: TORCHFLOWER
          npc-delivery-uuids:
          - f2513580-9294-4f69-a4b5-59d1f5e7cf34
          delivery-messages:
          - Thank you. Only §5<amount> §rmore to go!
    rewards:
      permissions:
      - multiverse.portal.access.nether
      - multiverse.portal.access.portal
      - nether.portal
      permission-worlds: []
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
