### ISSUE TITLE
Crops don't respect age

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2271]
### What is your Quests version / build number (do *not* say "latest")?

5.1.0-b495

### Describe the problem and how to replicate it.

Any quest involving aging crops. Carrots, potatoes, beetroot, nether wart, etc making all quests needing this easily abusable

### Any console errors to share?

```shell
n/a
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000016':
    name: Carrots Go Brrr # Tested
    ask-message: Finish <quest>
    finish-message: '&8&l[&x&7&6&8&b&f&5&lBOT&8&l]&r &fTake another quest with &x&f&f&d&5&7&e&l/quests&f!'
    stages:
      ordered:
        '1':
          break-block-names:
          - CARROTS
          - POTATOES
          - BEETROOTS
          break-block-amounts:
          - 320
          - 320
          - 320
          break-block-durability:
          - 7
          - 7
          - 3
    rewards:
      money: 15000
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-parties-plugin: false
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: false
```
