### ISSUE TITLE
McMMO Skill Rewards still allowing above max level

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2272]
### What is your Quests version / build number (do *not* say "latest")?

5.1.1-b496

### Describe the problem and how to replicate it.

Any quest that gives mcmmo levels will always give them, even if the player is already at level cap. Opened before under #2226 but was unable to test previously.

### Any console errors to share?

```shell
n/a
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000010':
    name: The Great Potato War I
    ask-message: '        &x&e&9&9&8&2&0&l⭐ &x&f&f&d&5&7&e&l<quest> &x&e&9&9&8&2&0&l⭐'
    finish-message: §8§l[§x§7§6§8§b§f§5§lBOT§8§l]§r §fTake another quest with §x§f§f§d§5§7§e§l/quests§f!
    stages:
      ordered:
        '1':
          break-block-names:
          - POTATOES
          break-block-amounts:
          - 128
          break-block-durability:
          - 7
          start-event: 24HrTimer
    rewards:
      money: 15000
      quest-points: 1
      custom-rewards:
        req1:
          name: mcMMO Overhaul Skill Reward
          data:
            Skill Amount: '10'
            Skill Type: Herbalism
    planner:
      cooldown: 1209600
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-parties-plugin: false
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: false
```
