### ISSUE TITLE
Multi Block Break Quests auto-complete

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2274]
### What is your Quests version / build number (do *not* say "latest")?

5.1.1-b496

### Describe the problem and how to replicate it.

It seems any (or perhaps most) quests that ask you to break several blocks (Oak Log & Birch Logs) will complete as soon as any one of them is completed. So if the quest requires you break 64 Dirt and 64 Stone, it will complete by you just breaking 64 dirt.

### Any console errors to share?

```shell
n/a
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000091':
    name: Lvl 99 Mining # Tested
    ask-message: '        &x&e&9&9&8&2&0&l⭐ &x&f&f&d&5&7&e&l<quest> &x&e&9&9&8&2&0&l⭐'
    finish-message: '&8&l[&x&7&6&8&b&f&5&lBOT&8&l]&r &fTake another quest with &x&f&f&d&5&7&e&l/quests&f!'
    stages:
      ordered:
        '1':
          break-block-names:
          - COAL_ORE
          - DEEPSLATE_COAL_ORE
          - IRON_ORE
          - DEEPSLATE_IRON_ORE
          - COPPER_ORE
          - DEEPSLATE_COPPER_ORE
          - GOLD_ORE
          - DEEPSLATE_GOLD_ORE
          - REDSTONE_ORE
          - DEEPSLATE_REDSTONE_ORE
          - LAPIS_ORE
          - DEEPSLATE_LAPIS_ORE
          - DIAMOND_ORE
          - DEEPSLATE_DIAMOND_ORE
          - NETHER_GOLD_ORE
          - NETHER_QUARTZ_ORE
          break-block-amounts:
          - 64
          - 64
          - 64
          - 64
          - 64
          - 64
          - 64
          - 64
          - 64
          - 64
          - 64
          - 64
          - 64
          - 64
          - 64
          - 64
          break-block-durability:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          start-event: 24HrTimer
    rewards:
      commands:
      - cr give to <player> McMMOToken15 1
      money: 50000
      quest-points: 1
      details-override:
      - '&x&3&1&f&7&6&6$50,000 & 1x &2&l15 Minute McMMO Token'
    planner:
      cooldown: 604800
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-parties-plugin: false
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
