### ISSUE TITLE
items duplication 

### ISSUE THREAD

**Issue by StKillReal** [PikaMug/Quests#2278]
### What is your Quests version / build number (do *not* say "latest")?

![image](https://github.com/user-attachments/assets/f8739e43-10ea-4165-a4aa-bf05ee7411d4)

### Describe the problem and how to replicate it.

I have a quests which in I need to bring 10 stacks of hay blocks to NPC. When I bring not 64 blocks, but less, like 25 or somthing, blocks starts to double in my inventory each click
![image](https://github.com/user-attachments/assets/63194b0f-1711-4533-9276-e29cd7c3a029)

### Any console errors to share?

```shell
no errors
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000003':
    name: Выгодное предложение
    ask-message: У меня тут какой-то дефицит сена, поскольку все несут его в скупщик,
      включая этого чертового фермера! Так уж и быть, я готов заплатить 6000$ за 10
      стаков сена. Как тебе предложение?
    finish-message: Неужели! Я думаю на неделю этого точно хватит, а там уже можешь
      приходить снова. Плачу столько же и за тот же объем
    npc-giver-uuid: 248a22c8-5113-4e69-b640-f0f2a8e44a1c
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: HAY_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: HAY_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: HAY_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: HAY_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: HAY_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: HAY_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: HAY_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: HAY_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: HAY_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: HAY_BLOCK
            amount: 64
          npc-delivery-uuids:
          - 248a22c8-5113-4e69-b640-f0f2a8e44a1c
          - 248a22c8-5113-4e69-b640-f0f2a8e44a1c
          - 248a22c8-5113-4e69-b640-f0f2a8e44a1c
          - 248a22c8-5113-4e69-b640-f0f2a8e44a1c
          - 248a22c8-5113-4e69-b640-f0f2a8e44a1c
          - 248a22c8-5113-4e69-b640-f0f2a8e44a1c
          - 248a22c8-5113-4e69-b640-f0f2a8e44a1c
          - 248a22c8-5113-4e69-b640-f0f2a8e44a1c
          - 248a22c8-5113-4e69-b640-f0f2a8e44a1c
          - 248a22c8-5113-4e69-b640-f0f2a8e44a1c
          delivery-messages:
          - Мне нужно 10 стаков
          - Мне нужно 10 стаков
          - Мне нужно 10 стаков
          - Мне нужно 10 стаков
          - Мне нужно 10 стаков
          - Мне нужно 10 стаков
          - Мне нужно 10 стаков
          - Мне нужно 10 стаков
          - Мне нужно 10 стаков
          - Мне нужно 10 стаков
    rewards:
      money: 6000
      quest-points: 1
    planner:
      cooldown: 604800
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
