### ISSUE TITLE
Quests not progressing past 64 when using furnace 

### ISSUE THREAD

**Issue by UrGirlLady** [PikaMug/Quests#2282]
### What is your Quests version / build number (do *not* say "latest")?

5.1.2-b${env.BUILD_NUMBER}

### Describe the problem and how to replicate it.

![image](https://github.com/user-attachments/assets/b9fc40fc-52fe-41d7-a18c-8f4a293284ad)
Quests are not progressing past 64 out of X amount when using a furnace 

Whether its smelting ores or baking potatoes the quest wont count past 64. 
![Screenshot 2024-08-22 094236](https://github.com/user-attachments/assets/87a9648a-dd0e-4da2-8683-46264578358e)
![Screenshot 2024-08-22 095757](https://github.com/user-attachments/assets/99489bc6-6400-48ce-9d80-84f241e86618)

### Any console errors to share?

```shell
NA
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000175':
    name: '&6Easy Iron Challenge'
    ask-message: '&7Smelt 7,560 Raw Iron'
    finish-message: Iron Challenge I Completed!
    npc-giver-uuid: 9c7d7ec6-98af-4504-a9ae-e3331a284b73
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3700
      type: IRON_INGOT
    stages:
      ordered:
        '1':
          items-to-smelt:
          - ==: org.bukkit.inventory.ItemStack
            v: 3700
            type: IRON_INGOT
            amount: 7560
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3700
        type: PAPER
        amount: 2
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"text":"","extra":[{"text":"O","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#4498DB","bold":false},{"text":"b","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#4A94DC","bold":false},{"text":"s","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#5090DD","bold":false},{"text":"c","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#568DDE","bold":false},{"text":"u","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#5C89DE","bold":false},{"text":"r","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#6285DF","bold":false},{"text":"e","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#6881E0","bold":false},{"text":"
            ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#6E7EE1","bold":false},{"text":"R","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#747AE2","bold":false},{"text":"e","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#7A76E3","bold":false},{"text":"m","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#8072E4","bold":false},{"text":"n","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#866EE4","bold":false},{"text":"a","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#8C6BE5","bold":false},{"text":"n","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#9267E6","bold":false},{"text":"t","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#9863E7","bold":false}]}'
          lore:
          - '{"text":"","extra":[{"text":"» ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#6F737D","bold":false},{"text":"Trade
            Obscure Remnant''s With S.A.M","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#D5D6D8","bold":false}]}'
          custom-model-data: 12441251
          PublicBukkitValues: |-
            {
                "oraxen:id": "fragment",
                "oraxen:original_name": "§x§4§4§9§8§D§BO§x§4§A§9§4§D§Cb§x§5§0§9§0§D§Ds§x§5§6§8§D§D§Ec§x§5§C§8§9§D§Eu§x§6§2§8§5§D§Fr§x§6§8§8§1§E§0e§x§6§E§7§E§E§1 §x§7§4§7§A§E§2R§x§7§A§7§6§E§3e§x§8§0§7§2§E§4m§x§8§6§6§E§E§4n§x§8§C§6§B§E§5a§x§9§2§6§7§E§6n§x§9§8§6§3§E§7t"
            }
      money: 20000
      quest-points: 1
      exp: 5400
```
