### ISSUE TITLE
Quest - Bug Issue with Silk Touch

### ISSUE THREAD

**Issue by AccioAce** [PikaMug/Quests#2296]
### What is your Quests version / build number (do *not* say "latest")?

It seems like there a bug with silktouch and also the message keeps popping up when silk touch is set to ignore via on quest configuration. Basically also silk touch makes it so quests don't register that you broke a block. Here is a screenshot of the the message which shouldn't be there either - https://prnt.sc/87yRs1_X8ZAD

**I am using Pufferfish 1.21.1 and Quests version 5.1.3-b503**

### Describe the problem and how to replicate it.

Silk touch enchantment on pickaxe then mining or breaking a block.

### Any console errors to share?

```shell
No console error
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
# For non-English characters, this file MUST stay encoded in UTF-8
quests:
  '000001':
    name: FAIRY2024
    ask-message: Challenge objectives!
    finish-message: Well done!
    stages:
      ordered:
        '1':
          break-block-names:
          - DEEPSLATE
          - END_STONE
          - DIORITE
          - ANDESITE
          - BOOKSHELF
          break-block-amounts:
          - 1600
          - 3200
          - 1600
          - 1600
          - 1000
          break-block-durability:
          - 0
          - 0
          - 0
          - 0
          - 0
          place-block-names:
          - GRAVEL
          - SAND
          place-block-amounts:
          - 1600
          - 1600
          place-block-durability:
          - 0
          - 0
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: IRON_AXE
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: IRON_AXE
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: IRON_AXE
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: IRON_AXE
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: IRON_AXE
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: IRON_AXE
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: IRON_AXE
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: IRON_AXE
            amount: 64
          cows-to-milk: 2000
          mobs-to-kill:
          - Witch
          - Wither Skeleton
          - Creeper
          - Shulker
          - Zombie
          mob-amounts:
          - 1600
          - 1600
          - 1600
          - 1600
          - 1600
          sheep-to-shear:
          - White
          - Orange
          - Magenta
          - LightBlue
          - Yellow
          - Lime
          - Pink
          - Gray
          - LightGray
          - Cyan
          - Purple
          - Blue
          - Brown
          - Green
          - Red
          - Black
          sheep-amounts:
          - 125
          - 125
          - 125
          - 125
          - 125
          - 125
          - 125
          - 125
          - 125
          - 125
          - 125
          - 125
          - 125
          - 125
          - 125
          - 125
    rewards:
      commands:
      - crate key <player> test
      - crate key <player> test
      details-override:
      - '&b2x Fairy 2024 Keys and 2x Cherry 2024 Keys'
    planner:
      end: 1:10:2024:12:59:59:UTC
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
