### ISSUE TITLE
Quests 5.1.5-b509 no information on the number of tasks performed

### ISSUE THREAD

**Issue by danyadanya2005** [PikaMug/Quests#2305]
### What is your Quests version / build number (do *not* say "latest")?

Quests 5.1.5-b509
Purpur version 1.21.1-2298-ver/1.21.1@a61db94 (2024-08-25T23:16:43Z) 

### Describe the problem and how to replicate it.

the problem(on versions 1.21) is that in the event log and when you take the quest it doesn't say what mob to kill, what block to break, and in what quantity
on the screenshots in the tasks there is just one word kill. it should say who to kill first and in what quantity

![5mDb_bAdgSQ](https://github.com/user-attachments/assets/186fbd7a-660c-4c26-9281-626a61173870)
![ekYOX5GLRFw](https://github.com/user-attachments/assets/d676e27f-7dc2-4552-bc46-152d5d8a4da9)

please note that there are no such problems on versions 1.20.+
there it is clearly written who to kill, what to break, collect and in what quantity

### Any console errors to share?

```shell
no
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
# For non-English characters, this file MUST stay encoded in UTF-8
quests:
  custom1:
    name: Охотник на монстров
    ask-message: Необходимо убить Зомби, Скелетов, Пауков и Эндерменов в указанном
      количестве
    finish-message: Отлично сработано!
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 500
          start-event: Провал
        '2':
          mobs-to-kill:
          - Skeleton
          mob-amounts:
          - 500
          start-event: Провал
        '3':
          mobs-to-kill:
          - Spider
          mob-amounts:
          - 500
          start-event: Провал
        '4':
          mobs-to-kill:
          - Enderman
          mob-amounts:
          - 500
          start-event: Провал
    rewards:
      items:
      - name-DIAMOND:amount-10
      # - ==: org.bukkit.inventory.ItemStack
      # v: 2584
      # type: SLIME_BALL
      # meta:
      # ==: ItemMeta
      # meta-type: UNSPECIFIC
      # display-name: §2Бонусная Монета
      # lore:
      # - §eУровень§7
      # - ' §2Необычный'
      # - §3Монета для покупки Сумочки с Ресурсами
      money: 10000
      quest-points: 1
    # commands:
    # - givebox <player> 9985 1
    planner:
      # cooldown: 72000
      repeat: 86400
      cooldown: 32400
      # cooldown: 86400
      override: true
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```
