### ISSUE TITLE
Start-message does not appear in /quest

### ISSUE THREAD

**Issue by Dragsio** [PikaMug/Quests#2306]
### What is your Quests version / build number (do *not* say "latest")?

5.1.4

### Describe the problem and how to replicate it.

When the player has an open quest and later enters `/quest` to find out what his task is, only what he has to bring will be shown, but the text of the task (start-message) will not be displayed.

### Any console errors to share?

```shell
no errors
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom2:
    name: Test
    ask-message: Welcome
    finish-message: Its done
    npc-giver-uuid: e150443d-d1fa-44fb-a88c-53f55e69016c
    requirements:
      quests:
      - custom1
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: COAL
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: CHARCOAL
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: FURNACE
            amount: 8
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: TORCH
            amount: 32
          npc-delivery-uuids:
          - e150443d-d1fa-44fb-a88c-53f55e69016c
          - e150443d-d1fa-44fb-a88c-53f55e69016c
          - e150443d-d1fa-44fb-a88c-53f55e69016c
          - e150443d-d1fa-44fb-a88c-53f55e69016c
          delivery-messages:
          - Thanks.
          - Thanks.
          - Thanks.
          - Thanks.
          start-message: Give me 64x coal, 64x charcoal, 8x furnace, 32x torch
          complete-message: Thank you.
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3955
        type: WOODEN_PICKAXE
      - ==: org.bukkit.inventory.ItemStack
        v: 3955
        type: TNT
      - ==: org.bukkit.inventory.ItemStack
        v: 3955
        type: TORCH
        amount: 4
      money: 50
      quest-points: 1
      commands:
      - clv addExp 20 <player>
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
