### ISSUE TITLE
Quests Data will not reset

### ISSUE THREAD

**Issue by Drizzt11** [PikaMug/Quests#2308]
### What is your Quests version / build number (do *not* say "latest")?

5.1.4

### Describe the problem and how to replicate it.

Quests data will not reset when using either /questsadmin reset or /questsadmin remove.

### Any console errors to share?

```shell
No errors pop up in the console
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000047':
    name: Quartermaster - Friendly
    ask-message: 'Greetings friend! Now that you have earned your reputation, go back
      to the Town Hall and report to the Town Mayor of your deeds to unlock friendly
      status with the vendor. **Reached 30 Quest Points. Report to the Town Mayor.
      Rewards: 100XP**'
    finish-message: Well done hero. Check out the reputation vendor. There are some
      items available now.
    npc-giver-uuid: a9a6e079-5f99-40e5-9d2f-65ca9689c61e
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3955
      type: BOOK
    requirements:
      quest-points: 30
    stages:
      ordered:
        '1':
          npc-uuids-to-talk-to:
          - e7d3d3f0-4b03-4e78-98b8-98e3f430b186
          start-message: '&bReport to the &aTown Mayor&b at the &cTown Hall &bin &cWest
            Side Windria&b.'
    rewards:
      exp: 100
      permissions:
      - reputation.friendly
      permission-worlds: []
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
