### ISSUE TITLE
Placeholder not work

### ISSUE THREAD

**Issue by Ednaph** [PikaMug/Quests#2310]
### What is your Quests version / build number (do *not* say "latest")?

5.1.0-b495

### Describe the problem and how to replicate it.

The Placeholder {player} does not work on quest reward commands. Plugin says player not found.
I tried to give myself a stone with the placeholder: player not found and when I put my nickname it works

### Any console errors to share?

```shell
[17:45:22 INFO]: Joueur introuvable.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000069':
    name: Convertisseur de points
    ask-message: Défiez des objectifs !
    finish-message: Bien joué !
    npc-giver-uuid: 031d8ff3-c3d4-4e5c-a1f7-87fccf9a45c2
    requirements:
      quest-points: 40
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: GOLDEN_APPLE
          npc-delivery-uuids:
          - 031d8ff3-c3d4-4e5c-a1f7-87fccf9a45c2
          delivery-messages:
          - Merci. Seulement <amount> de plus à y aller!
          start-message: Apportez une pomme doré à Lydus pour convertir 40 points
            de quête en 145.000 skydollars
    rewards:
      money: 145000
      commands:
      - questadmin takepoints {player} 40
    planner:
      cooldown: 1
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
