### ISSUE TITLE
Craft items with custom names

### ISSUE THREAD

**Issue by S4r3ss** [PikaMug/Quests#2313]
### What does your feature do?

Plugin can't detect when user is crafting custom item, configured using plugin Oraxen

Item could have custom name with colors and lore

If it is already exist, please let me know how to configure it. My item data is

```
needle:
  itemname: <yellow>Голка
  material: PAPER
  lore:
  - <yellow>Використовуйте даний предмет для крафту теплої броні
  Pack:
    generate_model: true
    parent_model: item/generated
    textures:
    - default/needle.png
    custom_model_data: 1026
```
There are how I was trying to catch it, using your plugin
```
'000001':
    name: Зимовий мор
    ask-message: Challenge objectives!
    finish-message: Well done!
    npc-giver-uuid: 2c53e5fc-028f-4092-9b82-fa3f6411b1eb
    stages:
      ordered:
        '1':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 3953
            type: PAPER
            amount: 4
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              display-name: '{"text":"","extra":["§eГолка"]}'
              lore:
              - '{"text":"","extra":[{"text":"Використовуйте даний предмет для крафту
                теплої броні","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"yellow","bold":false}]}'
```

### How would people use it?

From my perspective, it will allow people to use custom crafts, created by other plugins (like in my case) or using datapacks (also could be implemented in this way)
