### ISSUE TITLE
Chorus flowers are not counted when you break them

### ISSUE THREAD

**Issue by StKillReal** [PikaMug/Quests#2316]
### What is your Quests version / build number (do *not* say "latest")?

![image](https://github.com/user-attachments/assets/16ec2f6b-91e5-43d5-bee7-41ec6c0a5be2)
![image](https://github.com/user-attachments/assets/969cc3e5-df1d-4ff9-9e7e-e85c74215801)

### Describe the problem and how to replicate it.

Create a quest in which you need to break chorus flowers. However, when you do it, the flowers will not be counted when you break them

### Any console errors to share?

```shell
Nope
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000015':
    name: name
    ask-message: text
    finish-message: text
    npc-giver-uuid: 60dabead-4bba-47d7-8ce9-1e0b6b5ed7a5
    requirements:
      quests:
      - '000014'
    stages:
      ordered:
        '1':
          break-block-names:
          - CHORUS_FLOWER
          break-block-amounts:
          - 64
          break-block-durability:
          - 0
          damage-block-durability: []
        '2':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 4189
            type: CHORUS_FLOWER
            amount: 64
          npc-delivery-uuids:
          - 60dabead-4bba-47d7-8ce9-1e0b6b5ed7a5
          delivery-messages:
          - text
    rewards:
      money: 1000
      quest-points: 1
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
