### ISSUE TITLE
Weird user data lost

### ISSUE THREAD

**Issue by Dragsio** [PikaMug/Quests#2324]
### What is your Quests version / build number (do *not* say "latest")?

5.1.6-b523

### Describe the problem and how to replicate it.

Hi, yesterday the players lost their progress and completed quests. Today I'm trying to fix it and I found out that everything is fine in mysql but in the game it tells the players that they don't have completed quests.

When the server starts, no one has completed quests, then I run the command /qconvert playerdata MySQL YAML and the completed quests are working, but when I restart the server, the players don't have completed quests again.

I also have a database backup but it still doesn't work.

Any ideas on how to fix it?

**Comment by PikaMug** [comment]
Sounds like #2201 

What are the `pool-settings` and `storage-method` in your _config.yml_ file set to while the issue occurs? For reference, here's the default:

```yaml
storage-data:
  ...
  pool-settings:
    max-pool-size: 10
    min-idle: 10
    max-lifetime: 1800000
    keepalive-time: 0
    connection-timeout: 5000
    properties:
      useUnicode: true
      characterEncoding: utf8
storage-method:
  player-data: yaml
```

**Comment by Dragsio** [comment]
My entire _config.yml_:

```yaml
prevent-exploit: true
accept-timeout: 20
allow-command-questing: true
allow-command-quests-with-npcs: false
allow-pranks: false
clickable-prompts: true
condition-interval: 10
confirm-abandon: true
confirm-accept: true
console-logging: 2
disable-command-feedback: false
generate-files-on-join: true
give-journal-item: false
ignore-locked-quests: false
kill-delay: 600
language: en-US
language-override-client: false
max-quests: 0
npc-effects:
  enabled: true
  new-quest: note
  redo-quest: heart
show-completed-objectives: true
show-requirements: true
show-titles: true
storage-data:
  address: localhost
  database: minecraft
  username: minecraft
  password: ************
  table_prefix: quests_
  pool-settings:
    max-pool-size: 10
    min-idle: 10
    max-lifetime: 1800000
    keepalive-time: 0
    connection-timeout: 5000
    properties:
      useUnicode: true
      characterEncoding: utf8
storage-method:
  player-data: MySQL
strict-player-movement: 0
top-limit: 150
trial-save: false
translate-names: true
translate-subcommands: false
update-check: false
```
