### ISSUE TITLE
NPCs set up in delivery quests do not work after server restart.

### ISSUE THREAD

**Issue by Tsuyu-Rain** [PikaMug/Quests#2326]
### What is your Quests version / build number (do *not* say "latest")?

Quests-5.1.6

### Describe the problem and how to replicate it.

When I restart the server, I cannot deliver anything to the NPC I set as the delivery destination  when I right-click with an item. If server is not restarted, it will work normally.

### Any console errors to share?

```shell
no error
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000001':
    name: 【日課】オークの原木10個の納品
    ask-message: オークの原木を10個納品してください。
    finish-message: クエスト完了です！
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3839
            type: OAK_LOG
            amount: 10
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              attribute-modifiers:
                minecraft:generic.attack_damage:
                - ==: org.bukkit.attribute.AttributeModifier
                  amount: 0.0
                  name: foo
                  uuid: 52560d48-96b5-4ff4-8590-f00517453960
                  operation: 2
                - ==: org.bukkit.attribute.AttributeModifier
                  amount: 0.0
                  name: foo
                  uuid: d7f7ae5f-1df1-42a3-bac8-f7883271bdde
                  operation: 2
                - ==: org.bukkit.attribute.AttributeModifier
                  amount: 0.0
                  name: foo
                  uuid: fc8d3f2e-9eed-4d8f-9e67-1b3a13d27113
                  operation: 2
              ItemFlags:
              - HIDE_ATTRIBUTES
              - HIDE_ADDITIONAL_TOOLTIP
          npc-delivery-uuids:
          - 76818d66-4c2d-4b52-91e0-e3d2144f8cd4
          delivery-messages:
          - §rありがとうございます。あと <amount> 回だけです！
    rewards:
      money: 500
      quest-points: 10
    planner:
      cooldown: 10800
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
