### ISSUE TITLE
Mob kill tasks won't trigger in 5.2.0

### ISSUE THREAD

**Issue by EpicKnarvik97** [PikaMug/Quests#2330]
### What is your Quests version / build number (do *not* say "latest")?

5.2.0-b526

### Describe the problem and how to replicate it.

In version 5.2.0, any quest that includes killing a mob won't trigger new kills. The number of killed mobs stays the same in the overviews produced by `/quest` and `/quests journal` no matter how many enemies of the required type are killed. This behavior is consistent between resticted area quests, and quests with no kill region restriction. Killing the specified number of mobs does not finish the quest.

I found both previously accepted quests and quests accepted after the update to be affected. In my case, updating, and trying to progress any kill quest shows the problem.

I've had to revert to 5.1.6-b523, as that does work as intended.

### Any console errors to share?

```shell
The log had no errors.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom1:
    name: Get rid of the drowned
    ask-message: Please get rid of the drowned plaguing Atlantis!
    finish-message: The citizens of Atlantis have been saved!
    npc-giver-uuid: a2d4dedd-6528-46fa-b4a2-413030a0ee60
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 4189
      type: DROWNED_SPAWN_EGG
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Drowned
          mob-amounts:
          - 25
          locations-to-kill:
          - world -1204.0 30.0 801.0
          kill-location-radii:
          - 80
          kill-location-names:
          - Atlantis
          finish-event: NiceFinish
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 4189
        type: LAPIS_BLOCK
        amount: 10
      money: 200
      quest-points: 1
      commands:
      - f powerboost player add <player> 1
    planner:
      cooldown: 604800
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
