### ISSUE TITLE
Console Spamming

### ISSUE THREAD

**Issue by ultravi0let27** [PikaMug/Quests#2331]
### What is your Quests version / build number (do *not* say "latest")?

5.1.6

### Describe the problem and how to replicate it.

I added a placeholder in the scoreboard which was %quests_player_current_objectives_<quest>% and it started spamming the console

### Any console errors to share?

```shell
[18:15:47 ERROR]: [Quests] Quest was null when getting objectives for Tristytan
[18:15:48 ERROR]: [Quests] Quest was null when getting objectives for Tristytan
[18:15:48 ERROR]: [Quests] Quest was null when getting objectives for Tristytan
[18:15:49 ERROR]: [Quests] Quest was null when getting objectives for Tristytan
[18:15:49 ERROR]: [Quests] Quest was null when getting objectives for Tristytan
[18:15:50 ERROR]: [Quests] Quest was null when getting objectives for Tristytan
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000002':
    name: Guide
    ask-message: Start of your legacy
    finish-message: Time to start your biggest Adventure!
    npc-giver-uuid: 905914fb-e78d-4fe5-a6ab-439a69837f74
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3955
      type: GRASS_BLOCK
    stages:
      ordered:
        '1':
          npc-uuids-to-talk-to:
          - dd49d132-f9ba-48ec-a54a-969137b409a6
          delay: 19
          start-message: '&b&lHello, my name is &c&lRobert&b&l. Welcome to &6&lGoldenhatch&b&l.
            I am the one that welcome new people to our town. There a mysterious man
            there, that like to talk to people. Go check what up with him.'
        '2':
          npc-uuids-to-talk-to:
          - c698b40f-442b-4e4e-b308-700b0ae4dd40
          start-message: '&fYou: &#00ff6eMaybe we can buy something from the shop
            now. Lets follow the signs.'
          complete-message: '&3Welcome! What can i do for you today?'
    rewards:
      money: 150
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
