### ISSUE TITLE
Plugin spamming message about "Task 21" causing an exception.

### ISSUE THREAD

**Issue by diegoandersonjr** [PikaMug/Quests#2332]
### What is your Quests version / build number (do *not* say "latest")?

Version 5.2.1

I also tried downgrading to 5.2.0 to the same result.

### Describe the problem and how to replicate it.

Upon logging into the server (and suddenly as the plugin has worked fine in months past) we get repeated spam of the message attached in the below field. The message says that 'Task #21' is causing an exception. I tried one by one clearing quests to see which it was but after all were deleted and the plugin reloaded still the console error persists. I would like to solve the issue as I love the plugin otherwise. Thanks!

### Any console errors to share?

```shell
//The code below loops over and over as soon as someone joins the server, quickly filling up the server console.//


[02:52:46] [Server thread/WARN]: [Quests] Task #21 for Quests v5.2.1-b528 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "location" is null
	at Quests-5.2.1.jar/me.pikamug.quests.dependencies.npc.citizens.BukkitCitizensDependency.getNpcsByLocationPredicate(BukkitCitizensDependency.java:63) ~[Quests-5.2.1.jar:?]
	at Quests-5.2.1.jar/me.pikamug.quests.dependencies.npc.BukkitNpcDependency.getNpcsByNearbyLocationSquared(BukkitNpcDependency.java:31) ~[Quests-5.2.1.jar:?]
	at Quests-5.2.1.jar/me.pikamug.quests.tasks.BukkitNpcEffectThread.run(BukkitNpcEffectThread.java:37) ~[Quests-5.2.1.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-172-09f1f88]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.4.jar:1.21.4-172-09f1f88]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1659) ~[paper-1.21.4.jar:1.21.4-172-09f1f88]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1529) ~[paper-1.21.4.jar:1.21.4-172-09f1f88]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[paper-1.21.4.jar:1.21.4-172-09f1f88]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-172-09f1f88]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
//Here are the first 3. I can provide the full file if helpful.//

quests:
  '000001':
    name: Arrival
    ask-message: '{{TUTORIAL QUEST - TYPE OR CLICK ''yes'' IN CHAT}} It is time to
      begin your journey...'
    finish-message: You have completed your first quest. Now a choice awaits, climb
      to freedom OR stay and explore for more quests...
    block-start: Paraguania 727.0 84.0 192.0
    stages:
      ordered:
        '1':
          locations-to-reach:
          - Paraguania 716.0 77.0 203.0
          reach-location-radii:
          - 5
          reach-location-names:
          - the info board
          start-message: Your journey begins! Head outside and find the quest pillar
            and info board.
          complete-message: Excellent! You made it, please read and once ready it
            is time to find the house of no doors...
        '2':
          npc-uuids-to-talk-to:
          - 9cd6532b-5729-4c37-927b-3a210e5da311
          locations-to-reach:
          - Paraguania 729.0 79.0 224.0
          reach-location-radii:
          - 7
          reach-location-names:
          - the house of no doors
          start-message: Find the house of no doors...he forgives...he watches
          complete-message: You are getting closer to the light. It is almost time
            to begin the climb.
        '3':
          locations-to-reach:
          - Paraguania 693.0 75.0 204.0
          reach-location-radii:
          - 4
          reach-location-names:
          - the old bridge
          start-message: Reach the bridge, your first of many choices awaits.
    rewards:
      exp: 27
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
  '000002':
    name: Ascend
    ask-message: It is time to climb...start your journey and gain your permissions
    finish-message: Well done!
    block-start: Paraguania 685.0 83.0 204.0
    stages:
      ordered:
        '1':
          locations-to-reach:
          - Paraguania 670.0 110.0 213.0
          reach-location-radii:
          - 3
          reach-location-names:
          - Paraguania Outlands
          finish-event: spawnset
          start-message: begin the climb
          complete-message: You made it. Now you make your first of many choices...
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
  '000003':
    name: What Lies Below
    ask-message: Explore the market and find the special shopkeep...I hear he has
      a secret or two.
    finish-message: Well done!
    block-start: Paraguania 686.0 77.0 206.0
    stages:
      ordered:
        '1':
          locations-to-reach:
          - Paraguania 683.0 76.0 231.0
          reach-location-radii:
          - 6
          reach-location-names:
          - the market
          start-message: Head into the market and take a look around.
          complete-message: You made it, now to find that shopkeep...
        '2':
          npc-uuids-to-talk-to:
          - ad691add-e257-40c9-b651-fa811f97859c
          complete-message: Maybe something he is saying is useful?
        '3':
          locations-to-reach:
          - Paraguania 696.0 66.0 198.0
          reach-location-radii:
          - 3
          reach-location-names:
          - the hidden treasure
          start-message: I should make sure I listened to that shopkeep...
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 4189
        type: STONE_AXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"text":"","extra":["Shopkeeps Axe"]}'
          lore:
          - '{"text":"","extra":["an old but trusty axe"]}'
      - ==: org.bukkit.inventory.ItemStack
        v: 4189
        type: APPLE
        amount: 8
      - ==: org.bukkit.inventory.ItemStack
        v: 4189
        type: IRON_INGOT
      exp: 16
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
