### ISSUE TITLE
Console spamming error

### ISSUE THREAD

**Issue by Yiiitt** [PikaMug/Quests#2341]
### What is your Quests version / build number (do *not* say "latest")?

5.2.1-b528

### Describe the problem and how to replicate it.

When I enter the game, an error message is spammed in the console

### Any console errors to share?

```shell
[15:55:46 WARN]: [Quests] Task #190 for Quests v5.2.1-b528 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "location" is null
        at Quests-5.2.1.jar/me.pikamug.quests.dependencies.npc.citizens.BukkitCitizensDependency.getNpcsByLocationPredicate(BukkitCitizensDependency.java:63) ~[Quests-5.2.1.jar:?]
        at Quests-5.2.1.jar/me.pikamug.quests.dependencies.npc.BukkitNpcDependency.getNpcsByNearbyLocationSquared(BukkitNpcDependency.java:31) ~[Quests-5.2.1.jar:?]
        at Quests-5.2.1.jar/me.pikamug.quests.tasks.BukkitNpcEffectThread.run(BukkitNpcEffectThread.java:37) ~[Quests-5.2.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[slimeworldmanager-1.21.3.jar:1.21.3-16529-fb817aa]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[slimeworldmanager-1.21.3.jar:1.21.3-16529-fb817aa]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1819) ~[slimeworldmanager-1.21.3.jar:1.21.3-16529-fb817aa]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1680) ~[slimeworldmanager-1.21.3.jar:1.21.3-16529-fb817aa]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1345) ~[slimeworldmanager-1.21.3.jar:1.21.3-16529-fb817aa]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[slimeworldmanager-1.21.3.jar:1.21.3-16529-fb817aa]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
quests:
  '000001':
    name: Tembel Madenci
    ask-message: Biraz taşa ihtiyacım var. Biliyorum sıkıcı bir iş ancak bana sadece
      sen yardım edebilirsin
    finish-message: Bu odunları satmak için senden istemiştim. Aslında ihtiyacım yok
      eh neyse işte biraz para
    stages:
      ordered:
        '1':
          break-block-names:
          - STONE
          - COBBLESTONE
          break-block-amounts:
          - 256
          - 256
          break-block-durability:
          - 0
          - 0
    rewards:
      money: 750
      quest-points: 1
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
  '000002':
    name: Oduncunun Rüyası
    ask-message: Evlat, korkma. Ben o şişko madenci gibi keyfim için senden bir şey
      istemeyeceğim. Gerçekten ihtiyacım var. Admin, benden 1 saat içinde 400 odun
      getirmemi istedi. Kolaysa kendin bul! demek isterdim ama biliyorsun... Bana
      yardım edecek misin
    finish-message: Sana çok teşekkür ederim! Sayende 400 odunu admin'e zamanında
      ulaştırdım.
    requirements:
      quest-points: 1
    stages:
      ordered:
        '1':
          break-block-names:
          - OAK_LOG
          break-block-amounts:
          - 400
          break-block-durability:
          - 0
    rewards:
      money: 1500
      quest-points: 1
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
  '000003':
    name: Karanlık
    ask-message: Karanlık yayılmaya devam ediyor. Bize cesur ada sakinleri lazım!
      Cesaretini kanıtlamak için 10 iskelet öldür.
    finish-message: Sen gerçekten göründüğünden daha cesurmuşsun! İşte, hak ettiğin
      ödül.
    requirements:
      quest-points: 2
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Spider
          mob-amounts:
          - 10
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 4082
        type: DIAMOND_SWORD
      money: 450
  '000004':
    name: Sevgi
    ask-message: 3 Koyun traş et
    finish-message: 3 Koyun traş ettin tebrik ederim. Eee, hep tonla para ödülü alacak
      değilsin ya, işte biraz saman.
    requirements:
      quest-points: 3
    stages:
      ordered:
        '1':
          sheep-to-shear:
          - White
          sheep-amounts:
          - 3
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 4082
        type: WHEAT
        amount: 40
      money: 3
      quest-points: 1
  '000005':
    name: Kelle Avı
    ask-message: Güçlü olman lazım. 10 oyuncuyu öldürerek cesaretini ve gücünü kanıtla.
    finish-message: 10 oyuncuyu alt ettin. Cesaretin ve gücün takdire şayan! Ödüllerin
      seni bekliyor. Bir sonraki meydan okuma için hazır ol!
    requirements:
      quest-points: 5
    stages:
      ordered:
        '1':
          players-to-kill: 10
    rewards:
      money: 3000
      quest-points: 1
      exp: 1000
  '000006':
    name: Netherionun Taşları
    ask-message: Netherion dünyasında neler olup bittiğini bilmem gerek. Oradan 256
      taş getir ki inceleme yapabileyim.
    finish-message: Taşlar için teşekkürler, bunlar hep bilim için! Adamım işte, ödülün
      seni bekliyor!
    requirements:
      quest-points: 6
    stages:
      ordered:
        '1':
          break-block-names:
          - NETHERRACK
          break-block-amounts:
          - 256
          break-block-durability:
          - 0
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 4082
        type: DRAGON_BREATH
      - ==: org.bukkit.inventory.ItemStack
        v: 4082
        type: REDSTONE
      - ==: org.bukkit.inventory.ItemStack
        v: 4082
        type: GLOWSTONE_DUST
      - ==: org.bukkit.inventory.ItemStack
        v: 4082
        type: GHAST_TEAR
      - ==: org.bukkit.inventory.ItemStack
        v: 4082
        type: NETHER_WART
      - ==: org.bukkit.inventory.ItemStack
        v: 4082
        type: BLAZE_ROD
      quest-points: 1
      exp: 500
```
