### ISSUE TITLE
Item turn in quest no longer works after update from 1.21 to 1.21.4

### ISSUE THREAD

**Issue by CordlessDeWalt** [PikaMug/Quests#2348]
### What is your Quests version / build number (do *not* say "latest")?

Quests Version 5.2.2-b533

I have been using the version for 1.21 and recently updated to the newer 1.21.4 and this issue started happening.

### Describe the problem and how to replicate it.

I have a turn in item to NPC quest. I created the quest just fine, it starts with the person I turn it in to and the accept goes ok. I then have the items and right/left click the NPC with the items and they don't turn in.

I tried with carrots and I would just eat the carrot
I now have tried with hay bales and nothing either.

### Any console errors to share?

```shell
no errors in the console and no errors in the chat.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000001':
    name: Need a carrot
    ask-message: Hey I need one last carrot for my recipe, can you help me?
    finish-message: Perfect, thank you so much!
    npc-giver-uuid: b7e80500-9363-4d9f-96ed-87243ea9bdaa
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 4189
            type: HAY_BLOCK
            amount: 32
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              attribute-modifiers:
                minecraft:attack_damage:
                - ==: org.bukkit.attribute.AttributeModifier
                  amount: 0.0
                  operation: 2
                  key: minecraft:76978531-ada4-47c2-b405-7362977cc55e
              ItemFlags:
              - HIDE_ATTRIBUTES
              - HIDE_ADDITIONAL_TOOLTIP
          npc-delivery-uuids:
          - b7e80500-9363-4d9f-96ed-87243ea9bdaa
          delivery-messages:
          - §rThank you. Only §5<amount> §rmore to go!
    rewards:
      money: 20
    planner:
      start: 20:6:2024:23:44:51:Etc/UTC
      cooldown: 10
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
      give-at-login: false
      allow-stacking-global: true
      inform-on-start: true
```

**Comment by CordlessDeWalt** [comment]
I also updated to the newest Dev build (5.2.3-b535) and it still does not work. Other quests work ok, but turning something in is having trouble

**Comment by PikaMug** [comment]
Minecraft 1.21.3 and 1.21.4 caused breaking changes for many plugins. The HAY_BLOCK that you're using looks to be some kind of custom item, which could have either broken from the update or had its metadata changed by whichever plugin created it. Either way, there has never been official support for custom items in Quests without the use of a module.

If you're unable to [have a module created](https://pikamug.gitbook.io/quests/casual/modules#want-support-for-other-plugins-or-features) for integration with whichever item plugin the HAY_BLOCK is from, try using said plugin to regenerate the item, then add it to your quest again. Best of luck!

**Comment by CordlessDeWalt** [comment]
The hay block as far as I know is not a custom item, I don't have any
plugins that created any custom items it is directly from the creative
screen where you can choose items.

I did find that I made a different NPC and different quest and did the same
thing with cobblestone and that did work, so I'm going to delete the NPC
and the quest for the hay and try to create everything from the ground up
both the NPC and the quest again and see if that makes a difference

407 467 6875
Graham Ober - President, Ober Consulting and Design
***@***.***

**Comment by PikaMug** [comment]
@CordlessDeWalt In your case, this part of your quest indicates that the HAY_BLOCK has custom data:
```yaml
attribute-modifiers:
  minecraft:attack_damage:
  - ==: org.bukkit.attribute.AttributeModifier
  amount: 0.0
  operation: 2
  key: minecraft:76978531-ada4-47c2-b405-7362977cc55e
```

I've done a little web searching, and this means its Attack Damage (damage dealt by attacks) has been modified. Besides the MC version changing, the `key:` part could also be problematic, as it may change or become invalid from version upgrades.

Taking items from the vanilla Creative GUI shouldn't do this, so most likely a plugin is modifying the event. You might try acquiring the new 1.21.4 item another way, such as the `/minecraft:give` command or mining one directly from a Village.
