### ISSUE TITLE
error check

### ISSUE THREAD

**Issue by hugo1009810098** [PikaMug/Quests#2351]
### What is your Quests version / build number (do *not* say "latest")?

5.2.3

### Describe the problem and how to replicate it.

[Quests] Stage cannot be empty, see quest 9 stage 1
[Quests] Unable to load custom objectives because stage0 for 9 was null

i check quest 0009 and nth strage just give 640 honey block to a npc

### Any console errors to share?

```shell
[Quests] Stage cannot be empty, see quest 9 stage 1
[Quests] Unable to load custom objectives because stage0 for 9 was null
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000009':
    name: 收集640顆蜂蜜塊
    ask-message: 挑戰目標！
    finish-message: 做得好！
    block-start: WorldSpawn1 -42.0 57.0 -136.0
    requirements:
      quest-points: 26
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 4189
            type: HONEY_BLOCK
            amount: 640
          npc-delivery-uuids:
          - 5c8024c4-ee43-471f-83b2-ea31d9b17f83
          delivery-messages:
          - 謝謝你。只剩下 <amount> 了！
    rewards:
      money: 86000
      quest-points: 2
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```
