### ISSUE TITLE
LocaleLib Error

### ISSUE THREAD

**Issue by BayloraiEX** [PikaMug/Quests#2353]
### What is your Quests version / build number (do *not* say "latest")?

Quests Version 5.2.3-b537

### Describe the problem and how to replicate it.

When accepting a quest you never get to see the requirements needed for the quest like your suppose to

![Image](https://github.com/user-attachments/assets/236d7f4b-4880-4ecd-a481-c52084fb0656)

### Any console errors to share?

```shell
Yes this error comes into console whenever a quest is accepted ( Photo is also above )

[LocaleLib] Unable to query Material:
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
quests:
  '000001':
    name: Cobble Gobbler
    ask-message: Adventurer! So glad to hear from you, Are you interested in helping
      me out?
    finish-message: You did it Adventurer! Thank you for your help.
    stages:
      ordered:
        '1':
          break-block-names:
          - STONE
          break-block-amounts:
          - 1000
          break-block-durability:
          - 0
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 4325
        type: CHISELED_STONE_BRICKS
        amount: 64
      quest-points: 1
    planner:
      cooldown: 300
```
