### ISSUE TITLE
action : items to brew

### ISSUE THREAD

**Issue by Ednaph** [PikaMug/Quests#2356]
### What is your Quests version / build number (do *not* say "latest")?

My quest version is: 5.2.3-b537 and 5.2.1-b

### Describe the problem and how to replicate it.

We've detected a bug in the potion brewing quests.

Simply place a hopper on the brewing stand. Add the already crafted potion, and the quest is counted. I've attached a screenshot of the setup ont the discord [quests.](https://media.discordapp.net/attachments/510222124237979674/1385350391444668446/image.png?ex=6855bf97&is=68546e17&hm=2bcffe0fed375a22ac79d1a6c804a38d8e12cab3c1a4d1c86f83d9d74dccd25d&=&format=webp&quality=lossless)

The bug also works by replacing a previously crafted potion with a water flask. Simply swap the bottles in a loop.

### Any console errors to share?

```shell
No errors
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000156':
    name: Alchimiste 1 quotidien (facile)
    ask-message: Accomplissez cette quête pour obtenir votre récompense quotidienne.
    finish-message: Bien joué, cette quête sera de nouveau disponible à 08h00.
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 4189
      type: POTION
      meta:
        ==: ItemMeta
        meta-type: POTION
        attribute-modifiers:
          minecraft:attack_damage:
          - ==: org.bukkit.attribute.AttributeModifier
            amount: 0.0
            operation: 2
            key: minecraft:98b298f0-1f59-4d62-a632-48557f5b92fa
        ItemFlags:
        - HIDE_ATTRIBUTES
        - HIDE_ADDITIONAL_TOOLTIP
    stages:
      ordered:
        '1':
          items-to-brew:
          - ==: org.bukkit.inventory.ItemStack
            v: 4189
            type: POTION
            amount: 2
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:swiftness
          objective-override:
          - Brasser <count> potions de rapidité.
    rewards:
      money: 5500
      commands:
      - jobs exp <player> Alchimiste add 20
      - pgive <player> 1 Jobcoins
      details-override:
      - Vous avez reçu 5500 skydollards.
      - Vous avez reçu 20 point d'expérience dans votre métier Alchimiste.
      - Vous avez reçu 1 Jobcoins.
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true


Sorry i'm french :p
```
