### ISSUE TITLE
Add "delay" option for Event system

### ISSUE THREAD

**Issue by jajamic** [PikaMug/Quests#701]
Hello everyone,

Faced with my previous request (#699), I could not find a solution. I would like to suggest that this system be coded:
- A system of "delays / timer" activation for an event as I had mentioned like that (delay is 10sec) :
```
events:
  startq:
    commands:
    - /playsound ac.environment.quests voice <player> ~ ~ ~ 10000.0
    delay: 10
```

From what I understood it is not so difficult to add as functionality, it would be a real plus for the plugin and give interesting possibilities. For exemple my next plugin use : https://pastebin.com/VVHgi1jz

Not being good enough in coding, I am ready to finance this addition if it is necessary.

Sorry for this new post but you are my only chance
