### ISSUE TITLE
24h planner repeat still not working

### ISSUE THREAD

**Issue by SXRWahrheit** [PikaMug/Quests#741]
**What is your Quests version / build number (do _not_ say "latest")?**

3.6.4-b397

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

No errors, but players don't get their daily quests available (ctrl+f daily in the file) again after completion.

![2019-03-17 07_18_40-#minecraft - Discord](https://user-images.githubusercontent.com/774463/54490569-ed8f8680-4884-11e9-8068-617418edf500.png)

I force-completed the cocoa daily for myself today, I'll check whether it resets tonight.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

1-week expiry: https://pastebin.com/mFVNpEzB

**Comment by Gartentrulla** [comment]
I have the same problem for Germany. I have the version 697 date 11th of march 2019 and not the new one date 12th of march 2019. The old one doesn't work. Please, can you upload the changes of 12th of march?
Thanks and best regards. Gartentrulla

**Comment by PikaMug** [comment]
What is the specific message the player gets in-game after 24+ hours have elapsed?

**Comment by PikaMug** [comment]
Also if you could post only the single relevant quest in a Pastebin that won't expire, it'd be appreciated.

**Comment by SXRWahrheit** [comment]
![2019-03-17_21 48 46](https://user-images.githubusercontent.com/774463/54503728-8ca49480-48fe-11e9-9691-8f7207c30711.png)

Sure - was just trying to be thorough; as you know, Quests only supports one .yml file for loading quests, and the GitHub instructions request the entire file.

```yaml
  Daily Cocoa:
    name: Cocoa for the countrymen (Daily)
    planner:
      start: 30:2:2018:19:0:0:SystemV/EST5
      end: 30:3:2018:19:0:0:SystemV/EST5
      repeat: 86400
    npc-giver-id: 25
    ask-message: <darkgreen>We need 5 stacks of coacoa today to feed the people, can
      you help?
    finish-message: <darkgreen>Thank you kindly, your efforts are most appreciated!
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-ink_sack:amount-320:data-3
          npc-delivery-ids:
          - 25
          delivery-messages:
          - Thanks, keep it up!
    rewards:
      money: 50
      quest-points: 1
```
