### ISSUE TITLE
Commands display rewards

### ISSUE THREAD

**Issue by tiradorus** [PikaMug/Quests#849]
**What does your feature do?**

Add an option to disable the commands-rewards-display.
Please, seriously, i pray for it, help me xD It's hardly ugly why is it like that?
We already have a finish-message of every quest, if i want another message displayed, i just have to add a commands-reward of message for the player, or even easier a complete-message on the last stage.

But don't let us fight with a non removable message xD It's ugly! Look at that:

(Non commands-rewards display modified)
https://i.imgur.com/qavljfU.png

Looks! xD Seriously, it's like that for every quest, so i've tryed to take it off, players don't have to see that, so i've done it like that:

```
    rewards:
      commands:
      - rg addmember zone3 <player> -w Tutoriel
      - class exp <player> 400
      - questadmin give <player> Compétences des classes
      commands-override-display:
      - ''                    <==================
    options:
      allow-commands: true
      allow-quitting: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
```
https://i.imgur.com/RBbmPLN.png

But as you can see, there is a white rewards shown, it's useless! And i can't remove it!

I just want to have what i had in 3.6.8 ... 
Somthing like that:
**Rewards:
Finish message**

That's all xD

Please do it for us, or just for me but add a way to disable the commands-display ... Even if it's like that:

```
    rewards:
      commands:
      - rg addmember zone3 <player> -w Tutoriel
      - class exp <player> 400
      - questadmin give <player> Compétences des classes
      commands-override-display:
      - 'NONE'                                     <================
    options:
      allow-commands: true
      allow-quitting: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
```

Ps: There is a little bug, when you change the set-Command-display-overrides, then the 'Menu' of the quest editor isn't displayed in the chat ... you still can continue to editing, but you can't see anything else, nothing is displayed after that.

Have a nice day! =)
