### ISSUE TITLE
Quests rewards disappear

### ISSUE THREAD

**Issue by Chapata** [PikaMug/Quests#888]
Version: 3.7.7

When claiming the reward of a finished quest, it doesnt give items.
It gives the money and the quest points, but not the items.
I edited the quest from the quest editor 3 o 4 times, and every time it appeared as if there wasn't any item reward, althought in the quests.yml it appears.

I don't really know how to replicate the bug. All I know is that when you set the item reward and you edit the quest again, it shows the item, but after a while if a player tries to claim the rewards, he doesn't get the item and the quest show no item reward again.

My Quests.yml file is the one attached.

```
# For non-English characters, this file MUST stay encoded in UTF-8
quests:
  custom1:
    name: Un comienzo
    npc-giver-id: 45
    ask-message: Si me demuestras que sabes lo básico y me traes 3 diamantes, te daré
      una recompensa
    finish-message: Finaliza tu misión
    gui-display: name-STONE_PICKAXE:amount-1
    stages:
      ordered:
        '1':
          break-block-names:
          - OAK_LOG
          - STONE
          break-block-amounts:
          - 64
          - 256
          break-block-durability:
          - 0
          - 0
          items-to-craft:
          - name-IRON_PICKAXE:amount-1
          - name-IRON_SWORD:amount-1
          - name-IRON_AXE:amount-1
          - name-IRON_SHOVEL:amount-1
          mobs-to-kill:
          - Zombie
          - Skeleton
          - Spider
          - Creeper
          mob-amounts:
          - 5
          - 3
          - 3
          - 1
          start-message: '&bBuena suerte! Ve con cuidado..'
        '2':
          items-to-deliver:
          - name-DIAMOND:amount-3
          npc-delivery-ids:
          - 45
          delivery-messages:
          - '&aVaya, ya has vuelto!'
          complete-message: '&bToma esto, mucha suerte!'
    rewards:
      items:
      - name-DIAMOND_PICKAXE:amount-1:enchantment-DIG_SPEED 1:displayname-§6§lPico
        de Ryan:lore-Desprende una especie de magia...:meta-type-UNSPECIFIC:enchants-{DIG_SPEED=1}
      - name-BREAD:amount-12:displayname-§6§lChapata:lore-Todavía está caliente...:lore-¿Donde
        los guardaría?:meta-type-UNSPECIFIC
      money: 250
      quest-points: 5
    options:
      allow-commands: true
      allow-quitting: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
```
