### ISSUE TITLE
Action not Available

### ISSUE THREAD

**Issue by frost-byte** [PikaMug/Quests#904]
**Quests version / build number**
3.8.0-b19

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Steps to Reproduce Issue:
  1. Create an Action
  1. Specify the name, in this case GiveLitter.
  1. Select the 'Player' option.
  1. Select the option to give an item
  1. Select the item to be used in your action bar (1 Cocoa bean)
  1. Specify option 0, to use the item you're holding.
  1. Use option 5 to set the display name - Kitty Litter.
  1. Save the action
  1. Reload using /questsadmin reload.
  1. /quests actions - **The action is not in the list**

Looking in the actions.yml for the action, I see that the item has been serialized and is not using the old format. (Like the one for the GiveRod action, i.e. - `name-fishing_rod:amount-1`)

```yaml
  GiveLitter:
    message: <aqua>You have received some Kitty Litter.
    items:
    - ==: org.bukkit.inventory.ItemStack
      v: 1976
      type: COCOA_BEANS
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: Kitty Litter
```
