### ISSUE TITLE
attempted to take quest "null" but something went wrong

### ISSUE THREAD

**Issue by myfbone** [PikaMug/Quests#917]
**What is your Quests version / build number (do _not_ say "latest")?**

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
version 3.7.8-b16

I have all needed permissions for players:
quests.quests
quests.list
quests.take
quests.quit
quests.stats
quests.top
quests.info
quests.journal
quests.quest
quests.questinfo

And this is my quest:
```
quests:
  custom2:
    name: Убить свинозомби
    npc-giver-id: 84
    ask-message: §eУбей как можно больше этих гадких §dсвинозомби§e! За каждую §dсотню§e
      я дам тебе §d1000§e монет!
    finish-message: §eМолодец! Меньше свинозомби - лучше.
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Pig Zombie
          mob-amounts:
          - 100
    rewards:
      money: 1000
    planner:
      cooldown: 1
    options:
      allow-commands: true
      allow-quitting: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
```

When I get this quest as op it's okay, but when I try to get is a regular player I get this:
```
[09:11:58 INFO]: [Quests] tester12 attempted to take quest "null" but something went wrong
```
