### ISSUE TITLE
different potion levels are not distinguished

### ISSUE THREAD

**Issue by Sponge1996** [PikaMug/Quests#954]
**What is your Quests version / build number (do _not_ say "latest")?**
Plugin Version: 3.8.0-b34
Server Version: 1.14.4 Paper
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I once brewed all potions and noticed that on the one hand potion levels don't include sorting and it doesn't make any difference which level of potion you use when brewing because the first potion is always completed by the name.

![brau1](https://user-images.githubusercontent.com/18584669/66430160-d0d1c080-ea19-11e9-9ffa-250e12442798.png)

That's part of the potions. It looks the same with the others.

![liste1](https://user-images.githubusercontent.com/18584669/66430336-28702c00-ea1a-11e9-80a4-eeb6b9087ca9.png)
![liste2](https://user-images.githubusercontent.com/18584669/66430338-2a39ef80-ea1a-11e9-83f0-4c4f9216a848.png)
![liste3](https://user-images.githubusercontent.com/18584669/66430342-2c03b300-ea1a-11e9-8bda-f5039db46bce.png)

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/RpSWAgxx

**Comment by PikaMug** [comment]
As far as I can tell, the issue stems from how an ItemStack is saved to file. I'll look into whether it's possible to correct this, but I cannot guarantee a solution at this time.

**Comment by PikaMug** [comment]
My initial hypothesis was incorrect. ItemStacks are being saved correctly to file, as shown here:
```
          items-to-brew:
          - ==: org.bukkit.inventory.ItemStack
            v: 1631
            type: POTION
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:long_water_breathing
```
Note the "long_" water breathing, indicating the 8:00 minute amplifier rather than the base 3:00.

The trick, so to speak, is to load the item _from your hand_ using option '0' in the Create Item prompt. This allows the appropriate metadata to be loaded, whereas simply setting the item name does not.
