### ISSUE TITLE
Can't add multiple Command triggered Actions to a stage v2

### ISSUE THREAD

**Issue by LegitMeme** [PikaMug/Quests#971]
What is your Quests version / build number (do not say "latest")?
3.8.0-b5
Describe the problem and how to replicate it. Any console errors to post using Pastebin.com?
Console Errors: None.
How to replicate?:
Firstly, I made a new Quest, I made a new stage and added a goal (Talk to "NPC"), then I went to the actions menu of the stage and added 4 "Command Action" Actions. When I save the Quest and start editing it again, every "Command Action" Actions I added except for the last one dissapear.
If applicable, can you provide an example quest from quests.yml using Pastebin.com?
No example, but I can tell you that the "Command Action" Actions I add do not save into the Quest.yml file and when I try to add the multiple Actions into the file manually they dissapear (Except for of course the last one added) after starting the serve

**Comment by LegitMeme** [comment]
PS: Fixes from last post didn't work... here a video of the problem: https://vimeo.com/365956560

**Comment by PikaMug** [comment]
"Last post" being referred to is #962 

Thanks for your report. I wasn't able to replicate the issue you've described using the Spigot release of Quests 3.8.0 on a MC 1.13 server. I was able to create and complete a quest while triggering all command actions. Here's the quest I created as it appears in quests.yml:

```
  custom5:
    name: actiontest
    ask-message: pls
    finish-message: ty
    stages:
      ordered:
        '1':
          break-block-names:
          - dirt
          break-block-amounts:
          - 1
          break-block-durability:
          - 0
          start-event: NiceFinish
          command-events:
          - RodStart
          - GiveRod
          - NiceFinish
          - ThunderAction
          command-event-triggers:
          - sleep
          - night
          - best
          - please
    options:
      allow-commands: true
      allow-quitting: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
      require-same-quest: true
```
Please try upgrading to the Spigot release (equivalent to development build 34 ... you're currently on build 5) and check if the problem persists. If so, please provide your actions.yml file for testing.
