### ISSUE TITLE
Error with npc delivery

### ISSUE THREAD

**Issue by Prowco** [PikaMug/Quests#985]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.0

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
The problem is i set deliver to npc 3 stacks of cobblestone and 32 of coal but for some reason the npc just receive 64 of stone and 64 of coal and that dont have sense bc i put 32 of coal and 192 of cobblestone not 64 and 32 so i think this is  a bug of the npc deliver option with high numbers.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/RNgVZTar

**Comment by PikaMug** [comment]
Unfortunately, the amount cannot exceed 64 blocks. This is a limit enforced by Spigot/Minecraft. You should be able to split the 192 into multiple stacks, which would look like this in the file:
```
          break-block-names:
          - stone
          - stone
          - stone
          - coal_ore
          break-block-amounts:
          - 64
          - 64
          - 64
          - 32
          break-block-durability:
          - 0
          - 0
          - 0
          - 0
```

If that doesn't work after all, I'm afraid you'll have to split the amount across multiple stages.
